### ISSUE TITLE
Support for CORS?

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/owncloud-zimlet#1]
It would require us to add additional configuration at the DAV server... it will be a pain to support this after release:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by manens** [comment]
Dit you reject the usage of the Zimlet proxy for that ?
https://wiki.zimbra.com/wiki/Zimlet_Developers_Guide:Proxy_Servlet_Setup

The proxy can work correctly for some situations and if it can prevent the modification of the Nginx configucation, this can be a life saver.

**Comment by barrydegraaff** [comment]
Also very interesting suggestion, 

The problem with using proxies right now is that WebDAV breaks if your proxy is in a different location
on your ZCS then where WebDAV expects to be.

Like this would work:
https://zcsserver.com/owncloud/   (the proxy)
https://ocserver.blaap.com/owncloud/ (the owncloud)

This would not work:
https://zcsserver.com/documents/   (the proxy)
https://ocserver.blaap.com/owncloud/ (the owncloud)

As this would result in the DAV server to report: /documents is outside the document root == fail


CORS has the potential to fix that, as we could directly talk to the ownCloud server, but that would use
require to:
1. Find a DAV library that supports it
2. Alter the ownCloud server

Sending the correct CORS headers all the time in all cases, will be very hard. Also documenting
other use cases (liferay, alfresco) will be a pain.


So I will look into https://wiki.zimbra.com/wiki/Zimlet_Developers_Guide:Proxy_Servlet_Setup 
but I am not very hopeful at first glance.

**Comment by manens** [comment]
Ok, Take a deeper look, I am quite confident :)

With the Zimlet Proxy, the server is doing the request, so you will not face the browser security limits.

**Comment by barrydegraaff** [comment]
@manens Michele from ZeXtras looked into that JSP proxy, and it DOES NOT work, DAV methods are not supported:
1:03:19 PM - zx_bud: we are considering about to create a zimbra extension to proxy all the dav request, Is an option for you?
1:03:56 PM - zx_bud: I can confirm the zimbra poxy does not proxy the mkcoll, PROPFIND requests

Also I could not get that thing to work at all... but I only looked 5 minutes.

Also The DAV library I use will not understand the JSP proxy: So
https://myzvcs/service/proxysome.jsp?blaatlocation/dav/
DAV will have /service/proxysome.jsp?blaatlocation/dav/ inside the request
Then DAV server will say:
/service/proxysome.jsp?blaatlocation/dav/
is error 5XX outside the document root  as it only expects blaatlocation/dav/

Even if the JSP proxy works we still need to either find a different JavaScript DAV library or code the current one to understand the JSP proxy.

**Comment by barrydegraaff** [comment]
zmprov mc default +zimbraProxyAllowedDomains *.barrydegraaff.tk
zmprov gc default | grep zimbraProxyAllowedDomains
https://myzimbra.com/service/proxy?target=http://www.barrydegraaff.tk

This may be useful for something

**Comment by barrydegraaff** [comment]
Basically jsp proxy is an example zimlet, it would still need a lot of dev work, as it does not rewrite urls and all that, so you could follow links in http.

So not usefull for DAV, does not do anything except maybe if you need to get a single file from a different domain, like maybe rss feed or a json or something

**Comment by barrydegraaff** [comment]
Closing this as I will not be adding CORS support, there may be a next version developed here: https://github.com/ZeXtras/owncloud-zimlet/tree/soapService

That should do all this on the server side, eliminating the need for cors.
