### ISSUE TITLE
Problems with Send link or Send Attachment

### ISSUE THREAD

**Issue by kkhedman** [Zimbra-Community/owncloud-zimlet#100]
Zimbra 8.7.1 and owncloud 9.0.1 just installed owncloud-zimlet and it works unless adding files with "Send link, or Send Attachment" , it gives error like this:

https://pilvi.dvn.fi/index.php/s/pgTrlk3TGCQDAOW

Zimbra is in seperate server than owncloud server, is that the problem ? i can browse files ok.

**Comment by barrydegraaff** [comment]
Yep, the property owncloud_zimlet_oc_folder is not set correctly.If your owncloud is in a domain like:
https://myowncloud.com/ You need to clear the property (empty)

https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences

Or you need to set it correctly (https://myowncloud.com/owncloudsky) you need to set /owncloudsky

**Comment by kkhedman** [comment]
Uh sorry, new to this. Now it works. 

In short, these worked for me: 

DAV path: /remote.php/webdav/ 
Location ownCloud/Nextcloud: <just Empty Line> 

Regards, 
Kimmo Hedman
