### ISSUE TITLE
Open ownCloud tab ignores owncloud_zimlet_server_name

### ISSUE THREAD

**Issue by mnichols62** [Zimbra-Community/owncloud-zimlet#102]
owncloud zimlet version 0.6.6

My mailserver is at 
https://mail.mydomain.com

The config.properties file has 
owncloud_zimlet_server_name=https\://owncloud.mydomain.com

When I click on the link to "Open ownCloud tab", it directs me to 
https://mail.mydomain.com/owncloud
instead of 
https://owncloud.mydomain.com/owncloud

**Comment by barrydegraaff** [comment]
https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences

read table, the settings...
owncloud_zimlet_extra_toolbar_button_title	
owncloud_zimlet_extra_toolbar_button_url

After changing config.properties run the following:

Read on below table....

   wget https://github.com/Zimbra-Community/prop2xml/raw/master/out/artifacts/prop2xml_jar/prop2xml.jar -O /tmp/prop2xml.jar
   java -jar /tmp/prop2xml.jar tk_barrydegraaff_owncloud_zimlet /opt/zimbra/lib/ext/ownCloud/config.properties /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_owncloud_zimlet/config_template.xml

**Comment by mnichols62** [comment]
The config_template.xml has the correct value and it is still not being read:
<property name="owncloud_zimlet_server_name">https://owncloud.mydomain.com</property>

**Comment by barrydegraaff** [comment]
Try putting the entire url in the .properties file, then run java -jar /tmp/prop2xml.jar ...

To be sure, run zmprov fc all and flush your browser cache.

**Comment by barrydegraaff** [comment]
also you can remove the button, by setting an empty title.

**Comment by mnichols62** [comment]
Didn't work. I need the user to be able to launch ownCloud directly from there to incorporate Collabora.

**Comment by barrydegraaff** [comment]
I have not been able to reproduce this, perhaps there is something you are doing, that I did not test, the problem can't be that complicated. 

If you want me to debug it for you, maybe you can consider getting a support subscription
https://www.powercraft.nl/zetalliance/

**Comment by barrydegraaff** [comment]
did you run

     zmzimletctl configure config_template.xml ???

**Comment by barrydegraaff** [comment]
subscription case
