### ISSUE TITLE
A detailed result of SSO Owncloud zimlet 

### ISSUE THREAD

**Issue by redhat312** [Zimbra-Community/owncloud-zimlet#107]
Hi barry,

I hope you show me or do something to let me know a detailed result of SSO Owncloud Zimlet. In the previous version(<0.4.1), you noted that "After successful authentication users will be logged into both Zimbra and ownCloud" that i really confuses this case. Is this successful Owncloud access here logging in and no need to fill up text fields in the WebDav at Zimbra Zimblet Tab at the left side of Zimbra interface or something else? Can you show me or make a short video or explain clearly your results exacctly? Pls help me. I'm looking forward to your response.

**Comment by barrydegraaff** [comment]
The current version does not implement SSO, you have to store your credentials on the preferences to fake SSO. At this point I talked with the other devs on this project, and it seems SAML would be the solution to this problem.

I have not found time/budget to implement this yet.

**Comment by redhat312** [comment]
So in the previous version, is there any version that can carry out a SSO
ok?

**Comment by barrydegraaff** [comment]
The old version has some issues with owncloud 9 and up, and zimbra 8.7 and up.

So at the moment, NO.

**Comment by redhat312** [comment]
It means that in the past version, there was not any success in running a
sso?

**Comment by barrydegraaff** [comment]
Owh, it worked, but not many people seemed to have used it.

**Comment by redhat312** [comment]
Owh, THAT success was that user could log in single account and MUST NOT
input the credentials in the preferences of WebDav client tab. Right?

**Comment by wreckitkenny** [comment]
Hi Barry, 

I'm looking forward to your answer for my latest question. Pls. Many thanks!!
