### ISSUE TITLE
share with link does not work with nextcloud 10 and 11

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/owncloud-zimlet#109]
https://docs.nextcloud.com/server/11/developer_manual/core/ocs-share-api.html

All calls to OCS endpoints require the OCS-APIRequest header to be set to true.

**Comment by barrydegraaff** [comment]
Seems something else is going on as well, seems like patching it for Nextcloud, breaks ownCloud...

[OwnCloudClient.java.txt](https://github.com/Zimbra-Community/owncloud-zimlet/files/677327/OwnCloudClient.java.txt)
[nextcloud-share-api.patch.txt](https://github.com/Zimbra-Community/owncloud-zimlet/files/677328/nextcloud-share-api.patch.txt)

**Comment by lybrix** [comment]
I have a fresh install of zimbra 8.7.1 and nextcloud 11 on two different machines, both running ubuntu 16.04. I have successfully set the owncloudzimlet up and all works except link sharing. Upon trying to create a link share I get Unexpected response '401' which tells me something with authentication is wrong. Is this related to something already known? I am happy to test any ideas on possible solutions.

/Mikael

**Comment by barrydegraaff** [comment]
Yes, I need to find some time to rewrite the ownCloudClient.java, or find a way that works for both ownCloud and Nextcloud at the same time.

In the mean time you can use the binary below, copy-paste it to  /opt/zimbra/lib/ext/ownCloud/  and do zmmailboxdctl restart.

​dav-soap-connector-extension.jar  : https://powermail.nu/owncloud/index.php/s/UImtc84pn801HZV

**Comment by lybrix** [comment]
Thanks! I replaced the old binary with this one, did zmmailboxdctl restart, did still not work. Did a whole restart of the zimbra machine but the error is still the same.

I have searched the zimbra logs and pulled out he soap request in two text files, also placed a crop of the error popup there:
https://moln.lindecrantz.net/index.php/s/TsCYxE2dg9tNIoR

I have not been able to get any bright ideas as to what is the issue, will keep on looking.

**Comment by barrydegraaff** [comment]
Please check if you username and password are correct, and try one that does not contain characters other than A-Za-Z09 and _ or -.

**Comment by barrydegraaff** [comment]
@lybrix maybe you can send me a test account so I can check, in the mean time, I will try a fix this, but eta is next week.

**Comment by barrydegraaff** [comment]
Anyway, seems the code in OwnCloudClient.java is overly complicated, attached a simple java program that works in owncloud and nextcloud...

      nextcloud 11
      java Main https://intra.hivos.nl/nextcloud/ocs/v1.php/apps/files_sharing/api/v1/shares username password "Nextcloud Manual.pdf" 3 null

      owncloud 9.1
      java Main https://mail.hivos.org/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares username password "2016-10-31.webp" 3 null

[Main.java.txt](https://github.com/Zimbra-Community/owncloud-zimlet/files/690169/Main.java.txt)

**Comment by barrydegraaff** [comment]
the following sources should be removed 
/owncloud-zimlet/extension/src/com/zextras/owncloud/*

**Comment by barrydegraaff** [comment]
and re-do it based on a clean extension like https://github.com/Zimbra-Community/annoucements

**Comment by lybrix** [comment]
I did some testing and this is what I got. Initially, the account I tested with had a special char, still I could connect, traverse directories, upload and download files. But, no sharing via link, only as attachment. After changing the password I could share via link on nextcloud 11, but, setting a password on that share via the zimlet rendered the same error as before.

Then I also tested on owncloud 9.1 and there all works as expected.

**Comment by barrydegraaff** [comment]
@lybrix I also found that nextcloud has implemented a (undocumented) password policy in case the password is set to a public link share, I have implemented this in the solution... which is underway.

**Comment by barrydegraaff** [comment]
@lybrix the issues with the link share and 401 error is fixed in 0.6.9 for ownCloud 9.1 and Nextcloud 11.

**Comment by barrydegraaff** [comment]
@lybrix please run:

      wget --no-cache https://raw.githubusercontent.com/Zimbra-Community/owncloud-zimlet/soapServiceBarry/webdav-client-installer.sh -O /tmp/webdav-client-installer.sh
      chmod +rx /tmp/webdav-client-installer.sh
      /tmp/webdav-client-installer.sh 

To upgrade and apply the patch, you will need to flush browser and server cache also

**Comment by lybrix** [comment]
I did a quick test and got "Server error (unknown command sent to server)", could it be related to: [https://github.com/Zimbra-Community/owncloud-zimlet/issues/82](url)? I rolled back the change for now, will hopefully have some more time to test this evening.

**Comment by barrydegraaff** [comment]
@lybrix that is browser cache for sure... the old zimlet is talking to the new back-end.

Please remove your temporary internet files, or remove history in chrome, in most cases a browser restart will do the trick also.

**Comment by lybrix** [comment]
Thanks, clearing the cache did the trick, I should have been more thorough in the first place...

But, now there is another error popping up. Sharing in OC works like charm. Link sharing with NC on the other hand produces this error:
Exception thrown: java.lang.IllegalStateException: No match found

The error actually comes inline in the email itself, complete with the name of the item shared in front of it. Checking in NC shows that nothing got shared though.

**Comment by barrydegraaff** [comment]
That means Nextcloud did not return a result, maybe your nextcloud server sits behind a http redirect that is not followed.

What version of nextcloud do you use? I tested this feature against oc 9.1 and nc 11.

**Comment by lybrix** [comment]
nc 11, both clouds sits behind a apache reverse proxy, I switch out the path depending on which version I test. Nothing apart from the path is different.

**Comment by barrydegraaff** [comment]
I have not been able to reproduce this, perhaps there is something you are doing, that I did not test, the problem can't be that complicated.

If you want me to debug it for you, maybe you can consider getting a support subscription
https://www.powercraft.nl/zetalliance/

**Comment by barrydegraaff** [comment]
also you can send a test account to your nextcloud to info @ barrydegraaff dot tk so I can take a look

**Comment by barrydegraaff** [comment]
@lybrix try and update the OCS part:

      rm -f /opt/zimbra/lib/ext/OCS/*.jar
      cd /opt/zimbra/lib/ext/OCS
      wget --no-cache "https://github.com/Zimbra-Community/OCS/raw/master/extension/out/artifacts/OCS_jar/OCS.jar"

That one follows redirects if you have any, its the only thing I can think up that is wrong.

**Comment by barrydegraaff** [comment]
Dont forget to zmmailboxdctl restart after

**Comment by lybrix** [comment]
I looked through all the different options for the zimlet config once again and found that the owncloud/nextcloud location attribute was wrong. After changing that to / it all worked like a charm. So, human error on my part ;)

Thank you for really putting the effort in to help nailing it down! and to a great piece of integration between two great pieces of software.
