### ISSUE TITLE
Deploy Procedure for zimbra 8.6 to ubuntu 12.04.05

### ISSUE THREAD

**Issue by mbaesso** [Zimbra-Community/owncloud-zimlet#112]
Hi Barry De Graaff,
could you please let me known how to setup owncloud-zimlet in this environment
we try your istruction but have got some https handshake errors during get zal library, so process is stopping

thanks in advance

Mirko Baesso

**Comment by barrydegraaff** [comment]
Looks like the SSL cert for the server where openzal is downloaded from, is not trusted by your OS, probably because it is an older version of Ubuntu.

If you want me to debug it for you, maybe you can consider getting a support subscription
https://www.powercraft.nl/zetalliance/

**Comment by barrydegraaff** [comment]
Please retry, download and run the installer. As the latest installer no longer needs to connect to openzal.org, it may work on Ubuntu 12.
