### ISSUE TITLE
DAV Erreur Host name does not match the certificate

### ISSUE THREAD

**Issue by fl60** [Zimbra-Community/owncloud-zimlet#116]
Good evening,
I encountered a certificate problem when zimbra tries to connect to the webdav.
DAV Erreur Host name 'business.ovh.net' does not match the certificate subject provided by the peer (CN=ssl5.ovh.net, OU=PositiveSSL, OU=Domain Control Validated)
I use a shared server to host my owncloud. Would you have a solution to this problem?
Thank you in advance for your answer. I use a translator.

**Comment by barrydegraaff** [comment]
Yes, your SSL must be valid, please read all the steps here:
https://github.com/Zimbra-Community/owncloud-zimlet/wiki/Troubleshooting
