### ISSUE TITLE
Zimlet install problem - Zimbra 8.7.2 - Ubuntu 12.04

### ISSUE THREAD

**Issue by sematuszewski** [Zimbra-Community/owncloud-zimlet#117]
Hi, I have a problem.

Automated Zimbra WebDAV Client installer for single-server Zimbra 8.7 on CentOS 6 or 7 (Ubuntu untested)
- Installs ant and git, the WebDAV Client server extension and Zimlet.

Do you want to enable experimental document preview (tested on CentOS 7 and Ubuntu 14.04)? Y/n:
n

Do you want to automatically install Zimlet and force enable it in all COS'es?
If you choose n you have to run zmzimletctl, configuration COS and set config_template.xml manually.
If you have trouble or are unsure, choose Y. Y/n:
y

Do you want to install public link sharing?
If you use a WebDAV server that is not ownCloud or Nextcloud choose n.
If you have trouble or are unsure, choose Y. Y/n:
y
Check if git and ant are installed.
Remove old versions of Zimlet.
[] INFO: Uninstalling Zimlet tk_barrydegraaff_owncloud_zimlet from LDAP.
[] INFO: undeploying zimlet tk_barrydegraaff_owncloud_zimlet
[] INFO: zimlet directory tk_barrydegraaff_owncloud_zimlet is deleted
Saving existing configuration to /tmp/webdav-client-installer.xiQorUPw/upgrade
Download WebDAV Client to /tmp/webdav-client-installer.xiQorUPw
Cloning into 'owncloud-zimlet'...
remote: Counting objects: 955, done.
remote: Compressing objects: 100% (665/665), done.
remote: Total 955 (delta 429), reused 666 (delta 268), pack-reused 0
Receiving objects: 100% (955/955), 29.66 MiB | 3.47 MiB/s, done.
Resolving deltas: 100% (429/429), done.
Compiling WebDAV Client.
Buildfile: /tmp/webdav-client-installer.xiQorUPw/owncloud-zimlet/extension/build.xml

download-libs:
      [get] Getting: https://openzal.org/1.11/zal-1.11.4-8.7.2.jar
      [get] To: /tmp/webdav-client-installer.xiQorUPw/owncloud-zimlet/extension/lib/zal-1.11.4-8.7.2.jar
      [get] Error getting https://openzal.org/1.11/zal-1.11.4-8.7.2.jar to /tmp/webdav-client-installer.xiQorUPw/owncloud-zimlet/extension/lib/zal-1.11.4-8.7.2.jar

BUILD FAILED
/tmp/webdav-client-installer.xiQorUPw/owncloud-zimlet/extension/build.xml:64: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1902)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1074)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1320)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1347)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1331)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:432)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:660)
	at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:579)
	at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:569)

Total time: 1 second
ant jar
Buildfile: /tmp/webdav-client-installer.xiQorUPw/owncloud-zimlet/extension/build.xml

clean:
    [mkdir] Created dir: /tmp/webdav-client-installer.xiQorUPw/owncloud-zimlet/extension/build

compile:
    [javac] Compiling 152 source files to /tmp/webdav-client-installer.xiQorUPw/owncloud-zimlet/extension/build
    [javac] javac: invalid target release: 1.7
    [javac] Usage: javac <options> <source files>
    [javac] use -help for a list of possible options

BUILD FAILED
/tmp/webdav-client-installer.xiQorUPw/owncloud-zimlet/extension/build.xml:39: Compile failed; see the compiler error output for details.

Total time: 0 seconds
make: *** [extension] Error 1

**Comment by barrydegraaff** [comment]
Same as issue https://github.com/Zimbra-Community/owncloud-zimlet/issues/112

Seems Ubuntu 12 does not like the SSL certificate for openzal.org.

Work-around would be to either update your ssl certificate store (system and java), or install over http and not https. But that would require us to make that change for all users.

Problem here is that Ubuntu 12.04 is pretty much EOL (2 months left).
https://www.ubuntu.com/info/release-end-of-life

I can figure out how to add the SSL trust on Ubuntu 12, but maybe you can consider getting a support subscription first https://www.powercraft.nl/zetalliance/

**Comment by barrydegraaff** [comment]
It seems Ubuntu 12 uses sslv3, that is (for security reasons) not supported by openzal.org

**Comment by barrydegraaff** [comment]
Adding to readme, Ubuntu 12 is not supported as the SSL stack is outdated.

**Comment by barrydegraaff** [comment]
Please retry, download and run the installer. As the latest installer no longer needs to connect to openzal.org, it may work on Ubuntu 12.

**Comment by kansjee** [comment]
my installation of webdav always hangs at receiving objects. What could be the problem. see below the error
[root@mail tmp]# /tmp/webdav-client-installer.sh
Automated Zimbra WebDAV Client installer for single-server Zimbra 8.7 on CentOS 6 or 7 (Ubuntu untested)
- Installs ant and git, the WebDAV Client server extension and Zimlet.

Do you want to enable experimental LibreOffice document preview (tested on CentOS 7 and Ubuntu 14.04)? y/N:
You can later enable OnlyOffice document preview by configuring:
owncloud_zimlet_enable_onlyoffice and owncloud_zimlet_onlyoffice_api_url
It is OK to use both OnlyOffice and LibreOffice at the same time for document preview.
n

Do you want to automatically install Zimlet and force enable it in all COS'es?
If you choose n you have to run zmzimletctl, configuration COS and set config_template.xml manually.
If you have trouble or are unsure, choose Y. Y/n:
n

Do you want to install public link sharing?
If you use a WebDAV server that is not ownCloud or Nextcloud choose n.
If you have trouble or are unsure, choose Y. Y/n:
y
Check if git and ant are installed.
which: no apt-get in (/opt/zimbra/common/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/kannanadmin/.local/bin:/home/kannanadmin/bin)
Remove old versions of Zimlet.
Not touching COS per user request.
Saving existing configuration to /tmp/webdav-client-installer.5RnKwX6T/upgrade
Download WebDAV Client to /tmp/webdav-client-installer.5RnKwX6T
Cloning into 'owncloud-zimlet'...
remote: Counting objects: 429, done.
remote: Compressing objects: 100% (322/322), done.
Receiving objects:  10% (43/429), 6.75 MiB | 220.00 KiB/s

**Comment by kansjee** [comment]
I have centos 7 with zimbra 8.8.6. The git clone of the zimlets always hangs at 10% (43/429). What is the solution to this problem. 

[root@mail tmp]# /tmp/webdav-client-installer.sh
Automated Zimbra WebDAV Client installer for single-server Zimbra 8.7 on CentOS 6 or 7 (Ubuntu untested)
- Installs ant and git, the WebDAV Client server extension and Zimlet.

Do you want to enable experimental LibreOffice document preview (tested on CentOS 7 and Ubuntu 14.04)? y/N:
You can later enable OnlyOffice document preview by configuring:
owncloud_zimlet_enable_onlyoffice and owncloud_zimlet_onlyoffice_api_url
It is OK to use both OnlyOffice and LibreOffice at the same time for document preview.
n

Do you want to automatically install Zimlet and force enable it in all COS'es?
If you choose n you have to run zmzimletctl, configuration COS and set config_template.xml manually.
If you have trouble or are unsure, choose Y. Y/n:
n

Do you want to install public link sharing?
If you use a WebDAV server that is not ownCloud or Nextcloud choose n.
If you have trouble or are unsure, choose Y. Y/n:
y
Check if git and ant are installed.
Remove old versions of Zimlet.
Not touching COS per user request.
Saving existing configuration to /tmp/webdav-client-installer.5RnKwX6T/upgrade
Download WebDAV Client to /tmp/webdav-client-installer.5RnKwX6T
Cloning into 'owncloud-zimlet'...
remote: Counting objects: 429, done.
remote: Compressing objects: 100% (322/322), done.
Receiving objects:  10% (43/429), 6.75 MiB | 220.00 KiB/s

**Comment by barrydegraaff** [comment]
Sorry, I do not have resources to support Ubuntu 12... it is just too old.
