### ISSUE TITLE
Automatically get full email address instead of name.surname

### ISSUE THREAD

**Issue by xjobex** [Zimbra-Community/owncloud-zimlet#119]
Our environment is a multi-domain one, and Nextcloud users are synchronized from Zimbra LDAP.  Since some users have more than one email address (one for each domain), they have to log in to zimbra using the full email address. The WebDAV zimlet keeps on automatically getting only name.surname, and the user has to edit preferences manually. Is it possible to set up the zimlet to get the full email address (name.surname@domain.com) that the user entered to log in to Zimbra?

**Comment by barrydegraaff** [comment]
yep, that is a good point, however if the user saves it once, it should be saved for future use.

You could use zmprov to provision the correct settings, however, I will leave this open, and make the behavior configurable in a future release. Thanks

**Comment by barrydegraaff** [comment]
@xjobex this feature has been added to the latest version, to enable, re-run the installer and set owncloud_zimlet_accountname_with_domain to true. See README.md.
