### ISSUE TITLE
Change share link type

### ISSUE THREAD

**Issue by xjobex** [Zimbra-Community/owncloud-zimlet#120]
When sharing a file from within the WebDAV zimlet, an email is automatically generated containing a link like:
zimbradav://nextcloud/remote.php/webdav/FileName.ods , that redirects to the WebDAV tab in Zimbra web client. Is it possible to change this link to point directly to Nextcloud, like "public link" does (i.e. obtaining a link like https://nextcloud.site.com/nextcloud/index.php/s/ATfAuVOJxnSfy8 , but private?)

**Comment by barrydegraaff** [comment]
Probably, but I don't think I will add such a feature soon. Perhaps if you'd consider a donation, I would move it up the to-do list.
