### ISSUE TITLE
Exception thrown: java.lang.IllegalStateException in email body if "Can share" is not checked

### ISSUE THREAD

**Issue by xjobex** [Zimbra-Community/owncloud-zimlet#121]
Steps to reproduce:
User A shares file "Document.odt" to User B in Nextcloud, de-checking "Can share" box
User B from Zimbra creates an email and shares the public link of "Document.odt" via owncloud zimlet

Expected result:
User B receives an error popup/message

Actual result:
The user does not receive any message, and the following line is inserted in the email: 
Document.odt  : Exception thrown: java.lang.IllegalStateException: No match found

**Comment by barrydegraaff** [comment]
I can confirm this issue, there used to be a problem with the progress dialog, in that it could not be dismissed in case of an error. To avoid having the user to have reload the window, we implemented it as you describe.

On the to-do list.

**Comment by barrydegraaff** [comment]
Best would be to implement the fix in the back-end, but what complicates things, is that there are a lot of potential error situations to handle.

For example this one:
Password is within the 1,000,000 most common passwords. Please choose another one.

And as xjobex found, not having permission to create shares. On top of that is that OCS does a create share request for each selected item (multiselect). As a result some links may be created and others not. 

I think its best not to create a new email message (OwnCloudListView) in case some of the results do not match http:// or https:// and show an error dialog with the details. In case of attach dialog ( OwnCloudTabView) show an error dialog and not add the links to the mail body.

https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/OwnCloudListView.js#L418

https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/OwnCloudTabView.js#L325

**Comment by barrydegraaff** [comment]
@xjobex Thank you, this is fixed in the 0.7.9 release, you need to re-run the installer (do not only update the zimlet). For the changes to be applied.

**Comment by xjobex** [comment]
Hello Barry, I confirm that this bug is now fixed.
Thank you
