### ISSUE TITLE
Share link inserted under signature if email is composed in plain text

### ISSUE THREAD

**Issue by xjobex** [Zimbra-Community/owncloud-zimlet#122]
Steps to reproduce:
User A has set Zimbra options to compose emails in plain text, and has a default signature in plain text
User A shares a file with owncloud-zimlet via public link

Expected result:
The link is automatically written in the email body, above the signature

Actual result:
The link is automatically written under the signature

[Zimbra version: 8.6_Patch7]

**Comment by barrydegraaff** [comment]
I confirm this issue.

Problem is probably here:
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/OwnCloudTabView.js#L201

**Comment by barrydegraaff** [comment]
And here:
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/OwnCloudTabView.js#L336

I think maybe this code is outdated, maybe find a bult in method to determine where the signature is, and dump the composeview to find a better solution.

**Comment by barrydegraaff** [comment]
The code tries to find the divider between replied/forwarded messages. but does not seem to take into account the signature.

Anyway, 10 lines of code that do this: 
appCtxt.getCurrentView()._getDivider()

Then to find the signature do something like:
 appCtxt.getCurrentView().getSignatureContent();

to-do rewrite and test

**Comment by barrydegraaff** [comment]
@xjobex Hello Ego, I fixed this issue in the latest release, can you please test it, and confirm the patch works. Thanks Barry

**Comment by xjobex** [comment]
Hello barry, I tested today the updated zimlet and I can confirm that the patch worked.
Thank you for the update.
