### ISSUE TITLE
Size of uploaded files 0 Bytes

### ISSUE THREAD

**Issue by vdeyak** [Zimbra-Community/owncloud-zimlet#124]
When try to upload a file to the nextcloud it is created, but its size is 0 Bytes.
Nextcloud Version 11.0.2 (stable)
Zimbra 8.7.4_GA_1730 (build 20170227060845)

![_004](https://cloud.githubusercontent.com/assets/26440537/23960927/023a5dda-09b2-11e7-96ed-8af5b1a408af.png)
![_003](https://cloud.githubusercontent.com/assets/26440537/23960930/023eb2c2-09b2-11e7-8e18-c5f0f16d5555.png)
![_001](https://cloud.githubusercontent.com/assets/26440537/23960928/023b4ab0-09b2-11e7-9b1b-94ecb1681c95.png)
![_002](https://cloud.githubusercontent.com/assets/26440537/23960929/023c26c4-09b2-11e7-926d-4ad61083cd4f.png)

**Comment by vdeyak** [comment]
UPD:
1. I can delete and rename all files in the storage by owncloud-zimlet. 
2. When upload files by other davs-client to the same storage - ollways have correct file size.
Thanks!

**Comment by barrydegraaff** [comment]
Hi,

Can you hit F12 in Google Chrome and then click Console, then do another upload
and see if there is any error.

I have the same versions of Nextcloud/Zimbra here and it seems to work OK.

Barry

**Comment by vdeyak** [comment]
Hi, Barry. Thanks for quick replay!
Here is console ouput:
![_006](https://cloud.githubusercontent.com/assets/26440537/23968343/03f0d0c8-09cb-11e7-857b-cc2ddbc4de9f.png)

**Comment by barrydegraaff** [comment]
@vdeyak hi,

I will need more details on how to reproduce this issue. As so far I have not been able to reproduce.

If you want me to debug it for you, maybe you can consider getting a support subscription
https://www.powercraft.nl/zetalliance/
