### ISSUE TITLE
Installation issure for 8.7.5

### ISSUE THREAD

**Issue by Fakamaka333** [Zimbra-Community/owncloud-zimlet#125]
Installing server extension to /opt/zimbra/lib/ext/ownCloud
Downloading the correct ZAL Version (1.11.7 for zimbra 8.7.5)...
--2017-03-17 19:54:13--  https://openzal.org/1.11/zal-1.11.7-8.7.5.jar
Resolving openzal.org (openzal.org)... 52.85.142.223, 52.85.142.150, 52.85.142.187, ...
Connecting to openzal.org (openzal.org)|52.85.142.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-17 19:54:13 ERROR 404: Not Found.

**Comment by barrydegraaff** [comment]
Thanks for reporting!

I now configured OpenZAL for 8.7.5 you can proceed by re-running the installer.

Barry

**Comment by Fakamaka333** [comment]
Thank you for good work. Now everything goes fine.
