### ISSUE TITLE
any webdav?

### ISSUE THREAD

**Issue by gerickt** [Zimbra-Community/owncloud-zimlet#126]
works with seafile or alfresco?

**Comment by tuanta** [comment]
Yes. It supports WebDAV protocol.

**Comment by gerickt** [comment]
thanks!, I will do the tests

**Comment by barrydegraaff** [comment]
Also, alfresco is a supported platform.

**Comment by barrydegraaff** [comment]
Alfresco 5.1.1 is the latest we tested, if you have a different version, let us know your findings.
