### ISSUE TITLE
Default folder needs a trailing slash

### ISSUE THREAD

**Issue by sempiterna** [Zimbra-Community/owncloud-zimlet#129]
I've just updated zimbra to 8.7.6 and also updated the WebDAV zimlet. I noticed that when you drag an e-mail to the WebDAV, and you have set a Default Folder, the e-mail is stored in the root folder with the name you select as default folder attached as a prefix.

For example, the default folder is "Zimbra" and the e-mail subject is "Hi this is a subject", and you drag that mail to WebDAV, it is stored in / with filename:

"ZimbraHi this is a subject.eml"

Adding a trailing slash to the default folder solves it, but I don't think you intended it to be that way.

**Comment by barrydegraaff** [comment]
I check it here, and it works without adding any slash to the default folder.

That probably means you forgot to add the slash in one of the other settings, they need to be exactly as described in the https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/README.md

**Comment by sempiterna** [comment]
I don't see any problem in either my config file or the settings in the zimbra gui. I also just tried to do the same using a nextcloud installation instead of owncloud, with the same result. I don't think it is a config file issue, since none of the settings (seem to) handle forward slashes between upload folders. 

Maybe it is possible to build in a check, which checks if the default folder contains a slash, and if not, add one prior to uploading. Also, the issue was not present prior to upgrading my zimbra from 8.7.0 to 8.7.6, and updating the webdav client.

Screenshots of my cli and webgui:
![zimbracli](https://cloud.githubusercontent.com/assets/657431/25010037/0db3b940-2069-11e7-9d6f-5bb2dc5f8b96.png)
![zimbragui](https://cloud.githubusercontent.com/assets/657431/25010036/0db1cf36-2069-11e7-9660-635beb381eb6.png)

**Comment by barrydegraaff** [comment]
OK, I'll take a look later.

**Comment by barrydegraaff** [comment]
issue confirmed

**Comment by barrydegraaff** [comment]
Fixed in latest release.

**Comment by sempiterna** [comment]
Solution confirmed. Thank you :)
