### ISSUE TITLE
Can't see zimlet in COS and can't disable It via preference tab in zimbra web client

### ISSUE THREAD

**Issue by nikonaum** [Zimbra-Community/owncloud-zimlet#130]
I'm using this zimlet on CentOS 6 and Zimbra 8.7.7 and did the auto installation as in the readme file, the zimlet works fine but I can't disable it as an administrator nor as a common user via preferences menu. I've noticed that the installer put the unzipped directory to the following place "/opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_owncloud_zimlet" and when I copy it to the upper dir I can see it with the command "zmzimletctl listZimlets" as Installed Zimlet files on this host: "Installed Zimlet files on this host:" but not in "Installed Zimlets in LDAP:" nor "Available Zimlets in COS: default:"

**Comment by barrydegraaff** [comment]
https://github.com/Zimbra-Community/owncloud-zimlet/issues/98#issuecomment-261224181

Basically you should have chosen N when asked `Do you want to automatically install Zimlet and force enable it in all COS'es?` in the installer.

If you want to manually enable/disable, you need to remove the zimlet and re-run the installer.
https://github.com/Zimbra-Community/owncloud-zimlet#un-installing

And follow the steps to deploy the zip file, as shown at the end of the install process by the installer.

**Comment by nikonaum** [comment]
@barrydegraaff confirmed sollution, thank you.
