### ISSUE TITLE
Error when preference "Always compose in new window" is enabled 

### ISSUE THREAD

**Issue by nikonaum** [Zimbra-Community/owncloud-zimlet#131]
When enabled in preference --> mail --> Composing messages: "Always compose in new window" is checked when I compose a new massage a new window is oppened and I get the following error: "An error occurred while initializing the zimlet "tk_barrydegraaff_owncloud_zimlet". Please notify administrator."

**Comment by barrydegraaff** [comment]
Sorry about that, fixed in latest version, please re-run the installer or re-install zimlet manually to fix.
