### ISSUE TITLE
Bad russian localization

### ISSUE THREAD

**Issue by ekorneechev** [Zimbra-Community/owncloud-zimlet#132]
Hi!
Tell me, where can I fix russian language?
For example - "Public link to file/folder" => "Открытый связать с файл/папка"... but even [GoogleTranslate](https://translate.google.ru/#en/ru/Public%20link%20to%20file%2Ffolder) gives the best result...

**Comment by barrydegraaff** [comment]
its here: https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/OwnCloudTabView.js#L54

**Comment by ekorneechev** [comment]
Thanks!
