### ISSUE TITLE
Can't find variable davlib

### ISSUE THREAD

**Issue by alexweirig** [Zimbra-Community/owncloud-zimlet#133]
Hello,

after installing the latest version of the zimlet into our zimbra server whenever we connect to the webmail we get an error message saying: 
Can't find variable: davlib

Alex

**Comment by barrydegraaff** [comment]
Did you use the installer?

https://github.com/Zimbra-Community/owncloud-zimlet#installing

**Comment by alexweirig** [comment]
Yes of course I did ...

I used the installer, then I changed the config.

Afterwards I did the prop2xml stuff I restarted the zmmailboxdctl.

When I logged in to the webmail the error message occured.
