### ISSUE TITLE
File pane and preview pane don't resize when the browser resizes

### ISSUE THREAD

**Issue by justinhearn** [Zimbra-Community/owncloud-zimlet#134]
Thanks for a great product!

The first time the webdav zimlet tab opens it sizes nicely to the dimensions of the browser. However, if I maximize or resize the browser, the file pane and preview pane don't resize. Would it take much to implement automatic resizing? Thanks.

**Comment by justinhearn** [comment]
If I click on a file in the file pane after resizing the browser it resizes correctly.

**Comment by barrydegraaff** [comment]
In one of the earlier versions, we had a timer running to resize if needed, but there where some issues with it resizing all the time.

Anyway, clicking anywhere in the UI will do the resize, maybe at some point we hook into one of the timers in Zimbra, but for now this change is not scheduled.
