### ISSUE TITLE
Install script deletes TMPFOLDER before manual install can run

### ISSUE THREAD

**Issue by mnichols62** [Zimbra-Community/owncloud-zimlet#136]
If I choose to do a manual installation of the zimlet, the tmp folder is deleted by the bash install script, so there is nothing to go install.

**Comment by barrydegraaff** [comment]
It works here, maybe you did nog type N or n....

Do you want to automatically install Zimlet and force enable it in all COS'es?
If you choose n you have to run zmzimletctl, configuration COS and set config_template.xml manually.
If you have trouble or are unsure, choose Y. Y/n:
n

Then at the end of the installer I could 
To install Zimlet run as user Zimbra:
zmzimletctl deploy /tmp/webdav-client-installer.WDklxzxo/owncloud-zimlet/zimlet/tk_barrydegraaff_owncloud_zimlet.zip


I do not see where this could go wrong in the installer, did you download the latest version of the installer?
https://github.com/Zimbra-Community/owncloud-zimlet#installing

I re-checked but I do not see why this would not work.
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/webdav-client-installer.sh#L256
