### ISSUE TITLE
Automatically download attachments to the cloud

### ISSUE THREAD

**Issue by shlange** [Zimbra-Community/owncloud-zimlet#138]
Awesome zimlet! It really helps to work. A lot of people want to have automatic download of attachments from emails of zimbra to the cloud when an attachment exceeds the limit for zimbra. Will this functionality be implemented in the future?

**Comment by barrydegraaff** [comment]
That feature should already be implemented, try and upload a file that is too large aka over 
the zimbra attachment limit.

The zimlet should than ask to upload to nextcloud, and attach as link.

Provided:
owncloud_zimlet_disable_auto_upload_on_exceed is set to false.

Maybe there is a bug though.

**Comment by barrydegraaff** [comment]
verified, seems to just work.
