### ISSUE TITLE
WebDAV file

### ISSUE THREAD

**Issue by missuresh** [Zimbra-Community/owncloud-zimlet#139]
I have integrate Webdav with Alfresco 5.0.d (CE) and Zimbra 8.7.11 (ZCS).

It is working. But, I am not able to see the file size & modified Date-time.

If any settings need to be modify?

![image](https://user-images.githubusercontent.com/21118678/29395788-18d9553e-8331-11e7-9d72-2cd5d6db260d.png)

**Comment by barrydegraaff** [comment]
Hello missuresh,

This is correct, size/modified is not implemented for Alfresco.

I remember looking into it, and I believe the problem is Alfresco does not return those properties in the DAV response.
