### ISSUE TITLE
Zero filesize when upload from zimbra

### ISSUE THREAD

**Issue by deadmo** [Zimbra-Community/owncloud-zimlet#140]
Hello.
OC 9.1
ZCS 8.6.0
Config.properties:

```
owncloud_zimlet_disable_rename_delete_new_folder=false
owncloud_zimlet_disable_ocs_public_link_shares=false
owncloud_zimlet_default_folder=/
owncloud_zimlet_extra_toolbar_button_url=https\://cloud.mydomain.ua
owncloud_zimlet_server_port=443
owncloud_zimlet_oc_folder=/owncloud
owncloud_zimlet_server_path=/remote.php/webdav/
owncloud_zimlet_preview_delay=200
owncloud_zimlet_max_upload_size=104857600
owncloud_zimlet_extra_toolbar_button_title=CloudAgrosem
owncloud_zimlet_welcome_url=https\://barrydegraaff.github.io/owncloud/
owncloud_zimlet_ask_folder_each_time=false
owncloud_zimlet_app_title=CloudAgrosem
owncloud_zimlet_accountname_with_domain=false
owncloud_zimlet_server_name=https\://cloud.mydomain.ua
allowdomains=*
owncloud_zimlet_disable_auto_upload_on_exceed=false
file_number=1000002
disable_password_storing=false
owncloud_zimlet_use_numbers=false
```

I have an issue with zimlet:
When I try to upload file to owncloud from zimbra it creates 0-size file.
nginx log (OC server):
 [11/Sep/2017:12:34:49 +0300] "PUT /remote.php/webdav//123123123123.xlsx HTTP/1.1" 201 25 "-" "Sardine/UNAVAILABLE"
owncloud log (OC server): 
Exception: {"Message":"HTTP\/1.1 400 Empty filename is not allowed"...

When I try to attache file from OC to the letter - work fine

When upload directly from OC web-page, its work fine

**Comment by barrydegraaff** [comment]
Seems like you have put too many // slashes 

/remote.php/webdav // 123123123123.xlsx 

You have to put the exactly as in the README.md 


Kind regards, 

Barry de Graaff 
Zeta Alliance Founder 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 
Skype: barrydegraaff.tk 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by deadmo** [comment]
"PUT /remote.php/webdav/owncloud/1495619710149245910.jpg HTTP/1.1" 201 25 "-" "Sardine/UNAVAILABLE"


Same result.

**Comment by barrydegraaff** [comment]
do you use a reverse proxy (zimbra proxy) to go to owncloud? 

Kind regards, 

Barry de Graaff 
Zeta Alliance Founder 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 
Skype: barrydegraaff.tk 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by deadmo** [comment]
I use proxy for my zimbra web-interface.

**Comment by barrydegraaff** [comment]
I don't know, it seems you are using nginx on your oc server, that is known to cause issues, try without proxies.
