### ISSUE TITLE
Base DN appears to be wrong

### ISSUE THREAD

**Issue by NQuebec** [Zimbra-Community/owncloud-zimlet#143]
Hello,  Thank you for the wiki pages describing how to connect ownCloud to Zimbra LDAP.  This is actually the only one I found on the net about this!

Unfortunately it doesn't work for me, I get "Base DN appears to be wrong" error message when I click the "Test DN" button on the Server tab from ldap config.  I filled the base DN field with:
ou=people,dc=chene,dc=innovationsolutions,dc=ca

I am using Nextcloud 12.0.3 and Zimbra 8.7.11.

Thank you.

**Comment by barrydegraaff** [comment]
In nextcloud the ldap wizard is very buggy.

You need to go through all tabs of the wizard from top to bottom and save.

If it does not work, remove the ldap config from nextcloud and try again from scratch.

Barry
