### ISSUE TITLE
File Attachment Fails

### ISSUE THREAD

**Issue by arkitoure** [Zimbra-Community/owncloud-zimlet#144]
Hello,

Stumbled on a strange bug when attaching files through the WebDav tab interface.

An unknown error (mail.NO_SUCH_UPLOAD) has occurred.

Some detail below (message data cut out):

method: | [unknown]
-- | --
msg: | upload not found: ff7fc806-5b7c-4157-afe6-3c85587d3b1f:2759ac0e-476f-4e52-8373-c414c2b25254[object Object]
code: | mail.NO_SUCH_UPLOAD
detail: | soap:Sender

userAgent: {
      name: "ZimbraWebClient - FF57 (Win)",
      version: "8.7.1_GA_1670"

Making attachments via the Compose Mail>Attach>WebDav works fine however.

Ive combed logs to see if anything will reveal the issue with no luck...any clues to this?

Thank you!

**Comment by barrydegraaff** [comment]
Can you try again, but press F12 in the browser and go to the Console tab in the developer tools.

And see what the error is. 

It works from here, but we are using 8.7.11.

**Comment by arkitoure** [comment]
Checked the console...getting some depreciation warnings and XML parsing errors. Perhaps upgrade to 8.7.11 is overdue. The 401 errors are strange, auth/access works in reverse....


```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/
domain:1642
------------------------------------- Loading package: MailCore
domain:2261:1
------------------------------------- Loading package: ContactsCore
domain:2261:1
------------------------------------- Loading package: Startup2

XML Parsing Error: syntax error
Location: https://domain/service/extension/dav_download/
Line Number 1, Column 1:
dav_download:1:1
unreachable code after return statement
[Learn More]
%20line%201767%20%3E%20eval:6025
Source map error: request failed with status 401
Resource URL: https://domain/service/zimlet/_dev/tk_barrydegraaff_owncloud_zimlet/markdown/purify.js?v=161025050454&language=en&country=GB&debug=1
Source Map URL: purify.js.map
[Learn More]
Source map error: request failed with status 401
Resource URL: https://domain/service/zimlet/_dev/tk_barrydegraaff_owncloud_zimlet//ViewerJS/video-js/video.js
Source Map URL: video.js.map
[Learn More]
XML Parsing Error: syntax error
Location: https://domain/service/extension/dav_download/
Line Number 1, Column 1:
```

**Comment by barrydegraaff** [comment]
Looks like an installation problem, you should remove using:
https://github.com/Zimbra-Community/owncloud-zimlet#un-installing

Then re-install and keep hitting enter in the installer, so all the defaults are used:
https://github.com/Zimbra-Community/owncloud-zimlet#installing

Also, upgrading to 8.7.11 is a good idea, as 8.7.1 kinda sucks.

**Comment by arkitoure** [comment]
Funny enough upgrade is scheduled for this weekend. I'll get through that and re-install and report back if anything is persisting.

Thank you!

**Comment by barrydegraaff** [comment]
Any news?

**Comment by arkitoure** [comment]
Hallo Barry,

Yes, been a long week so far. Upgrade plans changed to doing a fully expanded multi-server environment...including, new to me, WebUI/Mailbox split.

I'll report on that scenario when wrapped up, question though... In the WebUI/Mailbox split situation does the owncloud-zimlet get installed on the mailbox, webui or both? 

Cheers for your time..

**Comment by barrydegraaff** [comment]
I would guess both, but that is guessing.

**Comment by arkitoure** [comment]
Well I guess I'll find out over the weekend and let you know the results. Maybe add resulting info to the Wiki if its helpful. Transfer is due by Monday morning....I loathe mail migrations. :\ Cheers!

**Comment by arkitoure** [comment]
The migration is done and the re-install of the zimlet worked solely on the mailbox, automatically setting up on the webui server without any added effort.

With this install there is an error regarding the proxy domain. Would this mean the zimbra nginx proxy needs modification? 

`

method: | [unknown]
-- | --
msg: | system failure: java.lang.RuntimeException: Proxy domain not allowed 'https://cloud.domain.com' for user 'user@mail.com'
code: | service.FAILURE
detail: | soap:Receiver
trace: | qtp127618319-2376:1512008234523:4ac17d264a9162c4
request: | <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><context xmlns="urn:zimbra"><userAgent xmlns="" name="ZimbraWebClient - FF58 (Mac)" version="8.7.11_GA_1854"/><session xmlns="" id="1127"/><account xmlns="" by="name">user@mail.com</account><format xmlns="" type="js"/><csrfToken xmlns="">0_95212c12d229e3d7f6cbdeb3136daf6018199bfc</csrfToken></context></soap:Header><soap:Body><davSoapConnector xmlns="urn:zimbraAccount"><path xmlns="">//</path><owncloud_zimlet_password xmlns="">passwordstring</owncloud_zimlet_password><owncloud_zimlet_username xmlns="">user</owncloud_zimlet_username><owncloud_zimlet_server_name xmlns="">https://cloud.domain.com</owncloud_zimlet_server_name><owncloud_zimlet_server_port xmlns="">443</owncloud_zimlet_server_port><owncloud_zimlet_server_path xmlns="">/remote.php/webdav</owncloud_zimlet_server_path><owncloud_zimlet_oc_folder xmlns=""></owncloud_zimlet_oc_folder><action xmlns="">MKCOL</action></davSoapConnector></soap:Body></soap:Envelope>

`

**Comment by barrydegraaff** [comment]
Hello,

The installer does not remove settings previously stored settings, rather
it migrate any existing settings to the new installation.

Maybe at one point you have configured `allowdomains` in /opt/zimbra/lib/ext/ownCloud/config.properties
https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences

If you want, you can remove that file, and re-run the installer and try again, OR set the
property to * to allow all domains.



Kind regards, 

Barry de Graaff
Zeta Alliance 
Co-founder & Developer
zetalliance.org | github.com/Zimbra-Community

+31 617 220 227 | skype: barrydegraaff.tk
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by arkitoure** [comment]
Hola Barry...

Made a mistake on the 'allowdomains' entry, where there was a letter out of place. Corrected it and now its working. This was a totally new install/upgrade so nothing carried over to the new system just the mail data. So far so good and the original error has not resurfaced. If it does pop up again I will post back here.

Thank you for your help and effort on this zimlet. In fact, Im interested in contributing - also for some UI/UX (my primary focus) if you are open to that?

Cheers!

**Comment by barrydegraaff** [comment]
Hello Alston,

Good to hear, if that it works,  you can make donations via:

PayPal: info@barrydegraaff.tk
Bank transfer: IBAN NL55ABNA0623226413 ; BIC ABNANL2A

I'm happy to do some UI work, as long as it's Zimbra related.
You can ping me at above email address.

Thanks!

Kind regards, 

Barry de Graaff
Zeta Alliance 
Co-founder & Developer
zetalliance.org | github.com/Zimbra-Community

+31 617 220 227 | skype: barrydegraaff.tk
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by barrydegraaff** [comment]
Hello Alston,

Please double check your settings, mind the slashes / they should be
exactly like in https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences
