### ISSUE TITLE
0 Bytes filesize when upload from zimbra

### ISSUE THREAD

**Issue by skuti-is** [Zimbra-Community/owncloud-zimlet#146]
Same as #124 and #140 
Using Zimbra 8.7.11 on Ubuntu 16.04
ownCloud 10.0.3-1.1 on separate server
owncloud-zimlet installed using webdav-client-installer.sh
Using ownCloud directly works without issues.

access.log:
[01/Dec/2017:12:33:59 +0000] "PUT /remote.php/webdav/asdf/Example.odt HTTP/1.1" 201 25 "-" "Sardine/UNAVAILABLE"
[01/Dec/2017:12:33:59 +0000] "PROPFIND /remote.php/webdav/asdf/ HTTP/1.1" 207 944 "-" "Sardine/UNAVAILABLE"

Cant find any errors in browser or log files.

**Comment by barrydegraaff** [comment]
Hello, 

Please double check your settings, mind the slashes / they should be
exactly like in https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences

**Comment by barrydegraaff** [comment]
It confirm the issue, perhaps a regression, I'll check later

**Comment by skuti-is** [comment]
Double checked slashes, no results.

**Comment by barrydegraaff** [comment]
Yeah, I am seeing some mixed results here, I have one set-up of ownCloud Zimlet Version: 0.8.7 and Nextcloud 12.0.3 that works.

When upgrading to the latest nextcloud and owncloud zimlet it no longer works, the upload code has not been touched for 10 months, so thats interesting :-p

**Comment by barrydegraaff** [comment]
ownCloud Zimlet Version: 0.8.7 and Nextcloud 12.0.3 that works.
ownCloud Zimlet Version: 0.9.5 and Nextcloud 12.0.4 that works.
ownCloud Zimlet Version: 0.9.5 and Nextcloud 12.0.3 does not work.

I have a feeling it is maybe a nextcloud/owncloud issue, or some server setting that is in the way. I will do some more digging.

**Comment by barrydegraaff** [comment]
I looked into issues reported in Nextcloud, and it seems there are some protocol incompatibilities in regards to the WebDAV PUT. In any way the sardine does not work Apache HttpPut does not work either, so I coded a low level java solution,

Can you unzip the attachment and place the 2 jars in 
/opt/zimbra/lib/ext/ownCloud/

Then zmmailboxdctl restart  then the upload button in the WebDAV Tab should work, the link behind mails are broken now, but I need to fix that in the Zimlet.

[commons-io-2.6.jar.zip](https://github.com/Zimbra-Community/owncloud-zimlet/files/1539100/commons-io-2.6.jar.zip)

**Comment by barrydegraaff** [comment]
This is the patched java, ignore this zip file you do not need it
[UploadHandler.java.patch.zip](https://github.com/Zimbra-Community/owncloud-zimlet/files/1539116/UploadHandler.java.patch.zip)

**Comment by barrydegraaff** [comment]
If you re-download and re-run the installer, your problem should go away.

**Comment by skuti-is** [comment]
Thanks, this works

**Comment by barrydegraaff** [comment]
Thanks for reporting!

If you can, support me and make donations via:

PayPal: info@barrydegraaff.tk
Bank transfer: IBAN NL55ABNA0623226413 ; BIC ABNANL2A

Thanks for your consideration!
