### ISSUE TITLE
Send link not work

### ISSUE THREAD

**Issue by longlnk** [Zimbra-Community/owncloud-zimlet#148]
Hi,
I have a fresh install of zimbra 8..8 and owncloud 8.1 on two different machines, Zimbra server running Centos 7 and Owncloud running ubuntu 14.04. I have successfully set the owncloud-zimlet up and all works except send link.
Upon trying to create internal users and groups I get "zimbradav://remote.php/webdav/update_8_12/"
Upon trying to create a send link public I get "java.lang.lllegalStateException: no match found"

Can you help me? :(

**Comment by barrydegraaff** [comment]
Hello,

Probably owncloud 8 is too old, the lowest version ever supported is oc9.

Can you try a newer version?

**Comment by longlnk** [comment]
Hi Mr. Barrydegraaff 

I've tried owncloud  version 9 and 10, I've installed same machine, but the error still appears.
![image](https://user-images.githubusercontent.com/15074179/34416135-b0a6ef8c-ec24-11e7-9e75-38185667bc4b.png)

**Comment by longlnk** [comment]
Update,

I see folder/file that is shared on OwnCloud, but still error on Zimbra

![image](https://user-images.githubusercontent.com/15074179/34417042-ffb942a6-ec28-11e7-9f97-d093c49c9bde.png)

![image](https://user-images.githubusercontent.com/15074179/34417084-2a2a3d88-ec29-11e7-9f0a-63692f41fb45.png)

I'm using https://IPaddress/ on Owncloud and Zimbra

**Comment by barrydegraaff** [comment]
Probably you need a good dns and ssl certificate for it to work.

I did not test using IPs

**Comment by longlnk** [comment]
I'm using https://domain.com and let'encrypt, but it still error
"java.lang.lllegalStateException: no match found"

This is my configuration

![image](https://user-images.githubusercontent.com/15074179/34434402-89556e4c-ecb8-11e7-8824-c020685b7ec0.png)

![image](https://user-images.githubusercontent.com/15074179/34434428-a8249f3c-ecb8-11e7-849f-0efdc2c4e53f.png)

![image](https://user-images.githubusercontent.com/15074179/34434441-c10e45de-ecb8-11e7-8321-b7da55de9e34.png)

![image](https://user-images.githubusercontent.com/15074179/34434449-cbfdaa20-ecb8-11e7-8d67-41b41f07eeec.png)

Please help me :(

**Comment by barrydegraaff** [comment]
Well I can debug, perhaps you can give me a test account on you owncloud server, so I can check.

**Comment by longlnk** [comment]
Hi,

I send email zimbra and account owncloud, Alert me if you need more information.

https://mail.geekysm.com admin/123456aA@
https://mail.geekysm.com:444/owncloud admin/admin
https://mail.geekysm.com:444/owncloud/index.php/apps/files/

File config owncloud
![image](https://user-images.githubusercontent.com/15074179/34441614-7797bb7e-ecef-11e7-9e9c-53856633454e.png)

[owncloud .log](https://github.com/Zimbra-Community/owncloud-zimlet/files/1593475/owncloud.log)

**Comment by barrydegraaff** [comment]
I removed the comment with the username and password, as this is public.

**Comment by barrydegraaff** [comment]
This problem is not in your Zimbra set-up, so it is most likely a bug in our code, I will look now

**Comment by barrydegraaff** [comment]
I do not have the time to debug it today, but I expect to fix it within 2 weeks, please do not disable the test account.

**Comment by longlnk** [comment]
Yes, You can go whenever you want 👍

**Comment by barrydegraaff** [comment]
The problem is in this piece of code:

                        if (!isError) {
                            pattern = Pattern.compile("<message>(.+?)</message>");
                            matcher = pattern.matcher(responseTxt.toString());
                            matcher.find();
                            if (!"OK".equals(matcher.group(1))) {
                                errorMessage += matcher.group(1) + ". ";
                            }

Nextcloud always returns a status message < message > something here < / message > but owncloud does not, and returns < message / >. I guess maybe owncloud does not implement that part.

As a result the regex fails, and an error is returned to the user.

One moment while I think about the fix.

**Comment by barrydegraaff** [comment]
Hello,

This issue is fixed, you need to re-run the installer to have the fix applied.

You also need to set in your owncloud configuration:
'overwritehost' => 'yourdomain.com:port',
(maybe different as I use nextcloud mostly)

Please consider a donations via:

PayPal: info@barrydegraaff.tk
Bank transfer: IBAN NL55ABNA0623226413 ; BIC ABNANL2A

**Comment by barrydegraaff** [comment]
As alternative to donations, I also appreciate free subscriptions to paid services you may provide. Thanks

**Comment by longlnk** [comment]
I will try and report back to you, I'm on the outside. :)

**Comment by longlnk** [comment]
Hi, 
I tried, but it don't show name of file and folder

![image](https://user-images.githubusercontent.com/15074179/34454684-f9416342-eda2-11e7-8ffd-124a11978324.png)

Share link internal user and group, it is inconnect

![image](https://user-images.githubusercontent.com/15074179/34454694-2adccab8-eda3-11e7-9fcf-628ed445945f.png)

**Comment by barrydegraaff** [comment]
works from here... also works after following internal user link.
![geekysm](https://user-images.githubusercontent.com/4353213/34454774-bd2eaa16-ed72-11e7-8d7d-21bd1c2f639a.png)

**Comment by barrydegraaff** [comment]
Did you restart mailbox after running the installer?

**Comment by longlnk** [comment]
Hi,

I restarted mailbox server, it has name file and folder, but Internal link that don't use. And File name changed when I use Upload File, Save Email To WebDav and Save File To WebDav in Email 

![image](https://user-images.githubusercontent.com/15074179/34455104-5ea8386c-edaa-11e7-8cbc-2554815e119f.png)

![image](https://user-images.githubusercontent.com/15074179/34455105-67605264-edaa-11e7-8049-439fb15054cb.png)

And File name changed when I use Upload File, Save Email To WebDav and Save File To WebDav in Email 

![image](https://user-images.githubusercontent.com/15074179/34455109-a8cd62dc-edaa-11e7-9296-9b9f51afbfab.png)

![image](https://user-images.githubusercontent.com/15074179/34455127-de2d5e64-edaa-11e7-9700-37be423f4c1b.png)

**Comment by barrydegraaff** [comment]
See my screenshot... unset the check for Use Prefix Number

**Comment by longlnk** [comment]
This is work, thank you very much, I will donations via your paypal on the day 2/1/2018 GMT +7

**Comment by barrydegraaff** [comment]
Hello,

Just a reminder, I did not see anything happen on PayPal yet.

Barry

**Comment by longlnk** [comment]
Hi,
Sorry, I've send, please check ;)
![image](https://user-images.githubusercontent.com/15074179/34521247-634c175e-f0bf-11e7-9168-0f0c08b84e59.png)

**Comment by barrydegraaff** [comment]
Thanks! It’s here
