### ISSUE TITLE
DAV error while saving mail to WebDav

### ISSUE THREAD

**Issue by rogerfv1** [Zimbra-Community/owncloud-zimlet#150]
Hello,

We have found a strange behavior while saving mails to webdav using the default folder preference.

### Steps to reproduce
1. Login into Zimbra
2. Open WebDav preferences (left click on Zimlet panel item)
3. Set "Default folder" and others.
4. Save WebDav preferences (click on OK)
5. Login into nextcloud and delete the created Default folder
6. Return to zimbra mail
7. Right click on mail and choose "Save to WebDav".

### Expected behaviour
Zimlet should create its default folder if it doesn't exist.

### Actual behaviour
Error message: DAV Error Unexpected response (404 Not Found)

**Comment by barrydegraaff** [comment]
Hello Roger,

This behavior is indeed as you describe. 

The folder is only created when saving preferences, or if the user creates it manually.

This has been done as the only other way would be to do it at initialization of Zimbra, and some customers that use automated provisioning or do not store password had problems with the automatic re-creation of the folder.

**Comment by rsilveira1987** [comment]
Greetings gentlemen,

I have been expiriencing a similiar "problem". Well, I don't consider it as a problem itself but I believe the Zimlet could get more resiliant.

As admin, I set the owncloud_zimlet_default_folder property inside the config_template.xml file and the user gets the same error above if he clicks directly on the zimlet tab and type his password. Usually, the user tries to access the zimlet's tab first, ignoring his preference's window.

I don't store my passwords in Zimbra LDAP either but, as I said, I noticed the Zimlet asks for the user password and stores it until the user session's end. Would it be possible to create the default folder at this moment?

**Comment by barrydegraaff** [comment]
@rsilveira1987 I just tried that, an it does not throw an error here, the default folder is not used in the WebDAV tab.

**Comment by barrydegraaff** [comment]
@rogerfv1 I have added the creation of the folder, can you re-install the Zimlet, flush all your cache and see if it works for you? Thx.

**Comment by rsilveira1987** [comment]
@barrydegraaff, access the WebDAV tab does not throw an error indeed. But after click the WebDAV tab, type the user password, and try to save an email using the 'save to WebDAV' function throws a DAV Error Unexpected response (404 Not Found) error if the default folder does not exist. It seems to me the original problem was the missing default folder.

I have just updated my WebDAV Zimlet with the new code and it worked like a charm. Great job. Now it is time to study the changed file.

**Comment by rogerfv1** [comment]
Hi @barrydegraaff,

It worked!
Sorry about the delay, I was on vacation.
Thanks,
Roger

**Comment by barrydegraaff** [comment]
For 3 weeks? In March, I am not talking to you anymore!

Just kidding, happy it works now.

**Comment by rogerfv1** [comment]
hahaha!! :-)
 I agree 3 weeks is a long vacation.
 Have a nice week!
 Thks,
