### ISSUE TITLE
Impossible to initialize zimlet

### ISSUE THREAD

**Issue by tigre-bleu** [Zimbra-Community/owncloud-zimlet#153]
When I activate the zimlet, I receive the following error while opening the webmail:

` TypeError: this.handlerObject._init is not a function `

Launching the webmail with ?dev=1 in the url does not give the error and the widget works correctly.

Any idea about this issue? I installed using the installer.

**Comment by barrydegraaff** [comment]
try flushing your cache:

zmprov fc all
zmmailboxdctl restart

and try again in an incognito tab

**Comment by tigre-bleu** [comment]
I already tried that but with no sucess. The only solution that works is the ?dev=1

**Comment by barrydegraaff** [comment]
I just flushed my dev server (clean install) and re-run the installer:

I typed 3x Y for the installer questions.

Can you go to google chrome, hit F12 and then Console tab and reload zimbra
Can you see what the error is? Also click on the source file on the right
if possible to track the file with the error (and find the code line) 

Also, I do not have a ._init call in my code, it still may be called by
the Zimlet framework.


Is this a new install or an upgrade?

**Comment by tigre-bleu** [comment]
It is a new install of the zimlet

Here is the details:
```
Zimlets-nodev_all.js.zgz?language=fr&cosId=b2507500-e05b-4322-a4c8-89313755f1ba:5654 Uncaught TypeError: this._getPresence is not a function
    at UnknownPersonSlide._setPresenceUI.l (Zimlets-nodev_all.js.zgz?language=fr&cosId=b2507500-e05b-4322-a4c8-89313755f1ba:5654)
    at Zimlets-nodev_all.js.zgz?language=fr&cosId=b2507500-e05b-4322-a4c8-89313755f1ba:5678
UnknownPersonSlide._setPresenceUI.l @ Zimlets-nodev_all.js.zgz?language=fr&cosId=b2507500-e05b-4322-a4c8-89313755f1ba:5654
(anonymous) @ Zimlets-nodev_all.js.zgz?language=fr&cosId=b2507500-e05b-4322-a4c8-89313755f1ba:5678
```

Hope this helps, I would like to avoid uninstalling/reconfiguring if possible but if there is no other choice I will try it.

Thanks

**Comment by barrydegraaff** [comment]
That is not a part of Nextcloud Zimlet, so if reinstalling zimbra is an option.... go for it

**Comment by tigre-bleu** [comment]
Ok, I was speaking of reinstalling Nextcloud Zimlet, not Zimbra :-)

Which version of zimbra do you test with? Mine is 8.8.6_GA_1906.FOSS

**Comment by barrydegraaff** [comment]
It is tested on 8.7.11 and 8.8.7. I will deploy to 8.6 on Saturday

**Comment by barrydegraaff** [comment]
I just deployed it to an 8.6 and it works as well.

I still feel you have a cache issue, try and create a new account, and log onto that
and see if it works.

Are you 100% sure you use a clean browser?

**Comment by barrydegraaff** [comment]
cannot re-produce

**Comment by KlugFR** [comment]
In my case, the error seems to be in the SpamExperts zimlet.
The error also exists without the webdav zimlet but nothing shows up (unless you look at the code).
```
Uncaught TypeError: Cannot read property 'type' of undefined
    at SpamExpertsZimlet._moveToTrashAction.l (Zimlets-nodev_all.js.zgz?language=fr&country=FR&cosId=9d0bf390-ae4b-4fd2-bc34-bd89ebcf4f32:2910)
    at Zimlets-nodev_all.js.zgz?language=fr&country=FR&cosId=9d0bf390-ae4b-4fd2-bc34-bd89ebcf4f32:2922
```
and
```
SpamExpertsZimlet.prototype._moveToTrashAction=function(n){
var e="MsgActionRequest";
if(n.type==ZmItem.CONV){
e="ConvActionRequest"
}
```

**Comment by KlugFR** [comment]
Seems fixed for me.
I don't know if it's the tuned SpamExperts zimlet I tried or that I removed/installed it (after the NextCloud one).

**Comment by KlugFR** [comment]
I even tried to delete /opt/zimbra/jetty/work content before I eventually undeployed/deployed com_zimbra_spamexperts.

**Comment by barrydegraaff** [comment]
Ooee that is exciting, well I know a lot of people who have a love/hate relation with Zimbra's caching.

In the end did both zimlets work at the same time?

**Comment by KlugFR** [comment]
Right now, on one of my setups, they seem to be.

I'm trying on another setup (another multi-servers setup).

**Comment by KlugFR** [comment]
Same issue (and fix) on the other setup.

Issue: adding Owncloud zimlet throws the error (flushing cache is not fixing)
Fix: undeploy then deploy spamexperts zimlet _after_ owncloud zimlet then flush cache.

**Comment by barrydegraaff** [comment]
its weird, but I do not have spamexperts zimlet, so I cannot see what the issue is.

**Comment by barrydegraaff** [comment]
sometimes it is also browser cache that is the issue,
in that case, incognito mode should help.

**Comment by KlugFR** [comment]
I tried incognito mode and a brand new browser that never connected to the ZCS server.
Same issue.
undeploy/deploy the zimlet and it works immediately.
Very strange...

**Comment by tigre-bleu** [comment]
I tried uninstalling the zimlet and reinstalling. Same issue. Unactivating all other widgets did not work either.

**Comment by tigre-bleu** [comment]
I tried uninstalling the zimlet and reinstalling. Same issue. Unactivating all other widgets did not work either.

**Comment by barrydegraaff** [comment]
Can you go to google chrome, hit F12 and then Console tab and reload zimbra
Can you see what the error is? Also click on the source file on the right
if possible to track the file with the error (and find the code line)

**Comment by barrydegraaff** [comment]
What zimlets are installed?

Can you run zimbra with /?dev=1 in the url and make a new screenshot

**Comment by barrydegraaff** [comment]
Can you pm me a test account at info@barrydegraaff.tk thanks!

**Comment by barrydegraaff** [comment]
The error this._getPresence is from another Zimlet (not one of mine) so I still think it is a cache issue. 
Did you try 
zmprov fc all 
zmcontrol restart 

Anyway, I want to investigate, in case there is an issue with 8.8 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 | skype: barrydegraaff.tk 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by tigre-bleu** [comment]
With ?dev=1 there is no error and the zimlet works correctly. Here is the console output in verbose mode:
![image](https://user-images.githubusercontent.com/1867719/38632841-331bea68-3dbe-11e8-9639-5e96c940c5b4.png)

The following zimlets are active on zimbra server:
![image](https://user-images.githubusercontent.com/1867719/38632900-617c8c14-3dbe-11e8-84c8-13142390ee61.png)
However, for the tests only the owncloud-zimlet was active for the user.
Note: The first one is just a simple embedded website in a tab.

I PM you with a test account.

**Comment by barrydegraaff** [comment]
I see that when I use 
[ https://zimbra.tigre-bleu.net/?dev=1#3 | https://zimbra.tigre-bleu.net/?dev=1#3 ] 

It works w/o issue. 

This means it is a cache issue, unless you made another customization to zgz files manually. 

The usual fix is: 
zmprov fc all 
zmcontrol restart 

If nothing else works, reboot the server... sometimes it takes a little while for Zimbra to rebuild 
all the caches. 

It is really annoying, but there is nothing much else to do. 

What happens is that a cached file from 
[ https://zimbra.tigre-bleu.net/service/zimlet/res/Zimlets-nodev_all.js.zgz?language=fr&cosId=b2507500-e05b-4322-a4c8-89313755f1ba | https://zimbra.tigre-bleu.net/service/zimlet/res/Zimlets-nodev_all.js.zgz?language=fr&cosId=b2507500-e05b-4322-a4c8-89313755f1ba ] 

Is calling methods that are no longer there. Meaning either the Zimlets-nodev is out of date, or the called methods are 
not cached (correctly) or no longer there. 

For kicks, you can also upgrade to Zimbra 8.8.8 and see what that does (I don't think it will hurt, but first upgrade WebDAV Client.) 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 | skype: barrydegraaff.tk 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by tigre-bleu** [comment]
Thanks for the investigation, I will reboot the server on the next zimbra upgrade and see if that goes well.
