### ISSUE TITLE
Getting error while search in owncloud

### ISSUE THREAD

**Issue by maheshassyst** [Zimbra-Community/owncloud-zimlet#154]
Team,

We are getting error while searching,Please find the attached the screenshot.

Regards,
Mahesh
![owncloud](https://user-images.githubusercontent.com/7468412/37830008-2bd911aa-2ec7-11e8-85af-cb94244e723e.png)

**Comment by barrydegraaff** [comment]
Yap, Search is not implemented on owncloud server. Its on Nextcloud 13.

**Comment by barrydegraaff** [comment]
This Zimlet uses WebDAV Search method, and that is not implemented yet by the owncloud team.

So there is nothing much I can do about it.
