### ISSUE TITLE
Upload to owncloud if the file exceed message size limit -> broken

### ISSUE THREAD

**Issue by im-evko** [Zimbra-Community/owncloud-zimlet#155]
If you add a file attachment that exceeds the allowed value. After downloading this file there is no error, but file does not appear in the repository and in the letter the inscription "the name of the file : Could not create share" OS Centos 7

**Comment by barrydegraaff** [comment]
Can you create a video, it works here.

**Comment by im-evko** [comment]
https://drive.google.com/file/d/1vPCrAo9P6tYkSROYvg8Jk3rrE2ixUs16/view?usp=sharing

**Comment by barrydegraaff** [comment]
I can confirm the issue, and will fix it soon

**Comment by barrydegraaff** [comment]
@im-evko the issue should be fixed now, re-run the installer to get the patch.

**Comment by barrydegraaff** [comment]
Can you confirm it works, thanks!!

**Comment by im-evko** [comment]
Yes, the problem is solved. Many thanks!!!
