### ISSUE TITLE
error:  while accessing https://github.com/barrydegraaff/owncloud-zimlet/info/refs

### ISSUE THREAD

**Issue by KlugFR** [Zimbra-Community/owncloud-zimlet#156]
Hello.

I'm trying to setup the zimlet on a ZCS 8.6 server, running on CentOS 6.x.

The installer stops with this error:
```
Check if git and ant are installed.
which: no apt-get in (/opt/zimbra/java/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
Remove old versions of Zimlet.
[] INFO: Uninstalling Zimlet tk_barrydegraaff_owncloud_zimlet from LDAP.
[] INFO: undeploying zimlet tk_barrydegraaff_owncloud_zimlet
[] INFO: zimlet directory tk_barrydegraaff_owncloud_zimlet is deleted
Saving existing configuration to /tmp/webdav-client-installer.YwCIpFx9/upgrade
Download WebDAV Client to /tmp/webdav-client-installer.YwCIpFx9
Initialized empty Git repository in /tmp/webdav-client-installer.YwCIpFx9/owncloud-zimlet/.git/
error:  while accessing https://github.com/barrydegraaff/owncloud-zimlet/info/refs
```

I've checked, the accessed page gives a 404.

**Comment by barrydegraaff** [comment]
This is a Github issue, I will file a support request there.

**Comment by barrydegraaff** [comment]
re-download the installer and try again.

**Comment by KlugFR** [comment]
Same issue.

`Initialized empty Git repository in /tmp/webdav-client-installer.4AIMh0mo/owncloud-zimlet/.git/
error:  while accessing https://github.com/Zimbra-Community/owncloud-zimlet/info/refs

fatal: HTTP request failed`

**Comment by barrydegraaff** [comment]
Can you change
git clone --depth=1 https://github.com/Zimbra-Community/owncloud-zimlet
to
git clone --depth=1 ssh://git@github.com/Zimbra-Community/owncloud-zimlet


And see if that works, I am starting to dislike centos 6

**Comment by KlugFR** [comment]
While I hate Ubuntu.

```[root@zimbra-ose03 tmp]# git clone --depth=1 ssh://git@github.com/Zimbra-Community/owncloud-zimlet
Initialized empty Git repository in /tmp/owncloud-zimlet/.git/
Permission denied (publickey).
fatal: The remote end hung up unexpectedly```

The correct way to go it is this (and I think it should work with any OS):
``` git clone --depth=1 git://github.com/Zimbra-Community/owncloud-zimlet   ```

**Comment by barrydegraaff** [comment]
Hate Ubuntu as well, especially the 12. and 14. basically I hate all the old crap.

git clone --depth=1 git@github.com:Zimbra-Community/owncloud-zimlet.git

What does work on your set-up?

**Comment by barrydegraaff** [comment]
Nah, I see, 
``` git clone --depth=1 git://github.com/Zimbra-Community/owncloud-zimlet ```

works, I am asking github support, I am not in the mood to find and replace all my git clone commands
in all my repos.

**Comment by KlugFR** [comment]
Good luck with them.
