### ISSUE TITLE
Problem with "Open Nextcloud tab" button

### ISSUE THREAD

**Issue by KlugFR** [Zimbra-Community/owncloud-zimlet#157]
Hello.

From what I've read/understood, this button is supposed to open a new browser tab with the genuine NextCloud (or other app) interface. If nothing is in the configuration field, the button should not appear.

I've correctly (I think) setup the zimlet for my account (zmprov ga myaccount |grep -i owncloud with a bit of filtering):

```
zimbraZimletUserProperties: tk_barrydegraaff_owncloud_zimlet:owncloud_zimlet_default_folder:/
zimbraZimletUserProperties: tk_barrydegraaff_owncloud_zimlet:owncloud_zimlet_ask_folder_each_time:false
zimbraZimletUserProperties: tk_barrydegraaff_owncloud_zimlet:owncloud_zimlet_template:
zimbraZimletUserProperties: tk_barrydegraaff_owncloud_zimlet:owncloud_zimlet_oc_folder:
zimbraZimletUserProperties: tk_barrydegraaff_owncloud_zimlet:owncloud_zimlet_server_name:https://files.domain.tld
zimbraZimletUserProperties: tk_barrydegraaff_owncloud_zimlet:owncloud_zimlet_server_path:/remote.php/webdav/
zimbraZimletUserProperties: tk_barrydegraaff_owncloud_zimlet:owncloud_zimlet_server_port:443
zimbraZimletUserProperties: tk_barrydegraaff_owncloud_zimlet:owncloud_zimlet_use_numbers:false
```

However, the button is here (even after a flushcache and a login/logout) and it links to https://zimbraURL.domain.tld/nextcloud...

Why do the button doesn't take my configuration?
Neither owncloud_zimlet_server_name nor owncloud_zimlet_oc_folder seems to be used.

**Comment by barrydegraaff** [comment]
The button is a bit silly (legacy), in retrospect it would have made more sense to have it take the owncloud_zimlet_server_name in some cases. But remember that not everybody uses nextcloud, so the url for the dav server is not always a web-ui that people can use.

See here:
https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences
And if you read carefully:
owncloud_zimlet_extra_toolbar_button_title	
If a value is set, show an additional button in the WebDAV tab to open in a new browser window the url set in owncloud_zimlet_extra_toolbar_button_url.

Aka, when owncloud_zimlet_extra_toolbar_button_title is blank, there is no button. It is a globally set configuration. Not a per-user one.

**Comment by barrydegraaff** [comment]
Yeah, as I said  _silly (legacy)_ so it is one thing for everybody.

The original idea was to use Zimbra proxy in a way multiple customers (width different domains) could use their own nextcloud based on what is behind the proxy. But that does not work well, as the proxy has too many issues. So the button is a left-over.

The idea was to configure the zimlet to point to /nextcloud and then in the proxy route the customer to their own nextcloud.

https://github.com/Zimbra-Community/owncloud-zimlet/wiki/Troubleshooting

I was thinking about allowing certain keywords in : 
owncloud_zimlet_extra_toolbar_button_url

When set to owncloud_zimlet_server_name use the users owncloud_zimlet_server_name. But then again I am not sure if there is much demand for this button, so perhaps removing it is better...

I no longer use it on any of my deployments, but sometimes do mis it. What do you think?

**Comment by KlugFR** [comment]
I'm not sure the button is _that_ needed.
But I'd say it's a nice addition for users so they can easily go and check on their Nextcloud interface do whatever they want (restore old versions, check/revoke shares, etc).

However, I don't know if the "good way" is to let the user setup what he wants (webdav server, webdav folder, webdav URL) or if this should be set at the CoS/domain level by the admin.
Right now, I think it should be let to the admin (who should also add the URL/domain of the webdav server to the allowed list, doesn't he?)

**Comment by barrydegraaff** [comment]
The allow list does not do anything in thus case. As the browser just goes to the link.

The Zimbra backend requests are limited by the allow list, but that has nothing to do in this case.

**Comment by barrydegraaff** [comment]
OK for new installs I renamed `Open Nextcloud tab` to `Go to Nextcloud`

And changed the behavior of owncloud_zimlet_extra_toolbar_button_url:
Instead of a URL you can set it to `owncloud_zimlet_server_name` it opens the URL set in owncloud_zimlet_server_name (may be set by user). 

When set to `owncloud_zimlet_oc_folder` it opens the URL set in owncloud_zimlet_server_name combined with owncloud_zimlet_oc_folder (maybe set by user).

That should allow to use the button in most cases.
