### ISSUE TITLE
RFE: OnlyOffice secret per domain

### ISSUE THREAD

**Issue by adriangibanelbtactic** [Zimbra-Community/owncloud-zimlet#158]
I was checking 003ff2049d603b1b33cfbf150c1d35dea6f8a792 and I'm not very confident on having a single OnlyOffice secret for previewing all our documents.
I would rather have an option to be able to setup an onlyoffice secret per domain (which the final user cannot see from the properties).

The current design implies there is only one onlyoffice secret for the Zimbra installation.

Any thoughts on how to implement this improvement?
Is it even possible to gather Domain data from a zimlet? I guess not because you would be able to check DKIM and other sensible data.

Thank you.

( Somehow related to: https://github.com/Zimbra-Community/owncloud-zimlet/issues/151 issue. )

**Comment by barrydegraaff** [comment]
I am not 100% sure what you mean by final user. 

A Zimbra extension can access pretty much everything. 

In this design, the secret is there to prevent others from using your 
OnlyOffice instance. 

With secret configured, the OnlyOffice instance only previews/edits documents 
of the Zimbra/Nextcloud instances intended (that know the secret). And not the 
entire world. 

Wihout secret anybody can use the instance... 


The secret itself however is part of the JSON Web Tokens idea. 

So the best solution would be implementing JSON web tokens fully. JSON Web Tokens 
work by digitally signing the parameters used to communicate with OnlyOffice. 

OnlyOffice does not require to sign all parameters, so now the Zimlet sends 
an empty message (basically), that is always the same (and can be found and 
reused via the developer console by authenticated users). 

If all parameters where signed, people could no longer re-use stuff 
found by snooping in the developer console. 

You can try and implement by reading the OnlyOffice docs and commits from issue 151, 
that you already found. 

Not sure if that is what you where asking. 


Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 | skype: barrydegraaff.tk 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by barrydegraaff** [comment]
I do not really see the added value of a per domain configuration here.

**Comment by barrydegraaff** [comment]
Also the way things work is that the Zimlet requests a one-time-only access link to the document to be previewed. That link is passed to onlyoffice, that fetches the document.

Even if the user would know the onlyoffice secret, that would not allow to redownload or even refresh a document. As the one-time-only link can only be obtained by the user that has access to Nextcloud (username and password)

**Comment by adriangibanelbtactic** [comment]
> I am not 100% sure what you mean by final user.
A Zimlet property.
> A Zimbra extension can access pretty much everything.
I see.
> In this design, the secret is there to prevent others from using your OnlyOffice instance.
Yeah, that's right. It's a design feature that I also prefer myself.

**Comment by adriangibanelbtactic** [comment]
> Also the way things work is that the Zimlet requests a one-time-only access link to the document to be previewed. That link is passed to onlyoffice, that fetches the document.
> 
> Even if the user would know the onlyoffice secret, that would not allow to redownload or even refresh a document. As the one-time-only link can only be obtained by the user that has access to Nextcloud (username and password)

Ok, that's good to know.

I'm also concerned about GDPR issues. One customer wanting his onlyoffice server to be in one country and another custom wanting his onlyoffice server to be in another country.

That's why I thought it was a good idea to have different onlyoffice servers per domain.

Anyway, I think I'll postpone this idea for now.

**Comment by barrydegraaff** [comment]
yes, but if a customer wants it's only office server in country X, wouldn't that same customer want its Zimbra also in Country X?

The secret itself cannot be found by the end user, as it is not a Zimet (LDAP) User property, also prop2xml has been changed so that the secret is not added to the Zimlet configuration XML (config_templace.xml).

The OnlyOffice server is a thing that does not store anything, it has no 'memory', so as long as you deploy it in a way similar to 
https://github.com/Zimbra-Community/owncloud-zimlet/wiki/OnlyOffice-Nextcloud

You should be OK for GDPR compliancy.
