### ISSUE TITLE
Alternative to set-java-path.sh

### ISSUE THREAD

**Issue by adriangibanelbtactic** [Zimbra-Community/owncloud-zimlet#159]
I do not like having to use set-java-path.sh as you suggest in README.md:
set-java-path.sh tries to blind guess the java path and, maybe, it will break if Zimbra developers change once again the Java path.

```
wget https://raw.githubusercontent.com/Zimbra-Community/prop2xml/master/set-java-path.sh -O /tmp/set-java-path.sh
wget https://github.com/Zimbra-Community/prop2xml/raw/master/out/artifacts/prop2xml_jar/prop2xml.jar -O /tmp/prop2xml.jar
chmod +rx /tmp/set-java-path.sh
source /tmp/set-java-path.sh
java -jar /tmp/prop2xml.jar tk_barrydegraaff_owncloud_zimlet /opt/zimbra/lib/ext/ownCloud/config.properties /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_owncloud_zimlet/config_template.xml
```

I prefer doing most of the work as zimbra user so that you don't have to bother about the JAVA path.

As Zimbra user:
```
wget "https://github.com/btactic/prop2xml/raw/master/out/artifacts/prop2xml_jar/prop2xml.jar" -O /tmp/prop2xml.jar

java -jar /tmp/prop2xml.jar tk_barrydegraaff_owncloud_zimlet /opt/zimbra/lib/ext/ownCloud/config.properties /tmp/config_template.xml
```
As root user:
```
 cp /tmp/config_template.xml /opt/zimbra/lib/ext/ownCloud/config_template.xml
chown zimbra:zimbra /opt/zimbra/lib/ext/ownCloud/config_template.xml
```
.

It would seem the main problem resides in /opt/zimbra/lib/ext/ownCloud/ folder permissions which does not let create new files.

So... What do you think it would be the best approach for this problem?

**Comment by barrydegraaff** [comment]
Just keep it like this and update set-java-path if Zimbra changes.

User may or may not have a correct path even if they are logged in as zimbra.

**Comment by barrydegraaff** [comment]
I would not call this a `blind guess` as this Zimlet only supports 3 versions of Zimbra, and the 8.6 support is ending soon. So set-java-path may not be the greatest solution technically, it works well = less github issues.
