### ISSUE TITLE
Help on debugging onlyoffice preview not working on ZCS 8.6

### ISSUE THREAD

**Issue by adriangibanelbtactic** [Zimbra-Community/owncloud-zimlet#166]
Our setup is the following one:
* Proxy server : ZCS OSE 8.6
* Mailbox server : ZCS OSE 8.6
What I mean is that our proxy server and mailbox server are separated.

0.1. Browsing files from Nextcloud does work.
0.2. Downloading files from Nextcloud does work.
0.3. Trying to preview files thanks to Onlyoffice does not work. It tries to edit an empty document.

1. Is onlyoffice preview supported in Zimbra scenarios where the proxy server and the mailbox server are in different servers?
Has it even tested? 
as it even tested specifically for ZCS 8.6?

2. Does onlyoffice preview use the Nextcloud/Owncloud server name for previewing from the zimlet configuration or from the zimbra user configuration?

```
owncloud_zimlet_server_name
```

3. How I go about debugging this stuff?
Can you please explain me how the downloaded file from Nextcloud is passed to Onlyoffice to be edited?
Can I add somewhere a debug line that maybe writes into mailbox.log which Nextcloud url OnlyOffice is trying to read?
Or is it something that only can be debugged via javascript? How, then?
What is the exact code that is triggered when you click on a file and onlyoffice preview starts?

Is it:  https://github.com/Zimbra-Community/owncloud-zimlet/blob/170c31e25e3f46db240f0e398e82da3fd6d10c76/zimlet/OwnCloudListView.js#L568-L623 ?

Should I maybe output an alert of url defined in this line:
https://github.com/Zimbra-Community/owncloud-zimlet/blob/170c31e25e3f46db240f0e398e82da3fd6d10c76/zimlet/OwnCloudListView.js#L737

If I use that output url from a browser will I get the same document OnlyOffice would try to preview?

Thank you very much for any help you can give me.

**Comment by barrydegraaff** [comment]
First, I can debug it for you, for a small donation.

What I can imagine is that the URL to the document is not passed correctly to onlyoffice. 

For example using a wrong port/url, for example 8443 and maybe an internal hostname.

To debug:

Go to the Nextcloud tab in the web UI - so make sure it is already loaded.

Use google chrome, hit F12 to open developer tools and go to the console tab, copy-paste the method here: https://gist.github.com/barrydegraaff/ca37a6aca7e046e8b87cca4675bc789e

Basically what that does is overwrite the method:
OwnCloudListView.prototype.preview

And adds
 
      console.log(url + token + "&name=" + encodeURIComponent(davResource.getName()) + "&contentType=" + contentType);     

on line 731.

Now clear the console log, and preview a docx, then the URL should be printed on the console log:

https://mail.zetalliance.org/service/extension/dav_download/?token=370872b5803bbfa0f6efe4940662eeaa&name=Nutanix-NEXT-2017-conference-justification.docx&contentType=application/vnd.openxmlformats-officedocument.wordprocessingml.document

This is an example from my working server, you must check and make sure that URL works in your set-up.

What is the URL in your case?

**Comment by barrydegraaff** [comment]
Check the access log
cat /opt/zimbra/log/access_log.2018-05-02 | grep dav_download

**Comment by barrydegraaff** [comment]
I see you already tried some of this, proxies can break stuff easy, especially when rewriting url's.

**Comment by barrydegraaff** [comment]
Instead of using wget, can you use  curl, like so:

    curl -v url here

So we can see the headers.

**Comment by barrydegraaff** [comment]
**_Do you use multiple mailbox servers?_** If so, than I guess it probably won't work well as the code here:
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/extension/src/com/zextras/dav/DownloadJob.java#L12

AFAIK the download job token is stored in memory on a single mailbox server... so that would result in mixed results, aka won't work on a mailserver that did not got the original request to create a download job.

**Comment by adriangibanelbtactic** [comment]
> What I can imagine is that the URL to the document is not passed correctly to onlyoffice.
> 
> For example using a wrong port/url, for example 8443 and maybe an internal hostname.
(...)
> This is an example from my working server, you must check and make sure that URL works in your set-up.
> 
> What is the URL in your case?

The url works fine (when querying directly the mailbox).
Url is using the public name of the proxy such as:

https://mail.example.com/service/extension/dav_download/?token=389c8255555dcc6644a1f5d38f2c2940&name=pruebadocx3.docx&contentType=application/vnd.openxmlformats-officedocument.wordprocessingml.document

So as you can see it's not a problem about the url being incorrect.

**Comment by adriangibanelbtactic** [comment]
> Check the access log
> cat /opt/zimbra/log/access_log.2018-05-02 | grep dav_download

Just after clicking the file for previewing it I get on the proxy:

```
1.2.3.4:45386 - - [03/May/2018:10:53:07 +0200]  "POST /service/extension/dav_download/ HTTP/1.1" 200 295 "https://mail.example.com/zimbra/" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" "172.16.87.24:80"

5.6.7.8:34205 - - [03/May/2018:10:53:17 +0200]  "GET /service/extension/dav_download/?token=9cb339f9dad350d7af69b093379a54f2&name=pruebadocx.docx&contentType=application/vnd.openxmlformats-officedocument.wordprocessingml.document HTTP/1.1" 200 109 "-" "-" "172.16.87.9:80"
```

where 1.2.3.4 is my public ip as a final user and where 5.6.7.8 is the onlyoffice public ip.

As you can see I am interacting with 172.16.87.24 mailbox and onlyoffice is redirected to 172.16.87.9 mailbox instead.

**Comment by adriangibanelbtactic** [comment]
> AFAIK the download job token is stored in memory on a single mailbox server... so that would result in mixed results, aka won't work on a mailserver that did not got the original request to create a download job.

I guess there are other zimbra extensions with the same problem which might have solved them with a proper implementation / workaround.

I assume you don't know any of them.

**Comment by barrydegraaff** [comment]
You assume wrong, one work-around would be storing the tokens in MariaDB.

Another work-around would be to fetch the document from Nextcloud directly
(is a bit more difficult)

Also the Download Job implementation was written by Zextras.
So if you want to point fingers...

I would assume the download feature from the webUI would also not work
all the time right? Because that is the same code. If that works reliable
the webclient has some way of knowing what mailbox server to interact with.


Barry

**Comment by adriangibanelbtactic** [comment]
> You assume wrong, one work-around would be storing the tokens in MariaDB.

So you can access MariaDB from one account even if you are not in the correct mailbox.

> Another work-around would be to fetch the document from Nextcloud directly (is a bit more difficult)

I see.

> Also the Download Job implementation was written by Zextras. So if you want to point fingers...

:)
 
> I would assume the download feature from the webUI would also not work all the time right?
> 
> Because that is the same code. If that works reliable the webclient has some way of knowing what mailbox server to interact with. Barry

Well, so far in the proxy setup the download code works always.
I remember having problems in the past when download did not work but, as it seems, preview did not work either. So, I guess it was a problem of setting up correctly some settings.

Well, yes, I assume that running that download in the same Zimbra login space/environment keeps the redirection to the right mailbox.


1. Currently I'm checking:

https://github.com/ZeXtras/zimbra-drive/blob/master/zimbra-extension/src/com/zextras/zimbradrive/NcUserZimbraBackendHttpHandler.java#L129-L153

My main idea about this implementation approach would be to send the account name to onlyoffice so that the GET call has the account name in it and then the GET request can be forwarded to the correct mailbox (as the code above does with POST).

Example:
```
https://mail.example.com/service/extension/dav_download/?token=389c8255555dcc6644a1f5d38f2c2940&name=pruebadocx3.docx&contentType=application/vnd.openxmlformats-officedocument.wordprocessingml.document&account=myaccount@example.com
```


2. I'll try to check the download job implementation too.
Did you recycle it from zimbra-drive or should I look for another one of the zextras repo?

**Comment by barrydegraaff** [comment]
Sounds like you are working in the right direction, happy to merge that PR 
once it works. 

I think they recycled this from internal code, but it was way before Zimbra Drive 
coding started. 



Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 | skype: barrydegraaff.tk 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by adriangibanelbtactic** [comment]
> do a trick in the proxy could be a solution, maybe there is something build into Zimbra proxy for this.

Yes, that's the approach I'm using at:
https://github.com/btactic/owncloud-zimlet/tree/proxy_support
.

I will be proof-testing all of this new code in the next hours. I have never even tested it. I might rewrite some of the commits on that branch.

**Comment by barrydegraaff** [comment]
Where did you get that version of zal? In case you got it from the upstream Zextras, please do not use it!

As the original Zal has hard dependencies on the version of Zimbra AND the one configured in this project.

As a result, if we would use the original ZAL, we need to update our installer and ZAL, the build files for each release of Zimbra (and there are many) even if there are no changes to ZAL.

**Comment by barrydegraaff** [comment]
That is just too much work, also the releases from Zimbra and Zextras and ZAL are not coordinated. So people would need to re-install the WebDAV Client on each upgrade, and they would run into the issue of the ZAL not working (and file issues here).

With the patched ZAL, one can upgrade from 8.7.6 to 8.8.8 without having to re-install the WebDAV client.

As you notice a lot of considerations here, on having the least amount of issues filed.

You can see the changes of our ZAL here:
https://github.com/Zimbra-Community/OpenZAL

We are only one release behind. so you can check the changes in that repo, then fork Zextras/OpenZAL
re-apply the changes, and then push that to Zimbra-Community/OpenZAL and then we can use it in this project without all the pain.

If I where to rewrite the project, I would not put ZAL in it...

**Comment by barrydegraaff** [comment]
500 errors should be logged in mailbox.log
tail -f /opt/zimbra/log/mailbox.log

String accountStr = paramsMap.get("account");
Means _account_ must be present in the request, or you will get a nullPointer Exception.

Did you change the zimlet to include the account parameter?

**Comment by barrydegraaff** [comment]
Anyway I see you had a lot of fun with building ZAL :-p welcome to my world

**Comment by barrydegraaff** [comment]
I see you added it to the zimlet on one place, so to make it work everywhere, you need to either make a change to the java parts to be able to deal with not having the _account_ parameter or add it everywhere it is used in the Zimlet. Or it will break other functionality.

**Comment by barrydegraaff** [comment]
So your guess is good, see my comment above, add the account parameter everywhere or change the java code like:

      String accountStr = "";
      if(paramsMap.get("account") != null)
      {
          accountStr = paramsMap.get("account");
      }

Just typing from my mind here, not tested

**Comment by barrydegraaff** [comment]
You also need to make a few more changes to make above snipped work with your new stuff

**Comment by barrydegraaff** [comment]
I’ll try and throw in the new version of ZAL tomorrow.

**Comment by barrydegraaff** [comment]
So here is a new version of ZAL:
https://github.com/Zimbra-Community/OpenZAL/raw/master/dist/8.8.8/zal.jar

Can you try and use that version in your work, it is based on the latest from Zextras, excluding all the version checking. Thanks!

**Comment by barrydegraaff** [comment]
@adriangibanelbtactic let me know if you need more help implementing, I consider it vital to support multi-server environments, but I have no customers running multi-server, so I never tested/worked with it much.

**Comment by adriangibanelbtactic** [comment]
> 500 errors should be logged in mailbox.log
> tail -f /opt/zimbra/log/mailbox.log

I don't see any of this for the owncloud-zimlet when requesting POST to dav_download. There's no exception thread in my 8.7.11 single server test machine.

Do you switch any setting in order to produce such logs?
Or is it perhaps compulsory to catch the exception and log it manually?

**Comment by adriangibanelbtactic** [comment]
> I see you added it to the zimlet on one place, so to make it work everywhere, you need to either make a change to the java parts to be able to deal with not having the account parameter or add it everywhere it is used in the Zimlet. Or it will break other functionality.

Yes, you are right. I realised later on yesterday while being offline. I'll do something about it.

**Comment by adriangibanelbtactic** [comment]
> So here is a new version of ZAL:
> https://github.com/Zimbra-Community/OpenZAL/raw/master/dist/8.8.8/zal.jar
> 
> Can you try and use that version in your work, it is based on the latest from Zextras, excluding all the version checking. Thanks!
> 
> New version of ZAL is tested on 8.6, 8.7.11 and 8.8.8 and is now in the project.

Nice. I'll let you know if I find any problems.

**Comment by barrydegraaff** [comment]
uncatched exceptions should log by default.Usually error 500 is an uncatched exceptions.

But I guess we'll see after you make the java changes.

**Comment by barrydegraaff** [comment]
Never had this problem, but thx for the pointer

**Comment by adriangibanelbtactic** [comment]
> That is just too much work, also the releases from Zimbra and Zextras and ZAL are not coordinated. So people would need to re-install the WebDAV Client on each upgrade, and they would run into the issue of the ZAL not working (and file issues here).
> 
> With the patched ZAL, one can upgrade from 8.7.6 to 8.8.8 without having to re-install the WebDAV client.
> 
> As you notice a lot of considerations here, on having the least amount of issues filed.

Maybe you should have different releases for different major Zimbra versions as the ZeXtras team does.

I might guess what you're going to answer me ;). Were you to use that policy then I could not implement the proxy support on ZCS 8.6 due to lack of some functions in ZCS 8.6 ZeXtras zal.

Anyway... give it a thought because it would be nice you not having to maintain your own zal fork.

**Comment by barrydegraaff** [comment]
Well that is one of the good points of Zextras, they put a lot of work in forwards and backwards compatibilty.

I did found that there is a development option in ZAL now that may do exactly what we need, so perhaps in the future I stop forking it.

However, so far the fork paid off, as it gave me less work.

One release for all supported versions is what I want to do, focus on improving and not testing different versions of Zimbra. There is a fat chance the feature you want will be added to 8.6 via ZAL even if it is included in 8.8 core Zimbra.

Besides I still have nextcloud, owncloud and all the other dav servers to look at as well, so enough work as is, not having multiple versions.

**Comment by adriangibanelbtactic** [comment]
It works!!!
Pull request is coming.

**Comment by barrydegraaff** [comment]
fixed by https://github.com/Zimbra-Community/owncloud-zimlet/pull/170/files/dc2937f230441a0f8bbef11882abd9e4d9fae038..ff13a4d7585f4613f7cff1c70466e9fa3cc5a6e2
