### ISSUE TITLE
webdav-client-installer.sh no longer has execution permissions

### ISSUE THREAD

**Issue by adriangibanelbtactic** [Zimbra-Community/owncloud-zimlet#167]
This commit: https://github.com/Zimbra-Community/owncloud-zimlet/commit/0f59444dbb48aa48d0a3164a32378f8fef24c4c1 changed the file permissions from 10644 to 10755 .

Was it on purpose or is it a bug?

**Comment by barrydegraaff** [comment]
It is a bug

**Comment by barrydegraaff** [comment]
But it was already fixed on the `main` branch

**Comment by barrydegraaff** [comment]
But was not fixed really, I committed it as 10755 again. Thanks for reporting
