### ISSUE TITLE
Sharing already shared files

### ISSUE THREAD

**Issue by lnxbil** [Zimbra-Community/owncloud-zimlet#168]
Hi Berry,

Thank you for this great Zimlet.

I have a minor problem which concerns sharing an already shared-to-me file, which does generate a "could not create share" message. I tried with and without "resharing" enabled.

Best,
Andreas

**Comment by barrydegraaff** [comment]
I tested with 
User K shared folder with me, I shared using a public link a file in the folder shared from K, and that worked.

**Comment by barrydegraaff** [comment]
With a single file it works as well to re-share.

How did you share, what is your Nextcloud version?

**Comment by barrydegraaff** [comment]
I tested on Nextcloud 13.0.1... I know, I am one minor behind atm.

**Comment by lnxbil** [comment]
Okay, the file itself was marked as "non-shareable", as were all others. I assume the once unset "allow resharing" triggered all created shares with this flag and the files were not reset upon a change to the "allow resharing" flag.

So let's open another issue with the correct issue contents.

**Comment by lnxbil** [comment]
Thanks for the ultra fast test and answers :+1:
