### ISSUE TITLE
moving away from Github

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/owncloud-zimlet#175]
I was thinking about moving the Zeta Alliance to Gitlab, but perhaps you have other ideas, please let me know your preferences, so we can vote on it. If no-one objects I am leaning to Gitlab, it is open-source and free. It can be run from gitlab.com or in a dedicated VM

https://blog.github.com/2018-06-04-github-microsoft/

https://gitlab.com/zimbra-community
https://gitlab.com/barrydegraaff

**Comment by barrydegraaff** [comment]
Please add your comments as member of the Zeta Alliance Github team, thanks!

@bucchi
@dploeger
@Dual-Boot
@fsschmidt
@iomarmochtar
@jorgedlcruz
@maxxer
@mrCine
@nomennesc-io
@plobbes
@quanah
@tuanta
@Victor-D
@wolfyzvf
@zeta-ajcody

**Comment by Victor-D** [comment]
Is it due to MicroSoft buying Github ?
Gitlab is opensource, but the other projects are on github so ...

Victor

**Comment by barrydegraaff** [comment]
Anyway, I will stop using wget in the installer scripts, instead I will move to a tar.gz or some other way to have an offline installer. This will make future moves to different gits more easy.

**Comment by barrydegraaff** [comment]
@victor-d yes, I think a lot of projects will move away from Github now. It will be rebranded as codelab-365 or some other crap with one-drive integration and 100000 ads. So I do not like to wait for that

**Comment by barrydegraaff** [comment]
Hoping there will be a migration tool soon :-p

**Comment by maxxer** [comment]
Gitlab is a nice platform, I use it daly on premise and it's fantastic. I also use it on gitlab.com for a side project and it's cool because you can even create private projects for free.

Given that I'd wait to see what the acquisition mean for GH. If it becomes full of crappy ads and stuff like that it'll be easy to move the source over to any other platform.  I see no rush.

I've historically never been a fan of Microsoft, but I don't see the move  as bad *per se*.

**Comment by jorgedlcruz** [comment]
**-1** it doesn't make any sense, all the open source code shared here it is already open, and it does include the license that every creator has decided, GPLv2/3, MIT, etc. They already said GitHub will remain independent, and Microsoft is one of the biggest contributors to Open Source on GitHub, despite the whole effort the Company is doing by having now SQL on Linux, their own Linux distro, Linux inside Windows 10/Server 2016 and such. Plus not to forget what happened to gitlab a year ago when they actually lose data of people using their service - https://about.gitlab.com/2017/02/01/gitlab-dot-com-database-incident/ GitHub has one of the best deployments which has already supported and mitigated huge attacks in the past.
Last but not least, the whole SEO of when people searching for projects in Google will be affected, and if it was difficult to put small projects like the OpenPGP or WebDAV or so on the google radar when people search for Zimbra, will be even difficult or impossible if you move that away from GitHub.

**Comment by quanah** [comment]
Embrace, Extinguish, Extend -- The words Microsoft lives by.  Also, licenses still haven't prevented MS from allegedly stealing code w/o attribution.  As a direct competitor to MS, it also puts Zimbra and all things related to it in an odd position.  GitHub specifically did not mine user data for ads.  There's no guarantee MS won't change that policy (and it is likely they will).  One also need only look at what MS has done to LinkedIn to seriously question any plans they have for GitHub. https://twitter.com/jamiebuilds/status/1002696910266773505

**Comment by tuanta** [comment]
+1 with @quanah .

I vote for moving to BitBucket.

**Comment by iomarmochtar** [comment]
+1 for bitbucket, i used it since several years ago and no issue so far. 
i haven't use gitlab but [deleted production data](https://about.gitlab.com/2017/02/01/gitlab-dot-com-database-incident/) quite scary enough

**Comment by Dual-Boot** [comment]
Good idea to move to gitlab and I agree with @quanah .
And now Gitlab is moving to Education and OpenSource community by offering for free Ultimate and Gold subscription : 
https://about.gitlab.com/2018/06/05/gitlab-ultimate-and-gold-free-for-education-and-open-source/
Enjoy

**Comment by barrydegraaff** [comment]
There is also: 
https://phacility.com/phabricator/ 
https://github.com/phacility/phabricator 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 | skype: barrydegraaff.tk 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
