### ISSUE TITLE
Unknown command sent to server: ZxChatRequest

### ISSUE THREAD

**Issue by bradleyb127** [Zimbra-Community/owncloud-zimlet#176]
I installed Ubuntu 16.04.4 LTS and Zimbra 8.8.8_GA_2009.FOSS

When logging into the admin account through the web interface, I get an error:
Unknown command sent to server: ZxChatRequest

I found information on two different versions of ZAL on ZCS8.6 but could not find that on the FOSS version I am running even though the error was identical.  

I wasn't able to find information that applied to the open source version but my experience level with Ubuntu is a beginner so I might have overlooked something.      This is the second time I have installed Ubuntu and Zimbra with the same result.

Thank you in advance.

**Comment by barrydegraaff** [comment]
That means you have enabled Zextras Chat or Zimbra chat Zimlet but the server side components are not installed or loaded.

Restart zimbra

**Comment by bradleyb127** [comment]
That did is.   Thank you.    I'm sorry that I did not try that first.
