### ISSUE TITLE
Implement editing lock based on the fileid

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/owncloud-zimlet#180]
Implement an edit lock, so users don't overwrite each others document using fileid.

https://docs.nextcloud.com/server/12/developer_manual/client_apis/WebDAV/index.html

It will be hard to do this across implementations though. Aka when one users edits from this zimlet, another from nextcloud, and another perhaps using networked storage and an office suite...

**Comment by barrydegraaff** [comment]
Perhaps we should avoid using the fileid, and save the document hash before editing and compare it when storing the result, and in case the hash has changes, store a copy of the file under a different name.

**Comment by mnichols62** [comment]
I really like your last idea...
