### ISSUE TITLE
What IP?

### ISSUE THREAD

**Issue by MisTerM7** [Zimbra-Community/owncloud-zimlet#183]
Hello
For this command:
`zmprov mcf +zimbraMailTrustedIP `

What IP do I have to introduce?

Wan or local (127.0.0.1)?

Thanks for your help, because I'm in the impasse, in the without that it is a production server and I do not want to make a mistake.

Mz

**Comment by barrydegraaff** [comment]
That depends a bit, you will want to put the IP there Zimbra uses/Nextcloud sees when Zimbra is 
doing requests to your Nextcloud. 

Check the Nextcloud/apache access log to be sure, and then follow: https://github.com/Zimbra-Community/owncloud-zimlet#configure-bruteforce-protection

**Comment by MisTerM7** [comment]
Hello Barry
Yes, OnlyOffice is install and visible under NexCloud, other info I forget to give, but I do not know if it is a big barn, the NextCloud, is not install on the same machine as Zimbra.
Thank you
Mz

**Comment by barrydegraaff** [comment]
zimbraMailTrustedIP does not have any effect on onlyoffice (I think).

can you send a test Zimbra/nextcloud account to info@barrydegraaff.tk ?

Thanks
