### ISSUE TITLE
Zimbra 8.8.9 GA

### ISSUE THREAD

**Issue by oe73773** [Zimbra-Community/owncloud-zimlet#184]
owncloud-zimlet works with zimbra 8.8.9 but there are some issues.
The "Nextcloud" in the menue is not shown and "Nextcloud" is not shown in attachement sources. A blank is there instead.

Are there any plans to support newer Zimbra Versions?

**Comment by barrydegraaff** [comment]
It is working fine in the latest version of Zimbra and all versions of 8.8.

Please re-run the installer and then afterwards:
git clone git@github.com:Zimbra-Community/owncloud-zimlet.git
cd owncloud-zimlet
./nextcloud-labels

To force the Nextcloud labels

**Comment by oe73773** [comment]
Thanks for the answer.
Forcing the Nextcloud labels works as described.
