### ISSUE TITLE
Nextcloud not work 

### ISSUE THREAD

**Issue by sent1989** [Zimbra-Community/owncloud-zimlet#185]
On browser console after connect Zimbra 8.6.0.RHEL7 webmail  :
core.js?v=023ca270-0:5729 PROPFIND https://HOSTZIMBRA/owncloud/remote.php/dav/files/659f92e6-7400-1035-8afa-973338c77d5c/ 501 (Method PROPFIND is not defined in RFC 2068 and is not supported by the Servlet API)
request	@	core.js?v=023ca270-0:5729
propFind	@	core.js?v=023ca270-0:5569
getFolderContents	@	client.js?v=023ca270-0:482
reload	@	merged-index.js?v=023ca270-0:6091
changeDirectory	@	merged-index.js?v=023ca270-0:5947
_onUrlChanged	@	merged-index.js?v=023ca270-0:4929
dispatch	@	core.js?v=023ca270-0:3
r.handle	@	core.js?v=023ca270-0:3
trigger	@	core.js?v=023ca270-0:3
a.event.trigger	@	core.js?v=023ca270-0:7
(anonymous)	@	core.js?v=023ca270-0:3
each	@	core.js?v=023ca270-0:2
each	@	core.js?v=023ca270-0:2
trigger	@	core.js?v=023ca270-0:3
_onPopState	@	merged-index.js?v=023ca270-0:299
initialize	@	merged-index.js?v=023ca270-0:128
(anonymous)	@	merged-index.js?v=023ca270-0:340
(anonymous)	@	core.js?v=023ca270-0:781
setTimeout (async)		
_.delay	@	core.js?v=023ca270-0:780
executeBound	@	core.js?v=023ca270-0:714
bound	@	core.js?v=023ca270-0:746
(anonymous)	@	merged-index.js?v=023ca270-0:339
j	@	core.js?v=023ca270-0:2
fireWith	@	core.js?v=023ca270-0:2
ready	@	core.js?v=023ca270-0:2
I	@	core.js?v=023ca270-0:2

**Comment by barrydegraaff** [comment]
yeah that means you are talking Webdav to a server that does not understand it.
That means you have set-up the Zimlet wrong aka you are talking to Zimbra, not
Nextcloud with the zimlet. That does not work.

Double check your server url and path. See the readme.md, and follow it closely, including
t(r)ailing /

**Comment by sent1989** [comment]
Thanks a lot.

I resolve following this wiki:
Serving Nextcloud ownCloud behind Zimbra's nginx

BR
Sent
