### ISSUE TITLE
Small screen support

### ISSUE THREAD

**Issue by adriangibanelbtactic** [Zimbra-Community/owncloud-zimlet#192]
Could you please implement an option on
```
/opt/zimbra/lib/ext/ownCloud/config.properties
```
to disable altogether in the UI the display of integrated help set by
```
owncloud_zimlet_welcome_url
```
variable ?

The integrated help display makes it difficulty to interact with owncloud files in small displays/screens.

Thank you very much.

**Comment by adriangibanelbtactic** [comment]
We are going to implement this feature ourselves.

**Comment by adriangibanelbtactic** [comment]
We saw that WebDAVPreview from zimlet/OwncloudApp.js is used not only for initial integrated help but also for file preview.
Not sure if an option for disabling altogether that tab is a good idea.

Maybe a switch button to show or not the preview which would expand/shrink the WebDAVListView width.

Not sure if we are going to implement it.

Have you had any idea on how to implement this @barrydegraaff ?

**Comment by barrydegraaff** [comment]
Yes the right pane is also used for the online-edit feature (onlyoffice)

Would it suffice if we included a blank html page to the project? It would allow one to configure the Zimlet to display that instead of the help page. 

You can also configure it to show any other page using the `owncloud_zimlet_welcome_url` property

**Comment by adriangibanelbtactic** [comment]
> Would it suffice if we included a blank html page to the project? It would allow one to configure the Zimlet to display that instead of the help page.

No.

I mean the root issue is the final user **not being able to see the complete filenames** in small screens because the preview is using half of the screen.

- Filename column cannot be made bigger to see the complete name.
- There is not a vertical line that we could use to shrink the preview page.
- It seems too basic for an UI.

Our current workaround is to remove type, size and modified columns.

I also had thought on putting the preview below (as Zimbra Drive tab does in some of its configuration).

Even having the preview where "To view a conversation, click on it" ( https://nts.pages.tcnj.edu/files/2014/12/Zimbra8-ScreenShot2.png ) text is  would be better than we have right now.

**Comment by barrydegraaff** [comment]
Yeah, dwt is a pain... resizing the columns dynamically has been proven a bit difficult.

Right now at least 28 characters are displayed. We could make the full name appear when the user
hovers the mouse over it (html title / tip)

Additionally one can find the full name using right-click -> properties, including the path, but it is tedious.

**Comment by barrydegraaff** [comment]
What display resolution are we talking about here?

**Comment by adriangibanelbtactic** [comment]
> We could make the full name appear when the user
hovers the mouse over it (html title / tip)

Yeah, that might be an acceptable workaround till the final fix.

**Comment by barrydegraaff** [comment]
@adriangibanelbtactic

I just committed the tooltip/title patch. It will display the tooltip for file/folder names
longer than 30 characters.

Shorter ones should display OK already, and I do not want to show the title if it is not
necessary. 

Can you confirm it works for you? Thanks!
