### ISSUE TITLE
onlyoffice binaries added to repository

### ISSUE THREAD

**Issue by adriangibanelbtactic** [Zimbra-Community/owncloud-zimlet#193]
Commit af9543a6d2ac3077cf60ecee8afe0382c751e011 is adding some binaries like:

```
onlyoffice/lib/commons-codec-1.9.jar
onlyoffice/lib/commons-io-1.4.jar
onlyoffice/lib/javax.servlet-api-3.0.1.jar
onlyoffice/lib/zcs-lib-json-simple.jar
onlyoffice/lib/zimbraclient.jar
onlyoffice/lib/zimbracommon.jar
onlyoffice/lib/zimbrastore.jar
```

```
onlyoffice/out/artifacts/onlyoffice_jar/onlyoffice.jar
onlyoffice/out/production/onlyoffice/tk/barrydegraaff/onlyoffice/OnlyOffice.class
onlyoffice/out/production/onlyoffice/tk/barrydegraaff/onlyoffice/OnlyOfficeExtension.class
```

1. What's the associated source code?
2. a. Can you please either split the source code into another project and add integration instructions? 2. b. Or remove the binaries and update the build instructions?

Thank you very much!

**Comment by barrydegraaff** [comment]
1. The source code associated is here:
https://github.com/Zimbra-Community/owncloud-zimlet/tree/soapServiceBarry/onlyoffice/src/tk/barrydegraaff/onlyoffice

**Comment by barrydegraaff** [comment]
These are from Zimbra upstream:
onlyoffice/lib/zcs-lib-json-simple.jar
onlyoffice/lib/zimbraclient.jar
onlyoffice/lib/zimbracommon.jar
onlyoffice/lib/zimbrastore.jar
(all of them here https://github.com/Zimbra-Community/zimbra-jars/tree/master/zimbra-jars-8.8.8) You can get them from the Zimbra installation as well.

The remainder is just other common used foss jars:
onlyoffice/lib/commons-codec-1.9.jar
onlyoffice/lib/commons-io-1.4.jar
onlyoffice/lib/javax.servlet-api-3.0.1.jar

Best thing indeed is to integrate into the build script, but it has no priority right now.
