### ISSUE TITLE
Drag and drop from briefcase to Webdav doesn't work

### ISSUE THREAD

**Issue by NQuebec** [Zimbra-Community/owncloud-zimlet#198]
No error messages, the file location dialog pops up but clicking OK button doesn't do anything.

Zimbra 8.8.11_GA_3737.FOSS under Ubuntu 18.04 LTS
Nextcloud 14.0.6

Thank you for the excellent work!

**Comment by barrydegraaff** [comment]
You can right-click the items and do the same thing. I will stop supporting drag&drop
