### ISSUE TITLE
cloning problem - timeout

### ISSUE THREAD

**Issue by adam-wolak** [Zimbra-Community/owncloud-zimlet#199]
Hello,
when I execute script it is timed out while cloning  into 'owncloud-zimlet' 
Stopping zimbra (with ladp up) did not help
Regards - Adam Wolak

**Comment by barrydegraaff** [comment]
OS and zimbra version?

**Comment by adam-wolak** [comment]
Ubuntu 16.04 
Zimbra 8.8.11

**Comment by barrydegraaff** [comment]
Try again... lets hope it was a small github issue

**Comment by adam-wolak** [comment]
tried yesterday and today - several times- fatal: unable to connect to github.com:

**Comment by barrydegraaff** [comment]
run the installer using: 
wget --no-cache https://raw.githubusercontent.com/Zimbra-Community/owncloud-zimlet/soapServiceBarry/webdav-client-installer.sh -O /tmp/webdav-client-installer.sh
chmod +rx /tmp/webdav-client-installer.sh 
bash -x /tmp/webdav-client-installer.sh 
on Ubuntu, often the ssl libs are outdated, causing https to malfunction. But without logging, I can't be sure

**Comment by adam-wolak** [comment]
not working
BTW - what is difference between your zimlet and Zimbra Drive?

**Comment by barrydegraaff** [comment]
It works from our servers, located in the USA:
https://zetalliance.org/nextcloud/index.php/s/bTPp8L6SMHifZME

So it must be something on your side preventing access to github.

Difference between drive and my zimlet, is that mine generally works better and is more configurable
(provided you can access github)

Here is a comparison:
https://zetalliance.org/zimbra-drive-vs-nextcloud-zimlet-zimbra-webdav-client/

**Comment by adam-wolak** [comment]
Is any way to manually write clon and use it by script?

**Comment by adam-wolak** [comment]
thx - I will try
meanwhile I tried to install zimbradrive. It goes usual way - by managing tar file, no problem

**Comment by adam-wolak** [comment]
and I see zimbradrive is creating nextcloud user not using that one which loggin 
(I matched zimbra user = nextcloud user)
Useless

**Comment by barrydegraaff** [comment]
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/README.md#known-issues-and-troubleshooting
