### ISSUE TITLE
504 - network service error has occurred.

### ISSUE THREAD

**Issue by adam-wolak** [Zimbra-Community/owncloud-zimlet#201]
I finally installed WebDav  - there was cache problem on Ubuntu 16. THX for your help
But now, when I try to configure zimlet I am getting 504 error

method: | davSoapConnector
-- | --
msg: | a network service error has occurred.
code: | CSFE_SVC_ERROR
detail: | HTTP response status 504

**Comment by barrydegraaff** [comment]
This is an indication that you may not have set the correct settings to have Zimbra connect to
your nextcloud.

See:
https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences

Set the settings like so:
https://raw.githubusercontent.com/Zimbra-Community/owncloud-zimlet/soapServiceBarry/docs/Nextcloud-prefs.png

Make sure to put the slashes (/) as they appear in the image.

That usually does the trick.

**Comment by adam-wolak** [comment]
it not quite clear from your guide if I should run commands which are below table in chapter Configuring preferences
If I do 
java -jar /tmp/prop2xml.jar tk_barrydegraaff_owncloud_zimlet /opt/zimbra/lib/ext/ownCloud/config.properties /opt/zimbra/zimlets-deployed/tk_barrydegraaff_owncloud_zimlet/config_template.xml
I am getting response - no such directory - there is no
zimlets-deployed/tk_barrydegraaff_owncloud_zimlet/ 
Do it means that installing gone wrong? BTW I see your zimlet in Zimbra

**Comment by adam-wolak** [comment]
it is exactly like here
https://raw.githubusercontent.com/Zimbra-Community/owncloud-zimlet/soapServiceBarry/docs/Nextcloud-prefs.png

**Comment by barrydegraaff** [comment]
From the readme:

Each user can configure the WebDAV Client for themselves by clicking Preferences in the Zimlet menu.

Initially the Preferences dialog will be filled with best guess values and values provided by the administrator in config.properties.

It is recommended that the administrator reviews the config.properties and change it to fit the needs. Doing this simplifies things for your users. You can find the configuration in /opt/zimbra/lib/ext/ownCloud/config.properties.

Please note that a preference set by the user has priority over a preference set in config.properties. And config.properties has priority over best guess preferences.



That means, that for testing purpose, you do not need to do the jar file stuff from the cli.  As the settings needed to
connect can be set via the UI (log in as a user, and on the left bottom Zimlets menu, set your preferences).

The readme explains the priority/defaults.


Some settings are for security aka disable_password_storing,allowdomains etc can only be set by running the jar, and you
do not see them in the web ui.

**Comment by barrydegraaff** [comment]
What is the url to your nextcloud?

**Comment by adam-wolak** [comment]
https://box.dekonet.pl

**Comment by adam-wolak** [comment]
![webdav](https://user-images.githubusercontent.com/29380247/51803443-99d5c900-2255-11e9-9182-8149999e0e25.png)

**Comment by barrydegraaff** [comment]
Try as so:

DAV Server:	
https://box.dekonet.pl

Port:	
443

DAV path:	
/remote.php/webdav/

Location ownCloud/Nextcloud: 	
/


If that does not work, see if you have a dosfilter issue:
https://wiki.zimbra.com/wiki/DoSFilter


If that does not work, you can send me a Nextcloud test account directly at
info@barrydegraaff.tk

**Comment by barrydegraaff** [comment]
That does not look right as your nextcloud server is not in /nextcloud

See earlier comment

**Comment by adam-wolak** [comment]
/var/www/nextcloud

**Comment by adam-wolak** [comment]
with this
Location ownCloud/Nextcloud: /
also does not work

**Comment by barrydegraaff** [comment]
these settings are correct, they work from my server (I am getting password error). 

Check dosfilter and see the /opt/zimbra/log/zmmailboxd.out for errors.

**Comment by adam-wolak** [comment]
nothing related there:
2019-01-27 09:52:50.604:WARN:oejh.HttpParser:qtp1712669532-4491: parse exception: java.lang.IllegalStateException: too much data seeking EOF in CLOSE for HttpChannelOverHttp@be6cd5e{r=1,c=false,a=IDLE,uri=null}

**Comment by adam-wolak** [comment]
mailbox.log
2019-01-27 17:54:03,789 INFO  [qtp1712669532-7022:https:https://mail.dekonet.pl/service/soap/NoOpRequest] [name=adam_w@dekonet.pl;mid=26;oip=83.4.143.172;port=43516;ua=ZimbraWeb$
$ZCS/8.8.11_GA_3737;via=83.4.143.172(ZimbraWebClient - FF64 (Win)/8.8.11_GA_3737);soapId=70b7907f;] soap - NoOpRequest elapsed=0

**Comment by adam-wolak** [comment]
![zimlets](https://user-images.githubusercontent.com/29380247/51805297-14a9de80-226c-11e9-9957-6f505fbe5771.png)
I can not see your zimlet

**Comment by adam-wolak** [comment]
mail.dekonet.pl u:barrydegraaff  p:WebDav12
box.dekonet.pl  u:barrydegraaff  p:WebDav12

**Comment by adam-wolak** [comment]
BTW - is sticky notes compatible with zimbra 8.8.11?

**Comment by barrydegraaff** [comment]
It is

**Comment by barrydegraaff** [comment]
Your nextcloud instance works, when configured on our Zimbra:
https://zetalliance.org/nextcloud/index.php/s/XLe9bzsG2kHetyD

You will not see this zimlet in your COS settings when deployed in dev mode. If you want to deploy it using ZIP files, follow the uninstall in the readme and then re-run the installer and answer N for the question `Do you want to automatically install Zimlet and force enable it in all COS'es?`

In addition, I will now look on your Zimbra install...

**Comment by barrydegraaff** [comment]
Is this a multi-server zimbra installation? If so it seems the Zimlet cannot talk to the mailbox node.

I am not sure how to fix that atm. Also your server is very slow and there are some JS related errors that are not coming from my zimlet. This suggest a cache or other install issue. In Google Chrome open the development console F12 and then click console and reload zimbra.

**Comment by adam-wolak** [comment]
No - it is single server instalation

pon., 28 sty 2019, 09:33: Barry de Graaff <notifications@github.com>
napisał(a):

**Comment by barrydegraaff** [comment]
Are you sure the Zimbra server can resolve and connect to box.dekonet.pl? The DNS and firewall etc need to work. As Zimbra proxies the request for the user (it does not go via the client)

Also run
tail -f /opt/zimbra/log/*.log

And send me the output of the logging, also see what changes when the 504 comes.

**Comment by adam-wolak** [comment]
Sorry for late answer - I was in trip
Definitely it is dns problem. I have 2 machines on one physical server with their internal ip's
So I fixed it and was, myself, able to connect to nextcloud - Working very nice
BUT .. when I tried to do the same for another zimbra account I am getting error 501 (like in attachment)
![dav_501_err](https://user-images.githubusercontent.com/29380247/51855784-5f8c2a80-232e-11e9-8719-f8fbcab82383.png)

**Comment by barrydegraaff** [comment]
Yeah that is because the default settings on your server are not set correct yet.

Aka it still has /nextcloud/ once you remove that it works.


So open the config.properties set the correct defaults. Run the prop2xml as in the readme. Then it will work for new accounts also.

Feel free to donate via paypal at info@barrydegraaff.tk to support me!

**Comment by adam-wolak** [comment]
I forgot - while on my account "go to nexcloud" button works OK on another account (with err llike in previos post) clicking this buttons is opening new zimbra window

**Comment by barrydegraaff** [comment]
Same problem as previous comment, set correct defaults then run prop2xml

**Comment by adam-wolak** [comment]
OK - I will try to fix it
Man YOU HAVE DONE PRETTY WORK - THX

**Comment by adam-wolak** [comment]
BTW you specified some zimbra js error - can you specify which one ?

**Comment by barrydegraaff** [comment]
In google chrome, hit f12 go to console and reload browser. If the error is no longer there, it was a cache issue.
