### ISSUE TITLE
folders visualization issues

### ISSUE THREAD

**Issue by ciompi** [Zimbra-Community/owncloud-zimlet#203]
![immagine](https://user-images.githubusercontent.com/42805725/52625029-654a4a00-2eb0-11e9-99d0-97a12320da0b.png)
this issue does not affect all users but all browsers for specific users
content folder columns are badly shown
no way to resize columns
no way to resize content file panel
content file correctly shown on side panel

**Comment by barrydegraaff** [comment]
What screen resolution is this?

Also you can resize the left folderlist, drag it to the left (this will also make the list of mail folders smaller)

Then it should work

**Comment by ciompi** [comment]
1280*1024 24 bbp
![immagine](https://user-images.githubusercontent.com/42805725/52627415-95e0b280-2eb5-11e9-9207-a5e3127aca9c.png)
no way for me
tested on multiple pcs on multiple browsers, same issue
other users doesn't have the same issue
I think that panel management and resizing is quite standard so can't figure an error of mine

**Comment by barrydegraaff** [comment]
Its probably an edge related bug, as we have not tested on MS Edge for a while

**Comment by ciompi** [comment]
it was firefox

**Comment by ciompi** [comment]
this is edge
![immagine](https://user-images.githubusercontent.com/42805725/52627927-beb57780-2eb6-11e9-90a9-75a4cb16b509.png)

**Comment by ciompi** [comment]
in any case, thank for your time

**Comment by barrydegraaff** [comment]
It has to be some vague driver or browser bug, none of my systems have it though.

**Comment by barrydegraaff** [comment]
What version of WebDAV Clients is this? Did you install the latest version?

If yes, try it with theme Harmony and the Font and Display Font Size -> Standard and 12pt in preferences.

**Comment by ciompi** [comment]
thankyou, I will check and report anwers

**Comment by ciompi** [comment]
![immagine](https://user-images.githubusercontent.com/42805725/52702786-32ba5300-2f7d-11e9-877d-0e3bf612e43a.png)

**Comment by ciompi** [comment]
![immagine](https://user-images.githubusercontent.com/42805725/52702828-4796e680-2f7d-11e9-8b3a-90bb4c1a51b5.png)

**Comment by ciompi** [comment]
client user settings:
settings: Armonia, standard, little 12 pts

**Comment by barrydegraaff** [comment]
@ciompi you never replied back to me what version of WebDAV Client you are using, but based on the screenshots, I see it is not an up to date version.

Can you please retry with the latest version, as I cannot reproduce your exact issue.

**Comment by ciompi** [comment]
I apologize for the delay. My collegues  never answered me either... I will
retry to ask them and also invite them to update Web dav.  Thank you for
following the issue. Gianmario



Il Mar 30 Apr 2019 13:05 Barry de Graaff <notifications@github.com> ha
scritto:

**Comment by ciompi** [comment]
Dear Barry, our email service provider (https://www.ilger.com/) uses
version 1.0.7 of Zimbra webdav plugin.
The issue I mentioned is about some accounts on multple browsers, whereas
other accounts are non affected at all.
Thankyou and best regards.
gmn


Il giorno mar 30 apr 2019 alle ore 13:05 Barry de Graaff <
notifications@github.com> ha scritto:

**Comment by barrydegraaff** [comment]
Yes, please upgrade to the newer version, as some of these bugs are fixed already.
