### ISSUE TITLE
Zimlet installed - Dev Mode (unable to set COS, how to move to prod mode).

### ISSUE THREAD

**Issue by dredge999** [Zimbra-Community/owncloud-zimlet#204]
I hope this isn't a dumb question but my zimlet is running in dev mode and in this mode I cannot manage COS it is applied to in the Zimbra admin.

I would like to either figure out how to apply the zimlet to COS in dev mode or move it to prod mode.
Can you let me know in any case how to move the zimlet into prod mode from dev mode?

Thanks,
Rick

**Comment by barrydegraaff** [comment]
Re-run the installer, read the questions and... answer N when asked for 
Do you want to automatically install Zimlet and force enable it in all COS'es? => N
and
Do you want to install the zimlet in easy mode? => N
