### ISSUE TITLE
Add script to change name

### ISSUE THREAD

**Issue by putt1ck** [Zimbra-Community/owncloud-zimlet#206]
End users don't know what webdav is, and often the organisation deploying <webdav-enabled document management> will have branded it for their organisation in some way e.g. if deploying NextCloud they might brand it "CompanyCloud". 

It therefore makes sense to deploy the zimlet with the same brand. We can see how change the action items and zimlet entry by editing the config_template.xml, but that still leaves (at least) the help files. Again, can see how we mod those too, but it would be neat if there was a pre- or post-install script that took care of this sort of branding.

The challenge would be modding the images in help.

**Comment by putt1ck** [comment]
Related (can open a new RFE if makes sense): the button in the webdav tab that takes you to your <insert preferred webdav service here> is labelled Nextcloud

**Comment by barrydegraaff** [comment]
To rebrand this Zimlet, I usually git-clone this repo on the target server, and then I run 
nextcloud-labels.sh	or
nuxeo-labels.sh

This replaces WebDAV with Nextcloud or Nuxeo, and also sets a new icon.

The help pages, and button can be customized by setting them via
https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences

See:
owncloud_zimlet_extra_toolbar_button_title

**Comment by barrydegraaff** [comment]
And point owncloud_zimlet_welcome_url to a different set of help pages.

**Comment by barrydegraaff** [comment]
Thanks for your donation!
