### ISSUE TITLE
Unable to install with 8.8.12

### ISSUE THREAD

**Issue by Xaldimo** [Zimbra-Community/owncloud-zimlet#207]
When trying to install (upgrade) with Zimbra 8.8.12 (Debian 16.04) it fails:

    [javac] Compiling 152 source files to /tmp/webdav-client-installer.PAMMYXmG/owncloud-zimlet/extension/build                              
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 7                                                    
    [javac] /tmp/webdav-client-installer.PAMMYXmG/owncloud-zimlet/extension/src/com/github/sardine/DavAce.java:25: error: package javax.xml.bind.annotation does not exist                                                                                                                
    [javac] import javax.xml.bind.annotation.XmlRootElement;                                                                                 
    [javac]                                 ^                                                                                                
    [javac] /tmp/webdav-client-installer.PAMMYXmG/owncloud-zimlet/extension/src/com/github/sardine/model/Ace.java:3: error: package javax.xml.bind.annotation does not exist

Unfortunately it now has removed the existing deployment zimlet so have no fallback at this moment.

**Comment by barrydegraaff** [comment]
I can confirm this issue

**Comment by barrydegraaff** [comment]
It appears to be a change in the dependencies from Oracle Java
https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist

**Comment by barrydegraaff** [comment]
With added dependencies it builds, but does not run.

**Comment by barrydegraaff** [comment]
Should work now! Try again by re-downloading the installer and run it as per the readme.

**Comment by Xaldimo** [comment]
Yes that has resolved it :smiley:  Thank you
