### ISSUE TITLE
Cannot edit office document from zimlet

### ISSUE THREAD

**Issue by Qtechnetita** [Zimbra-Community/owncloud-zimlet#211]
Problem: 
Cannot edit office documents from owncloud-zimlet with Onlyoffice, just  preview them.

Infrastructure:
On-premise Zimbra server on Ubuntu 16.04.6 LTS: 8.8.12p2 Network Edition behind his Nginx reachable at a public IP/FQDN (NATted)

On-premise Nextcloud 16 on Ubuntu 16.04.06 LTS behind standard Nginx proxy and served by Apache and php7.3 reachable at a public IP/FQDN (NATted and different from the Zimbra one) with primary storage on a compatible S3 storage

On-premise Onlyoffice documentserver community edition (last version) on Nextcloud machine
reachable at a public IP/FQDN (NATted)

Note: 
Documents editing works as expected from Nextcloud webUI. 
APIurl is defined in config.properties and converted to xml in the owncloud-zimlet.
I took a look at mailbox log on Zimbra, Nginx/Apache on nextcloud/onlyoffice machine and nextcloud.log. It'seems (with my knowledge) there're no errors using the two editing UI.

How I can debug it deeper? Or there's some more trivial setting or switch to enable/disable editing?
Many thanks

**Comment by barrydegraaff** [comment]
Did you try, right clicking the file from the list and click edit?

**Comment by Qtechnetita** [comment]
Yes, that's it! It was definitively trivial...

**Comment by barrydegraaff** [comment]
Hello Alessandro, 

Thank you very much for your donation! 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

+31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
