### ISSUE TITLE
Can we translate your zimlet

### ISSUE THREAD

**Issue by webafrancois** [Zimbra-Community/owncloud-zimlet#213]
We are very interesting with your job and can translate it to some europeans languages like french (native tongue), spanish, german...
Is there come interface or .po somewhere ?

Thanks.

**Comment by barrydegraaff** [comment]
There is a french translation here:
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/tk_barrydegraaff_owncloud_zimlet_fr.properties

To update it, make a Github account, hit the fork button on the top of this
repo. Then in your own account, you can type the missing translations.

Make sure to convert each new translated string using Unicode conversion see: http://itpro.cz/juniconv/

Also, to see the translation, you must deploy the Zimlet using zmzimletctl deploy.
One way to do this is using the installer like so: /tmp/webdav-client-installer.sh --auto

**Comment by barrydegraaff** [comment]
For spanish and german on can add new files, copy-paste this file: 
[ https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/tk_barrydegraaff_owncloud_zimlet.properties | https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/tk_barrydegraaff_owncloud_zimlet.properties ] 

en put it here: 
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/tk_barrydegraaff_owncloud_zimlet_es.properties 
and 
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/tk_barrydegraaff_owncloud_zimlet_de.properties 

Let me know if that works for you. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
