### ISSUE TITLE
The trutAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by Emi94** [Zimbra-Community/owncloud-zimlet#215]
Hi, today I tried to access the webdav tab on zimbra and I got this error:
![Screenshot from 2019-06-24 13-55-11](https://user-images.githubusercontent.com/11816318/60027289-dfcc7700-96a5-11e9-89a8-3c8ed05c8602.png)

The connection to Nextcloud also seems to not work. It says "Loading..." where the folders/files list should be.

Here's the full error stack:

> 2019-06-24 12:27:36,746 WARN  [qtp1595953398-1407575:https:https://mail.domain.com/service/soap/davSoapConnector] [name=myuser@domain.com;mid=21;oip=12.34.56.78;port=57552;ua=ZimbraWebClient - GC73 (Linux)/8.8.6_GA_1906;] extensions - ZAL SOAP Unknown Exception: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
>         at sun.security.ssl.Alerts.getSSLException (Alerts.java:208)
>         at sun.security.ssl.SSLSocketImpl.fatal (SSLSocketImpl.java:1959)
>         at sun.security.ssl.SSLSocketImpl.fatal (SSLSocketImpl.java:1916)
>         at sun.security.ssl.SSLSocketImpl.handleException (SSLSocketImpl.java:1899)
>         at sun.security.ssl.SSLSocketImpl.startHandshake (SSLSocketImpl.java:1420)
>         at sun.security.ssl.SSLSocketImpl.startHandshake (SSLSocketImpl.java:1397)
>         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket (SSLConnectionSocketFactory.java:394)
>         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket (SSLConnectionSocketFactory.java:353)
>         at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect (DefaultHttpClientConnectionOperator.java:134)
>         at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect (PoolingHttpClientConnectionManager.java:353)
>         at org.apache.http.impl.execchain.MainClientExec.establishRoute (MainClientExec.java:380)
>         at org.apache.http.impl.execchain.MainClientExec.execute (MainClientExec.java:236)
>         at org.apache.http.impl.execchain.ProtocolExec.execute (ProtocolExec.java:184)
>         at org.apache.http.impl.execchain.RetryExec.execute (RetryExec.java:88)
>         at org.apache.http.impl.execchain.RedirectExec.execute (RedirectExec.java:110)
>         at org.apache.http.impl.client.InternalHttpClient.doExecute (InternalHttpClient.java:184)
>         at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:71)
>         at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:220)
>         at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:164)
>         at com.github.sardine.impl.SardineImpl.execute (SardineImpl.java:1074)
>         at com.github.sardine.impl.SardineImpl.execute (SardineImpl.java:1041)
>         at com.github.sardine.impl.SardineImpl.propfind (SardineImpl.java:446)
>         at com.github.sardine.impl.SardineImpl.propfind (SardineImpl.java:428)
>         at com.zextras.dav.DavSoapConnector.propfind (DavSoapConnector.java:214)
>         at com.zextras.dav.DavSOAPHandler.handleRequest (DavSOAPHandler.java:144)
>         at org.openzal.zal.soap.InternalDocumentHelper.handle (InternalDocumentHelper.java:75)
>         at org.openzal.zal.soap.InternalDocumentHandler.handle (InternalDocumentHandler.java:42)
>         at com.zimbra.soap.SoapEngine.dispatchRequest (SoapEngine.java:607)
>         at com.zimbra.soap.SoapEngine.dispatch (SoapEngine.java:460)
>         at com.zimbra.soap.SoapEngine.dispatch (SoapEngine.java:273)
>         at com.zimbra.soap.SoapServlet.doWork (SoapServlet.java:303)
>         at com.zimbra.soap.SoapServlet.doPost (SoapServlet.java:213)
>         at javax.servlet.http.HttpServlet.service (HttpServlet.java:707)
>         at com.zimbra.cs.servlet.ZimbraServlet.service (ZimbraServlet.java:206)
>         at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
>         at org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:821)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1685)
>         at com.zimbra.cs.servlet.CsrfFilter.doFilter (CsrfFilter.java:169)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.RequestStringFilter.doFilter (RequestStringFilter.java:54)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.SetHeaderFilter.doFilter (SetHeaderFilter.java:59)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter (ETagHeaderFilter.java:47)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter (ContextPathBasedThreadPoolBalancerFilter.java:107)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter (ZimbraQoSFilter.java:116)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter (ZimbraInvalidLoginFilter.java:131)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at org.eclipse.jetty.servlets.DoSFilter.doFilterChain (DoSFilter.java:473)
>         at org.eclipse.jetty.servlets.DoSFilter.doFilter (DoSFilter.java:318)
>         at org.eclipse.jetty.servlets.DoSFilter.doFilter (DoSFilter.java:288)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:581)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
>         at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:524)
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:226)
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1158)
>         at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:511)
>         at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:185)
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1090)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
>         at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:213)
>         at org.eclipse.jetty.server.handler.HandlerCollection.handle (HandlerCollection.java:109)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:119)
>         at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle (RewriteHandler.java:318)
>         at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle (GzipHandler.java:437)
>         at org.eclipse.jetty.server.handler.DebugHandler.handle (DebugHandler.java:84)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:119)
>         at org.eclipse.jetty.server.Server.handle (Server.java:517)
>         at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:306)
>         at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:242)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:261)
>         at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
>         at org.eclipse.jetty.io.ssl.SslConnection.onFillable (SslConnection.java:192)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:261)
>         at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
>         at org.eclipse.jetty.io.SelectChannelEndPoint$2.run (SelectChannelEndPoint.java:75)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun (ExecuteProduceConsume.java:213)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run (ExecuteProduceConsume.java:147)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:654)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run (QueuedThreadPool.java:572)
>         at java.lang.Thread.run (Thread.java:748)
> Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
>         at sun.security.validator.PKIXValidator.<init> (PKIXValidator.java:91)
>         at sun.security.validator.Validator.getInstance (Validator.java:179)
>         at sun.security.ssl.X509TrustManagerImpl.getValidator (X509TrustManagerImpl.java:312)
>         at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit (X509TrustManagerImpl.java:171)
>         at sun.security.ssl.X509TrustManagerImpl.checkTrusted (X509TrustManagerImpl.java:184)
>         at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted (X509TrustManagerImpl.java:124)
>         at sun.security.ssl.ClientHandshaker.serverCertificate (ClientHandshaker.java:1496)
>         at sun.security.ssl.ClientHandshaker.processMessage (ClientHandshaker.java:216)
>         at sun.security.ssl.Handshaker.processLoop (Handshaker.java:1026)
>         at sun.security.ssl.Handshaker.process_record (Handshaker.java:961)
>         at sun.security.ssl.SSLSocketImpl.readRecord (SSLSocketImpl.java:1072)
>         at sun.security.ssl.SSLSocketImpl.performInitialHandshake (SSLSocketImpl.java:1385)
>         at sun.security.ssl.SSLSocketImpl.startHandshake (SSLSocketImpl.java:1413)
>         at sun.security.ssl.SSLSocketImpl.startHandshake (SSLSocketImpl.java:1397)
>         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket (SSLConnectionSocketFactory.java:394)
>         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket (SSLConnectionSocketFactory.java:353)
>         at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect (DefaultHttpClientConnectionOperator.java:134)
>         at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect (PoolingHttpClientConnectionManager.java:353)
>         at org.apache.http.impl.execchain.MainClientExec.establishRoute (MainClientExec.java:380)
>         at org.apache.http.impl.execchain.MainClientExec.execute (MainClientExec.java:236)
>         at org.apache.http.impl.execchain.ProtocolExec.execute (ProtocolExec.java:184)
>         at org.apache.http.impl.execchain.RetryExec.execute (RetryExec.java:88)
>         at org.apache.http.impl.execchain.RedirectExec.execute (RedirectExec.java:110)
>         at org.apache.http.impl.client.InternalHttpClient.doExecute (InternalHttpClient.java:184)
>         at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:71)
>         at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:220)
>         at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:164)
>         at com.github.sardine.impl.SardineImpl.execute (SardineImpl.java:1074)
>         at com.github.sardine.impl.SardineImpl.execute (SardineImpl.java:1041)
>         at com.github.sardine.impl.SardineImpl.propfind (SardineImpl.java:446)
>         at com.github.sardine.impl.SardineImpl.propfind (SardineImpl.java:428)
>         at com.zextras.dav.DavSoapConnector.propfind (DavSoapConnector.java:214)
>         at com.zextras.dav.DavSOAPHandler.handleRequest (DavSOAPHandler.java:144)
>         at org.openzal.zal.soap.InternalDocumentHelper.handle (InternalDocumentHelper.java:75)
>         at org.openzal.zal.soap.InternalDocumentHandler.handle (InternalDocumentHandler.java:42)
>         at com.zimbra.soap.SoapEngine.dispatchRequest (SoapEngine.java:607)
>         at com.zimbra.soap.SoapEngine.dispatch (SoapEngine.java:460)
>         at com.zimbra.soap.SoapEngine.dispatch (SoapEngine.java:273)
>         at com.zimbra.soap.SoapServlet.doWork (SoapServlet.java:303)
>         at com.zimbra.soap.SoapServlet.doPost (SoapServlet.java:213)
>         at javax.servlet.http.HttpServlet.service (HttpServlet.java:707)
>         at com.zimbra.cs.servlet.ZimbraServlet.service (ZimbraServlet.java:206)
>         at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
>         at org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:821)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1685)
>         at com.zimbra.cs.servlet.CsrfFilter.doFilter (CsrfFilter.java:169)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.RequestStringFilter.doFilter (RequestStringFilter.java:54)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.SetHeaderFilter.doFilter (SetHeaderFilter.java:59)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter (ETagHeaderFilter.java:47)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter (ContextPathBasedThreadPoolBalancerFilter.java:107)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter (ZimbraQoSFilter.java:116)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ZimbraInvalidLoginFilter.doFilter (ZimbraInvalidLoginFilter.java:131)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at org.eclipse.jetty.servlets.DoSFilter.doFilterChain (DoSFilter.java:473)
>         at org.eclipse.jetty.servlets.DoSFilter.doFilter (DoSFilter.java:318)
>         at org.eclipse.jetty.servlets.DoSFilter.doFilter (DoSFilter.java:288)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:581)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
>         at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:524)
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:226)
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1158)
>         at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:511)
>         at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:185)
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1090)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
>         at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:213)
>         at org.eclipse.jetty.server.handler.HandlerCollection.handle (HandlerCollection.java:109)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:119)
>         at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle (RewriteHandler.java:318)
>         at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle (GzipHandler.java:437)
>         at org.eclipse.jetty.server.handler.DebugHandler.handle (DebugHandler.java:84)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:119)
>         at org.eclipse.jetty.server.Server.handle (Server.java:517)
>         at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:306)
>         at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:242)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:261)
>         at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
>         at org.eclipse.jetty.io.ssl.SslConnection.onFillable (SslConnection.java:192)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:261)
>         at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
>         at org.eclipse.jetty.io.SelectChannelEndPoint$2.run (SelectChannelEndPoint.java:75)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun (ExecuteProduceConsume.java:213)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run (ExecuteProduceConsume.java:147)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:654)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run (QueuedThreadPool.java:572)
>         at java.lang.Thread.run (Thread.java:748)
> Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
>         at java.security.cert.PKIXParameters.setTrustAnchors (PKIXParameters.java:200)
>         at java.security.cert.PKIXParameters.<init> (PKIXParameters.java:120)
>         at java.security.cert.PKIXBuilderParameters.<init> (PKIXBuilderParameters.java:104)
>         at sun.security.validator.PKIXValidator.<init> (PKIXValidator.java:89)
>         at sun.security.validator.Validator.getInstance (Validator.java:179)
>         at sun.security.ssl.X509TrustManagerImpl.getValidator (X509TrustManagerImpl.java:312)
>         at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit (X509TrustManagerImpl.java:171)
>         at sun.security.ssl.X509TrustManagerImpl.checkTrusted (X509TrustManagerImpl.java:184)
>         at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted (X509TrustManagerImpl.java:124)
>         at sun.security.ssl.ClientHandshaker.serverCertificate (ClientHandshaker.java:1496)
>         at sun.security.ssl.ClientHandshaker.processMessage (ClientHandshaker.java:216)
>         at sun.security.ssl.Handshaker.processLoop (Handshaker.java:1026)
>         at sun.security.ssl.Handshaker.process_record (Handshaker.java:961)
>         at sun.security.ssl.SSLSocketImpl.readRecord (SSLSocketImpl.java:1072)
>         at sun.security.ssl.SSLSocketImpl.performInitialHandshake (SSLSocketImpl.java:1385)
>         at sun.security.ssl.SSLSocketImpl.startHandshake (SSLSocketImpl.java:1413)
>         at sun.security.ssl.SSLSocketImpl.startHandshake (SSLSocketImpl.java:1397)
>         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket (SSLConnectionSocketFactory.java:394)
>         at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket (SSLConnectionSocketFactory.java:353)
>         at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect (DefaultHttpClientConnectionOperator.java:134)
>         at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect (PoolingHttpClientConnectionManager.java:353)
>         at org.apache.http.impl.execchain.MainClientExec.establishRoute (MainClientExec.java:380)
>         at org.apache.http.impl.execchain.MainClientExec.execute (MainClientExec.java:236)
>         at org.apache.http.impl.execchain.ProtocolExec.execute (ProtocolExec.java:184)
>         at org.apache.http.impl.execchain.RetryExec.execute (RetryExec.java:88)
>         at org.apache.http.impl.execchain.RedirectExec.execute (RedirectExec.java:110)
>         at org.apache.http.impl.client.InternalHttpClient.doExecute (InternalHttpClient.java:184)
>         at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:71)
>         at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:220)
>         at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:164)
>         at com.github.sardine.impl.SardineImpl.execute (SardineImpl.java:1074)
>         at com.github.sardine.impl.SardineImpl.execute (SardineImpl.java:1041)
>         at com.github.sardine.impl.SardineImpl.propfind (SardineImpl.java:446)
>         at com.github.sardine.impl.SardineImpl.propfind (SardineImpl.java:428)
>         at com.zextras.dav.DavSoapConnector.propfind (DavSoapConnector.java:214)
>         at com.zextras.dav.DavSOAPHandler.handleRequest (DavSOAPHandler.java:144)
>         at org.openzal.zal.soap.InternalDocumentHelper.handle (InternalDocumentHelper.java:75)
>         at org.openzal.zal.soap.InternalDocumentHandler.handle (InternalDocumentHandler.java:42)
>         at com.zimbra.soap.SoapEngine.dispatchRequest (SoapEngine.java:607)
>         at com.zimbra.soap.SoapEngine.dispatch (SoapEngine.java:460)
>         at com.zimbra.soap.SoapEngine.dispatch (SoapEngine.java:273)
>         at com.zimbra.soap.SoapServlet.doWork (SoapServlet.java:303)
>         at com.zimbra.soap.SoapServlet.doPost (SoapServlet.java:213)
>         at javax.servlet.http.HttpServlet.service (HttpServlet.java:707)
>         at com.zimbra.cs.servlet.ZimbraServlet.service (ZimbraServlet.java:206)
>         at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
>         at org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:821)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1685)
>         at com.zimbra.cs.servlet.CsrfFilter.doFilter (CsrfFilter.java:169)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.RequestStringFilter.doFilter (RequestStringFilter.java:54)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.SetHeaderFilter.doFilter (SetHeaderFilter.java:59)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ETagHeaderFilter.doFilter (ETagHeaderFilter.java:47)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter (ContextPathBasedThreadPoolBalancerFilter.java:107)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter (ZimbraQoSFilter.java:116)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at com.zimbra.ctty.server.Server.handle (Server.java:517)
>         at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:306)
>         at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:242)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:261)
>         at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
>         at org.eclipse.jetty.io.ssl.SslConnection.onFillable (SslConnection.java:192)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:261)
>         at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
>         at org.eclipse.jetty.io.SelectChannelEndPoint$2.run (SelectChannelEndPoint.java:75)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun (ExecuteProduceConsume.java:213)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run (ExecuteProduceConsume.java:147)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:654)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run (QueuedThreadPool.java:572)
>         at java.lang.Thread.run (Thread.java:748)s.servlet.ZimbraInvalidLoginFilter.doFilter (ZimbraInvalidLoginFilter.java:131)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at org.eclipse.jetty.servlets.DoSFilter.doFilterChain (DoSFilter.java:473)
>         at org.eclipse.jetty.servlets.DoSFilter.doFilter (DoSFilter.java:318)
>         at org.eclipse.jetty.servlets.DoSFilter.doFilter (DoSFilter.java:288)
>         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1668)
>         at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:581)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
>         at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:524)
>         at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:226)
>         at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1158)
>         at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:511)
>         at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:185)
>         at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1090)
>         at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
>         at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:213)
>         at org.eclipse.jetty.server.handler.HandlerCollection.handle (HandlerCollection.java:109)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:119)
>         at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle (RewriteHandler.java:318)
>         at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle (GzipHandler.java:437)
>         at org.eclipse.jetty.server.handler.DebugHandler.handle (DebugHandler.java:84)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:119)
>         at org.eclipse.jetty.server.Server.handle (Server.java:517)
>         at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:306)
>         at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:242)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:261)
>         at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
>         at org.eclipse.jetty.io.ssl.SslConnection.onFillable (SslConnection.java:192)
>         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:261)
>         at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:95)
>         at org.eclipse.jetty.io.SelectChannelEndPoint$2.run (SelectChannelEndPoint.java:75)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun (ExecuteProduceConsume.java:213)
>         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run (ExecuteProduceConsume.java:147)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:654)
>         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run (QueuedThreadPool.java:572)
>         at java.lang.Thread.run (Thread.java:748)

**Comment by barrydegraaff** [comment]
It is an SSL related error.

Make sure Zimbra connects to the correcr Nexctloud server. Try using curl from the commandline to your nextcloud server.

Restart Zimbra and Nextcloud apache.

Make sure the certificate is trusted, see the wiki on this github repo.

**Comment by Emi94** [comment]
Zimbra is setup to connect to the correct Nextcloud server and I can access it just fine from command line. The certificate is a valid one. The weird part is that Nextcloud doesn't even see the requests from zimbra. I'll try to restart zimbra tonight or tomorrow morning and see if that fixes something, but would be nice to find out what triggered this issue.

**Comment by barrydegraaff** [comment]
automatic updates enabled? 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by Emi94** [comment]
no

**Comment by barrydegraaff** [comment]
https://confluence.atlassian.com/jirakb/unable-to-access-ssl-services-due-to-java-security-invalidalgorithmparameterexception-218269293.html

Maybe an update in Zimbra cleaned out your java ssl keystore.

Mak sure to import your cert:
https://github.com/Zimbra-Community/owncloud-zimlet/wiki/Troubleshooting#suncertpathbuilderexception-unable-to-find-valid-certification-path-to-requested-target

Aka from the cli
openssl s_client -connect example.domain.com:443
copy paste the certificate into /tmp/a
/opt/zimbra/common/bin/keytool -import -alias example.com -keystore /opt/zimbra/common/etc/java/cacerts -storepass changeit -file /tmp/a

Restart zimbra

https://github.com/Zimbra-Community/owncloud-zimlet/wiki/Troubleshooting#suncertpathbuilderexception-unable-to-find-valid-certification-path-to-requested-target
