### ISSUE TITLE
First level indentation

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/owncloud-zimlet#216]
When choosing a target folder, there is no indentation difference between 1st and 2nd level folders. Append some pixels for the 2nd level so it is becomes a more visible tree.

**Comment by putt1ck** [comment]
Related: the indent is also missing when selecting an attachment for a new message via the zimlet.

**Comment by barrydegraaff** [comment]
has been fixed in 
[ https://github.com/Zimbra-Community/owncloud-zimlet/commit/d1d8c1db61ea5fb1dca76d8d59941ad2cf54bdc0 | https://github.com/Zimbra-Community/owncloud-zimlet/commit/d1d8c1db61ea5fb1dca76d8d59941ad2cf54bdc0 ] 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
