### ISSUE TITLE
"save to webdav" bugs

### ISSUE THREAD

**Issue by Emi94** [Zimbra-Community/owncloud-zimlet#217]
The 1.1.6 version says it allows to save a whole folder containing emails, contacts, etc. by right-click, but I can't see such an option.

Also, not sure if you plan on supporting the Opera browser. But when using it, if I select multiple emails and right-click, the "save to webdav" option is grayed out and I can't click it. Seems to work fine in Firefox and Chrome. I tried to do ctrl+f5 and restart the browser in case it was cached before upgrading the plugin.

**Comment by barrydegraaff** [comment]
Looks like a cache issue to me. Make sure to restart zimbra and close your browser, and then try using an incognito window. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by Emi94** [comment]
I already did that.

Note: the first problem with not being able to save a whole folder is happening on all browsers, even on ones that I never used to access zimbra until now, and still happens after I deleted all history/cache.

The second problem was indeed cache as it seems to work after I disabled the cache from the browser developer console.

**Comment by barrydegraaff** [comment]
It is only supported to save multiple items, selected via the mail list view, not entire folders from the folder pane. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by Emi94** [comment]
Well this phrase made me believe it could do that: "Enable right click "save to webdav" for **folders** and muliple email selections/briefcase/contacts"

**Comment by barrydegraaff** [comment]
That is a typo, sorry about that. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by Emi94** [comment]
Thanks for the quick answers.
