### ISSUE TITLE
New folder option reverts to root after creation

### ISSUE THREAD

**Issue by putt1ck** [Zimbra-Community/owncloud-zimlet#219]
Scenario: email received with attachments related to a new potential project. Receiver wants to file in new project folder. They navigate to the projects folder and create the new project folder and then want to save the attachment or create a subfolder for the attachments

Outcome: the folder picker returns to the root folder, requiring the user to navigate back through to the newly created folder before creating the subfolder or saving the items.

Expected behaviour: the folder picker opens the new folder after creation.

**Comment by barrydegraaff** [comment]
fixed
