### ISSUE TITLE
Can't Upload file 

### ISSUE THREAD

**Issue by tanguy-opendsi** [Zimbra-Community/owncloud-zimlet#221]
Hi we have 8.8.11 zimbra  and zimlet 1.1.0
We got error 500 when we upload files to nextcloud. 

Export error : 
"response": {
          "status": 500,
          "statusText": "Server Error",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Server",
              "value": "nginx"
            },
            {
              "name": "Date",
              "value": "Thu, 18 Jul 2019 10:28:26 GMT"
            },
            {
              "name": "Content-Type",
              "value": "text/html;charset=iso-8859-1"
            },
            {
              "name": "Content-Length",
              "value": "267"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Cache-Control",
              "value": "must-revalidate,no-cache,no-store"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html; charset=iso-8859-1",
            "size": 267,
            "text": "<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>\n<title>Error 500 Server Error</title>\n</head>\n<body><h2>HTTP ERROR 500</h2>\n<p>Problem accessing /service/extension/dav_upload/. Reason:\n<pre>    Server Error</pre></p>\n</body>\n</html>\n"
          },
          "redirectURL": "",
          "headersSize": 220,
          "bodySize": 487
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 1291,
          "wait": 60,
          "receive": 0
        },
        "time": 1351,
        "_securityState": "secure",
        "serverIPAddress": "XXXXXX",
        "connection": "443"
      },
      {
        "pageref": "page_1",
        "startedDateTime": "2019-07-18T12:28:33.876+02:00",
        "request": {
          "bodySize": 576,
          "method": "POST",
          "url": "https://XXXXX/service/soap/ZxChatRequest",
          "httpVersion": "",
          "headers": [
            {
              "name": "Host",
              "value": "XXXXX.fr"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "Referer",
              "value": "https://XXXXX.fr/"
            },
            {
              "name": "Content-Type",
              "value": "application/soap+xml; charset=utf-8"
            },
            {
              "name": "Content-Length",
              "value": "576"
            },
            {
              "name": "Cookie",
              "value": "ZM_TEST=true; ZM_AUTH_TOKEN=0_a161a9049dd83f148b8a7688c520c195aaf8ee22_69643d33363a36373264386536322d663732372d346165622d626366322d3362663464613266376337653b6578703d31333a313536333631383336373530313b76763d313a303b747970653d363a7a696d6272613b753d313a613b7469643d393a3538343336313336343b76657273696f6e3d31343a382e382e31315f47415f333733373b637372663d313a313b; JSESSIONID=19muvrbra5rgvx0nxaeypelc0"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            }
          ],
          "cookies": [
            {
              "name": "ZM_TEST",
              "value": "true"
            },
            {
              "name": "ZM_AUTH_TOKEN",
              "value": "0_a161a9049dd83f148b8a7688c520c195aaf8ee22_69643d33363a36373264386536322d663732372d346165622d626366322d3362663464613266376337653b6578703d31333a313536333631383336373530313b76763d313a303b747970653d363a7a696d6272613b753d313a613b7469643d393a3538343336313336343b76657273696f6e3d31343a382e382e31315f47415f333733373b637372663d313a313b"
            },
            {
              "name": "JSESSIONID",
              "value": "19muvrbra5rgvx0nxaeypelc0"
            }
          ],

**Comment by barrydegraaff** [comment]
Can you run (while try and upload)

     tail -f /opt/zimbra/log/mailbox.log 
     tail -f /opt/zimbra/log/zmmailboxd.out

and copy paste the result here, perhaps it is an 8.8.11 issue, as officially I do not support it.

**Comment by tanguy-opendsi** [comment]
Here you haves logs :
[zimbra@dczistore01 ~]$  tail -f /opt/zimbra/log/mailbox.log | grep user@xx.xx
2019-07-22 12:04:41,455 INFO  [qtp1286783232-87491:http://courriels.xx.xx/service/soap/davSoapConnector] [name=user@xx.xx;mid=127;oip=10.134.0.115, 192.168.81.2;port=46720;ua=ZimbraWebClient - GC75 (Win)/8.8.11_GA_3787;soapId=678ce7e9;] soap - davSoapConnector elapsed=633
2019-07-22 12:04:50,968 INFO  [qtp1286783232-87984:http://courriels.xx.xx/service/soap/davSoapConnector] [name=user@xx.xx;mid=127;oip=10.134.0.115, 192.168.81.2;port=48434;ua=ZimbraWebClient - GC75 (Win)/8.8.11_GA_3787;soapId=678ce858;] soap - davSoapConnector elapsed=608

[zimbra@dczistore01 log]$  tail -f /opt/zimbra/log/zmmailboxd.out | grep user@xx.xx
java.lang.RuntimeException: DAV Data connection not set for user 'user@xx.xx'
best regards

**Comment by barrydegraaff** [comment]
It means that your settings are incomplete, you must enter correct connection settings.

In the left bottom of the mail view in Zimbra under Zimlets, click WebDAV and configure the
connection.

https://raw.githubusercontent.com/Zimbra-Community/owncloud-zimlet/soapServiceBarry/docs/Nextcloud-prefs.png

**Comment by tanguy-opendsi** [comment]
The problem is here : 
We can download, list Nextcloud documents but we can't download.

Best regards

**Comment by barrydegraaff** [comment]
Can you send me a test account?
