### ISSUE TITLE
DAV  Error 403

### ISSUE THREAD

**Issue by cshardey** [Zimbra-Community/owncloud-zimlet#222]
Great work Sir this app is great.
My zimlet is currently connected to alfresco 5.2. I was able to connect and everything was working fine until I recently started encountering this error "403 forbidden" anytime I try connecting from zimbra . Kindly advise

**Comment by barrydegraaff** [comment]
ddos throttle or something?

**Comment by cshardey** [comment]
No, please. My WebDAV URL can be accessed from the browser. I'm able to browse my file using the WebDAV URL in my browser.

**Comment by barrydegraaff** [comment]
Probably a configuration issue, but with the information provided I cannot know what the issue is.

Make sure to put the / -slashes exactly as in the readme.md
