### ISSUE TITLE
CollaboraOnline integration

### ISSUE THREAD

**Issue by KlugFR** [Zimbra-Community/owncloud-zimlet#223]
Hello.

This zimlet is able to "access" OnlyOffice when it's integrated in NextCloud (that allows to modify documents from ZWC directly).

Would it be possible to do the same thing with CollaboraOnline (integrated in NextCloud too)?

**Comment by barrydegraaff** [comment]
No it does not. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by KlugFR** [comment]
That's unfortunate.

I'm quite happy with OnlyOffice (it's neat) but many users would like to be able to LOOL.
Mostly because they're using LO on their desktops and switched to ODF and don't want the double conversion OnlyOffice is doing.
And because they're using it from NextCloud already.

**Comment by barrydegraaff** [comment]
Yes it is legacy, we have onlyoffice as that was stable before LOOL was. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
