### ISSUE TITLE
How to change from Dev to Production mode

### ISSUE THREAD

**Issue by WizWareTech** [Zimbra-Community/owncloud-zimlet#224]
Forgive my lack of knowledge, but I did not see it listed in the documentation. Can you tell me how to move zimlet from _dev to production? I tried moving the folders out of _dev up a level, but that did not work.

And if you can add that to the instructions, that may help others.

**Comment by barrydegraaff** [comment]
Re-run the installer and when asked: 
echo "" 
echo "There are two ways you can deploy the Zimlet" 
echo "You can have the installer do `zmzimletctl deploy`, this way you can enable/disable the Zimlet per user/cos." 
echo "Or you can have the installer install the Zimlet to /opt/zimbra/zimlets-deployed/_dev that way you will have" 
echo "less cache issues on updates of the Zimlet and it is also easier if you want to rebrand the Zimlet." 
echo "" 
echo "Do you want to deploy to /opt/zimbra/zimlets-deployed/_dev ? " 
echo "If you have trouble or are unsure, choose Y. Y/n:" 

Select N and then follow the instructions. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by WizWareTech** [comment]
Thank you so much, sir. I’m sorry I missed that! After I have re-branded, is there any way to move to production without re-install? 

 

 

Mark Cook

President / CEO

WizWare Technologies, Inc.

 

303-225-3277, Ext 122

www.WizWareTech.com <http://www.wizwaretech.com/>

**Comment by barrydegraaff** [comment]
yeah by removing the corresponding zimlets fronm /opt/zimbra/zimlets-deployed/_dev/
