### ISSUE TITLE
File extensions

### ISSUE THREAD

**Issue by iPontch** [Zimbra-Community/owncloud-zimlet#227]
Some users send attachments with extensions like *.DOCX or *.XLSX, instead of  *.docx or *.xlsx and docconverter can't convert them. How to fix it?

Thnx.

**Comment by barrydegraaff** [comment]
pushed a fix for this issue, re-run the installer to make it work.

Alternatively you can:
wget https://github.com/Zimbra-Community/owncloud-zimlet/raw/soapServiceBarry/docconvert/extension/out/artifacts/DocConvert/DocConvert.jar -O /opt/zimbra/lib/ext/DocConvert/DocConvert.jar

And restart mailbox

**Comment by iPontch** [comment]
Yes!!! Working! Thnx!
