### ISSUE TITLE
OnlyOffice - Windows AD

### ISSUE THREAD

**Issue by javito1081** [Zimbra-Community/owncloud-zimlet#228]
Hi again Barry :-)

   Jesus christ it seems that u do a lot of apps for Zimbra, everytime i see a usefull app, ur involved in it hehe.

   But to go into the topic, iv been using ZimbraDrive so far without issued, my ZimbraMail Domains are connected to my local Windows AD, and as well connected to my Nextcloud Server which is also authenticating through my Windows AD, the reason why im considering to change to this Zimlet is cause i read with this zimlet i can preview and edit documents with OnlyOffice inside the same Zimbra interface and also see my External Drives, which i have setup on my Nextcloud Server for my network SMB folders, my concern is that if ur Zimlet can automatically authenticate users with their Domain User/Pass instead of having each user setup manually their Nextcloud user/pass/folders.

   Also, i saw on a website that the WebDAV name in top can be changed to Nextcloud name or whatever we want, but in ur demo video the WebDAV tab at the top is never renamed, so i wonder if that was a feature in old versions or if thats still a thing how do we do that?

   That would be all :-)

Thanks in advance. 

Note: here https://raw.githubusercontent.com/Zimbra-Community/owncloud-zimlet/soapServiceBarry/docs/Nextcloud-tab.png is shown as Nextcloud instead of WebDAV

**Comment by barrydegraaff** [comment]
Hello,

The re-branding works, and also it has been set to Nextcloud by default
and in also includes the Nextcloud logo. So no worries there.

We do not support the auto-login/passing of credentials.

So each user would to at least set their password or passcode at least
once.

However, this is done via a user friendly pop-up so if you provision
all the default settings correctly, users only need to type their
password in the password dialog. It has been made easy.

Barry

**Comment by javito1081** [comment]
Tyvm for u quick response as usual barry, ill test it a bit today, have a great day :-)
