### ISSUE TITLE
Nextcloud Zimlet not yet compatible with Zimbra 8.8.15 patch 5

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/owncloud-zimlet#229]
Hello All,

Just to let you know, Zeta Alliance Nextcloud Zimlet  does not work yet with the
next patch for Zimbra.

Upon upgrading you will see a Network Service Error.

To make you web interface reachable again, remove openzal:
rm /opt/zimbra/lib/ext/ownCloud/zal.jar
and restart mailbox.

There seems to be some incompatibility with the current zal release and
the one in Nextcloud Zimlet. I hope to fix it soon .

Kind regards,

Barry de Graaff
Zeta Alliance
Co-founder & Developer
zetalliance.org | github.com/Zimbra-Community

**Comment by barrydegraaff** [comment]
Temporary unofficial work-around from the Zeta Alliance mailing list:

it's the new openjdk ( 13.0.1-zimbra )  , I fixed the problem  with by copying the old one (11.0.2-zimbra)  and : 

unlink /opt/zimbra/common/lib/jvm/java
 ln -s /opt/zimbra/common/lib/jvm/openjdk-11.0.2-zimbra /opt/zimbra/common/lib/jvm/java

**Comment by barrydegraaff** [comment]
If anyone wants this jdk please reply here.

**Comment by barrydegraaff** [comment]
New fix, install updated zal.jar

     wget https://github.com/Zimbra-Community/owncloud-zimlet/raw/soapServiceBarry/extension/lib/zal.jar -O /opt/zimbra/lib/ext/ownCloud/zal.jar
      su zimbra
      zmmailboxdctl restart

**Comment by npocToTeHb** [comment]
Hi,Barry! You do the great zimlet!
Please help with translate your zimlet to Russian interface.
I edited this file in zimlet folder - tk_barrydegraaff_owncloud_zimlet.properties.
Changed all properties to Russian and save them in UTF 8.
Then restarted zimbra, and have text in wrong codepage  in  zimlet part of web interface.
What i do wrong?

**Comment by ASTIN-UA** [comment]
Hi. Have same problem. Use Zimbra 8.7.11. Cn you help me?

**Comment by barrydegraaff** [comment]
@ASTIN-UA sorry 8.7 is not supported anymore.

**Comment by ASTIN-UA** [comment]
Oh... No one chance? I can't update now. It's working corporate server...

**Comment by barrydegraaff** [comment]
End of general support for this Zimbra version, but the Zimlet has dropped support for older releases much sooner:
https://www.zimbra.com/support/support-offerings/product-lifecycle/

Anyways, you can probably rerun the installer and change:

      OWNCLOUD_ZIMLET_CLONE_BRANCH="soapServiceBarry"

to

      OWNCLOUD_ZIMLET_CLONE_BRANCH="1.4.0"


If that does not work, change this line manually:

      git clone --depth=1 -b ${OWNCLOUD_ZIMLET_CLONE_BRANCH} ${OWNCLOUD_ZIMLET_CLONE_URL}


Maybe the 1.4.0 still works on 8.7, but I am not sure, as I have not looked at that release for a long time. So maybe you need to trial and error a couple times to find the last working release for your version of Zimbra.

**Comment by Kevin7744** [comment]
I have the same issue as i try to login to the the web interface, however when i check the /opt/zimbra/... directory. I cant find the ownCloud dir that contains the zal.jar file.how do i go about this. 
The problem started when i upgraded to zimbra 8.8.15.
