### ISSUE TITLE
Interface translation to Russian language

### ISSUE THREAD

**Issue by npocToTeHb** [Zimbra-Community/owncloud-zimlet#230]
Hi,Barry! You do the great zimlet!
Please help with translate your zimlet to Russian interface.
I edited this file in zimlet folder - tk_barrydegraaff_owncloud_zimlet.properties.
Changed all properties to Russian and save them in UTF8.
Then restarted zimbra, and have text in wrong codepage in zimlet part of web interface.
What i do wrong?

**Comment by barrydegraaff** [comment]
We must create a new file called tk_barrydegraaff_owncloud_zimlet_ru.properties, you can start by making a copy of tk_barrydegraaff_owncloud_zimlet.properties.

And you must encode your strings using:
http://itpro.cz/juniconv/

An example of what the end result looks like is here:
https://github.com/Zimbra-Community/pgp-zimlet/blob/stable/tk_barrydegraaff_zimbra_openpgp/tk_barrydegraaff_zimbra_openpgp_ru.properties

If you do not know how git works, you can also make the file and copy paste it here, then I will commit it for you.

**Comment by npocToTeHb** [comment]
Ok, thanks alot! It works good now!)

**Comment by barrydegraaff** [comment]
please share your translation!!

**Comment by npocToTeHb** [comment]
that's my translated file
[tk_barrydegraaff_owncloud_zimlet_ru.zip](https://github.com/Zimbra-Community/owncloud-zimlet/files/3988270/tk_barrydegraaff_owncloud_zimlet_ru.zip)
