### ISSUE TITLE
Owncloud Zimlet changes to NextCloud

### ISSUE THREAD

**Issue by aptpupil303** [Zimbra-Community/owncloud-zimlet#232]
When I run the auto installer the script updates the OwnCloud Zimlet to Nextcloud. The current version of the zimlet is 0.2.1. and Owncloud is on 10.3.1.

**Comment by barrydegraaff** [comment]
yes the default changed some time ago, you can set the owncloud_zimlet_app_title using the 
[ https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences | https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences ]
