### ISSUE TITLE
"could not create share"

### ISSUE THREAD

**Issue by malinkalive** [Zimbra-Community/owncloud-zimlet#234]
Hi, 
first of all thank you for this usefull zimlet. It is nice to working with. Few weeks ago I have installed "Release 8.8.15.GA.3869.UBUNTU18.64 UBUNTU18_64 FOSS edition, Patch 8.8.15_P7." and owncloud-zimlet 1.4.1 version. Everythink works fine except "sharing file as public link". When I`m trying create public share action ends with "could not create share" message. My production server URL is https://**nextcloud**.example.pl. When I`m trying to wget https://zimbra.example.pl/nextcloud/ I get 404 Error. I did not found usefull information in "/opt/zimbra/log/mailbox.log and nginx.access.log". Can You help me find where the problem is?

**Comment by barrydegraaff** [comment]
Maybe you set it up a long time ago? 

[ https://zimbra.example.pl/nextcloud/ | https://zimbra.example.pl/nextcloud/ ] 
That usually means there is a proxy in front of Zimbra OR a custom Zimbra proxy config that proxies nextcloud to be in the same 
domain as your Zimbra. 

Not recommended anymore, but you may have done this in the past: 
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/wiki/Serving%20Nextcloud%20ownCloud%20behind%20Zimbra's%20nginx.md 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by malinkalive** [comment]
I have created fresh environment without proxy settings. But my problem is still the same. Do you have commercial support?

**Comment by barrydegraaff** [comment]
not at this time, did you check the proxy settings as in my previous comment?

**Comment by malinkalive** [comment]
Sure I have checked with proxy settings delivered by you and without it. It`s probably some misconfiguration on my site but I can`t find it out.

**Comment by rosegarde** [comment]
I have the following problem when i was send a filelink from nextcloud

![image](https://user-images.githubusercontent.com/63907087/79636944-ad7f8f00-817b-11ea-9727-45753ec31f91.png)

![image](https://user-images.githubusercontent.com/63907087/79636742-241b8d00-817a-11ea-84c7-1953e44f83f0.png)

after i press ok this errormessage apears 

![image](https://user-images.githubusercontent.com/63907087/79636809-c2a7ee00-817a-11ea-92eb-f3831fe62e96.png)

All other things will work fine. i can send a file as attachment and i see all folders and files in the nextcloud window. If i send a file as attachment the mail-window comes up and i can send the the mail.

And this is my nextcloud configuration windows
![image](https://user-images.githubusercontent.com/63907087/79636875-4bbf2500-817b-11ea-85be-027fcad1045e.png)

what can i do to make it work? is there some wrong configuration ?

**Comment by rosegarde** [comment]
I forgot to say, i am using zimbra 8.8.15 and nextcloud 18.0

**Comment by mbaldazzi85** [comment]
Hi rosegarde,
Have you tried to remove nextcloud After /? In the connection settings? 
I mean leave / in ort owncloud/nextcloud field

**Comment by rosegarde** [comment]
hi mbaldazzi85,
perfect, that it was. now it work  :-)
thanks for your quick answer
