### ISSUE TITLE
onlyoffice editing is not working

### ISSUE THREAD

**Issue by balin777** [Zimbra-Community/owncloud-zimlet#235]
hi! i am in panic now. 
i install zimlet, and write in  /opt/zimbra/lib/ext/ownCloud/config.properties URL OnlyOffice api. 
And it s not working! Just not run jnlyoffice in Zimbra interface. 
It s my config.properties file:
owncloud_zimlet_oc_folder=/nextcloud
owncloud_zimlet_max_upload_size=104857600
owncloud_zimlet_welcome_url=https\://barrydegraaff.github.io/owncloud/
encryption_password_secret=zsue11sI8vq9PL5m8ursXq1o
allowdomains=*
owncloud_zimlet_enable_onlyoffice=true
owncloud_zimlet_extra_toolbar_button_title=Go to Nextcloud
owncloud_zimlet_extra_toolbar_button_url=owncloud_zimlet_oc_folder
enable_seafile_patches=true
owncloud_zimlet_disable_auto_upload_on_exceed=false
owncloud_zimlet_disable_ocs_public_link_shares=false
db_connect_string=jdbc\:mariadb\://127.0.0.1\:7306/onlyoffice_db?user\=ad-onlyoffice_db&password\=E11DGCHIW6
encryption_salt_secret=JrVt1KPTSIYR2HrK2UFMwsRW
owncloud_zimlet_server_name=http\://cloud.call-service.ru\:80
owncloud_zimlet_accountname_with_domain=false
owncloud_zimlet_disable_rename_delete_new_folder=false
owncloud_zimlet_server_port=80
owncloud_zimlet_onlyoffice_api_url=http\://10.203.60.32\:80/web-apps/apps/api/documents/api.js
owncloud_zimlet_server_path=/remote.php/webdav/
owncloud_zimlet_onlyoffice_secret=uAxyo6ba58tAjhTGswdQ
disable_password_storing=false
owncloud_zimlet_app_title=Cloud
owncloud_zimlet_disable_eml_export=false

What i m doing wrong?

**Comment by barrydegraaff** [comment]
It cannot work over HTTP, YOU MUST USE HTTPS with proper certificates. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by balin777** [comment]
thnx, i try use https.
