### ISSUE TITLE
Server or network failed

### ISSUE THREAD

**Issue by balin777** [Zimbra-Community/owncloud-zimlet#236]
![image](https://user-images.githubusercontent.com/41673679/77065751-557a2f00-69fb-11ea-8e22-5c94bf7ca36f.png)
Hi!

After install and start zimlet i see this message in video files, and the other file type does not open either.. 
What i m doing wrong?

**Comment by barrydegraaff** [comment]
the mp4 playback is pretty broken, I will remove it in a next release. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by balin777** [comment]
![image](https://user-images.githubusercontent.com/41673679/77067070-c6bae180-69fd-11ea-8ec6-c3a11754404b.png)
![image](https://user-images.githubusercontent.com/41673679/77067435-624c5200-69fe-11ea-95f2-e1898d3805e9.png)
The other file type does not open either.
Nothing happens when you click on the "Download file" button.

**Comment by balin777** [comment]
It s Nextcloud trouble. Thx.
