### ISSUE TITLE
Add support for "document server community" for Onlyoffice

### ISSUE THREAD

**Issue by alexdaums** [Zimbra-Community/owncloud-zimlet#237]
Hello, and first sorry for my bad english.

I installed my Nextcloud server with the official script: [https://github.com/nextcloud/vm](https://github.com/nextcloud/vm)
This script also allows you to preconfigure some applications like Onlyoffice.
Some time ago it was using a docker container. But since version 18.0.2 of Nextcloud it uses this application: [https://apps.nextcloud.com/apps/documentserver_community](https://apps.nextcloud.com/apps/documentserver_community).
Can you add support for this zimlet.

Thank you for your great work!

**Comment by barrydegraaff** [comment]
Hello Alex,

The documentserver_community does not really add anything special, if it can be reached as regular onlyoffice document server, you can configure Zimbra to use that.

Otherwiser you can set one up as you did using Docker:
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/wiki/OnlyOffice%20Nextcloud.md

In any case the number of users remains limited to the community edition limit and it is not in the scope of this project to add a whole onlyoffice document server.
