### ISSUE TITLE
The localization file is not processed

### ISSUE THREAD

**Issue by AlexandrKrupnik** [Zimbra-Community/owncloud-zimlet#241]
Hello!
The localization file tk_barrydegraaff_owncloud_zimlet_ru.properties is not used for some reason. The tk_barrydegraaff_owncloud_zimlet.properties file too - using hardcoded phrases from k_barrydegraaff_owncloud_zimlet.js (for example now method this.getMessage('useOwncloudDlgLabel1'); return "???useOwncloudDlgLabel1???")
How do I enable the use of a localization file so that all text is translated?

**Comment by barrydegraaff** [comment]
run the installer like so:

      /tmp/webdav-client-installer.sh --auto
