### ISSUE TITLE
An error occurred while initializing the zimlet 

### ISSUE THREAD

**Issue by gaborabraham** [Zimbra-Community/owncloud-zimlet#242]
Hi,

I got the following error message when I enable your zimlet in COS:
![error](https://user-images.githubusercontent.com/64774338/80957391-54625d00-8e03-11ea-9bfb-6f9c047f71bc.png)

Here's what I did before the error message appeared:
- installed your zimlet the "easy way" (directly to the zimlets-deployed/_dev folder)
- configured and tested it with an account. All worked well. (I've a few suggestions, but it's another story)
- realized that zimlet - with the easy way install - can't be managed with COS
- uninstalled the zimlet according to the readme.md file "Un-installing (For both production and development mode)" section
- reinstalled the zimlet in production mode
- enable zimlet for the account
- run into the error message

Thing I tried so far:
- found a similar issue "Impossible to initialize zimlet #153"
- reinstall zimlet in production mode
- flush cache with zmprov fc all several times
- restart zmmailboxdctl, zmcontrol, and even the whole zimbra server
- delete browser cache

Nothing helped!
It only works if I start with /?dev=1 

Additional info:
Zimbra version: Zimbra 8.8.15_GA_3928 (build 20200415072015)
Zimlet version: 1.4.1
No other 3rd party zimlets in use

Do you have any idea?
Can you try reproduce the issue with the above steps? (install dev mode, uninstall, install prod mode)
I can also provide you a zimbra account on my server with the zimlet enabled, if you prefer.

Regards,
Gabor

**Comment by barrydegraaff** [comment]
try incognito mode, try on a new zimbra account, it is always a cache issue.

Do you have other zimlets deployed? Are they all up to date?
