### ISSUE TITLE
Could not create share

### ISSUE THREAD

**Issue by starxpert** [Zimbra-Community/owncloud-zimlet#250]
**Hi there is an issue when trying to share files:**
**Owncloud:** 10.2.1.4
{"reqId":"d44EIDpLnZH2N7ZKx0ol","level":3,"time":"2020-07-16T10:15:42+00:00","remoteAddr":"172.16.42.5","user":"--","app":"index","method":"POST","url":"\/nextcloud\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/nextcloud\\\/ocs\\\/v1.php\\\/apps\\\/files_sharing\\\/api\\\/v1\\\/shares) cannot be processed by the script '\\\/apps\\\/files_')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(858): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":659}"}

**If we work this around then:**
\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/1b302d22-7d22-1039-95fb-1b0f0adf3357\/","message":"token cb2bb657b1a8a61b9e521c6eb7e2d0c9164e8a72858722615f2189af6a528fb39319890ef6dd070c270b48dc8cdd09f48f5db36de6de26d4c0459fbf43b4b209 does not exist"}

**Using SSO**

**On Nextcloud:** Same with logs

{"reqId":"XxBf1AJFc8sz3VC6T9sX2QAAAAA","level":0,"time":"July 16, 2020 14:10:28","remoteAddr":"217.108.54.85","user":"--","app":"core","method":"GET","url":"/lzcloud/ocs/v1.php/apps/files_sharing/api/v1/shares","message":{"Exception":"OC\\AppFramework\\Middleware\\Security\\Exceptions\\NotLoggedInException","Message":"Current user is not logged in","Code":401,"Trace":[{"file":"/var/www/html/lzcloud/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","line":97,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\Security\\SecurityMiddleware","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"getShares"]},{"file":"/var/www/html/lzcloud/lib/private/AppFramework/Http/Dispatcher.php","line":97,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"getShares"]},{"file":"/var/www/html/lzcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"getShares"]},{"file":"/var/www/html/lzcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareAPIController","getShares",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files_sharing.ShareAPI.getShares"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"ocs.files_sharing.ShareAPI.getShares"}]},{"file":"/var/www/html/lzcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"ocs.files_sharing.ShareAPI.getShares"}]},{"file":"/var/www/html/lzcloud/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/files_sharing/api/v1/shares"]}],"File":"/var/www/html/lzcloud/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php","Line":142,"CustomMessage":"--"},"userAgent":"Java/13.0.1","version":"18.0.7.1"}

{"reqId":"XxBf1CQgZLb5JVU5swqhSQAAAAs","level":0,"time":"July 16, 2020 14:10:28","remoteAddr":"217.108.54.85","user":"--","app":"no app in context","method":"GET","url":"/lzcloud/login?redirect_url=/lzcloud/ocs/v1.php/apps/files_sharing/api/v1/shares","message":"Deprecated event type for OCA\\User_LDAP\\User\\User::postLDAPBackendAdded: null","userAgent":"Java/13.0.1","version":"18.0.7.1"}

{"reqId":"XxBf4QH5@iaVWPGIbs1wjAAAAAI","level":0,"time":"July 16, 2020 14:10:41","remoteAddr":"217.108.54.85","user":"slebreto","app":"no app in context","method":"PROPFIND","url":"/lzcloud/remote.php/dav/files/slebreto/","message":"Deprecated event type for OCA\\User_LDAP\\User\\User::postLDAPBackendAdded: null","userAgent":"Mozilla/5.0 (Macintosh) mirall/2.6.5stable (build 20200710) (Nextcloud)","version":"18.0.7.1"}

 

{"reqId":"XxBf4wH5@iaVWPGIbs1wjQAAAAI","level":0,"time":"July 16, 2020 14:10:43","remoteAddr":"217.108.54.85","user":"slebreto","app":"no app in context","method":"GET","url":"/lzcloud/ocs/v2.php/core/navigation/apps?absolute=true&format=json","message":"Deprecated event type for OCA\\User_LDAP\\User\\User::postLDAPBackendAdded: null","userAgent":"Mozilla/5.0 (Macintosh) mirall/2.6.5stable (build 20200710) (Nextcloud)","version":"18.0.7.1"}

 

![Capture d’écran du 2020-07-16 17-37-29](https://user-images.githubusercontent.com/11029307/87691638-1b435300-c78b-11ea-97ac-baf3c6501220.png)
![Capture d’écran du 2020-07-16 17-36-43](https://user-images.githubusercontent.com/11029307/87691645-1c748000-c78b-11ea-8838-897c54335399.png)

**Thanks,**

**Comment by barrydegraaff** [comment]
I can confirm this issue, it is probably because of an update to the Nextcloud OCS api.

**Comment by barrydegraaff** [comment]
In my case there was a misconfiguration in the settings, one too many slash. Please share a screenshot of your nextcloud zimlet settings dialog.

**Comment by starxpert** [comment]
![copie ecran](https://user-images.githubusercontent.com/11029307/88382889-b0f16a80-cda9-11ea-98ea-37a981ee701b.png)

Hi
Remove last slash from davpath does bnot change a thing

**Comment by starxpert** [comment]
Hi,

Any News ?

Regards
