### ISSUE TITLE
NC18 can't login whit zimbra crediential

### ISSUE THREAD

**Issue by mbaldazzi85** [Zimbra-Community/owncloud-zimlet#253]
Hello everyone,
after updating nextcloud to the latest version 18 (18.0.9) I can no longer login with zimbra credentials.
Did I miss something? 

For Zimbra & NC use Ubuntu16 the app is 0.8.25 and it's compliant with NC18.
Zimbra is the 8.8.15_P14 version

this is the plug-in in zimbra 
![immagine](https://user-images.githubusercontent.com/45855548/95061025-58204580-06fb-11eb-93e9-ec76681a6700.png)

**Comment by barrydegraaff** [comment]
The Zimbra app in Nextcloud is not a part of this Zimlet.

This Zimlet does not require an App installed on the Nextcloud side, please check the readme.
