### ISSUE TITLE
Problem with search inside the zimlet

### ISSUE THREAD

**Issue by camilosanz-720tec** [Zimbra-Community/owncloud-zimlet#255]
Hello,

We cannot do any search from the zimlet search bar. It throws this error: DAV error unexpected response (404 not found).

Attached is the related log from the mailbox.log.

We have uninstalled and installed again with the same result. We also test the two modes for the installation. 

Please, can you help me?

Best regards,
Camilo.
[mailbox.log](https://github.com/Zimbra-Community/owncloud-zimlet/files/5492932/mailbox.log)

**Comment by barrydegraaff** [comment]
are you using nextcloud or owncloud?

**Comment by camilosanz-720tec** [comment]
We are using nextcloud.

Sent from my mobile



Camilo Sanz
Servicios y proyectos
964066964 - Directo: 964 066 962
https://www.720tec.es
-------- Mensaje original --------
De: Barry de Graaff <notifications@github.com>
Fecha: jue., 5 nov. 2020 9:28
Para: Zimbra-Community/owncloud-zimlet <owncloud-zimlet@noreply.github.com>
Cc: Camilo Sanz - 720tec <csanz@720tec.es>, Author <author@noreply.github.com>
Asunto: Re: [Zimbra-Community/owncloud-zimlet] Problem with search inside the zimlet (#255)

are you using nextcloud or owncloud?

**Comment by barrydegraaff** [comment]
version number?

**Comment by camilosanz-720tec** [comment]
Hello!

Zimbra version 8.8.15 on Red Hat 7
Nextcloud version 16.0.0 on Red Hat 7.

Regards.


Camilo Sanz
Servicios y proyectos
964066964 - Directo: 964 066 962
https://www.720tec.es
De: Barry de Graaff <notifications@github.com>
Enviado el: jueves, 5 de noviembre de 2020 9:32
Para: Zimbra-Community/owncloud-zimlet <owncloud-zimlet@noreply.github.com>
CC: Camilo Sanz - 720tec <csanz@720tec.es>; Author <author@noreply.github.com>
Asunto: Re: [Zimbra-Community/owncloud-zimlet] Problem with search inside the zimlet (#255)

version number?

**Comment by barrydegraaff** [comment]
This is probably an issue in Nextcloud, the error message is misleading.

This error happens if your database collation is not correct.

Try:

   'mysql.utf8mb4' => false,

in config.php and try again.


Also you are running a very old version, upgrade is recommended.

**Comment by camilosanz-720tec** [comment]
Hello,

Using this parameter did not solve the problem…)-: We can try to upgrade, but is complicated right now.

Regards.


Camilo Sanz
Servicios y proyectos
964066964 - Directo: 964 066 962
https://www.720tec.es
De: Barry de Graaff <notifications@github.com>
Enviado el: jueves, 5 de noviembre de 2020 11:16
Para: Zimbra-Community/owncloud-zimlet <owncloud-zimlet@noreply.github.com>
CC: Camilo Sanz - 720tec <csanz@720tec.es>; Author <author@noreply.github.com>
Asunto: Re: [Zimbra-Community/owncloud-zimlet] Problem with search inside the zimlet (#255)

This is probably an issue in Nextcloud, the error message is misleading.

This error happens if your database collation is not correct.

Try:

  'mysql.utf8mb4' => false,

in config.php and try again.


Also you are running a very old version, upgrade is recommended.

**Comment by camilosanz-720tec** [comment]
We have upgraded to Nextcloud version 19.0.4, but the error is the same. Any clue?


Camilo Sanz
Servicios y proyectos
964066964 - Directo: 964 066 962
https://www.720tec.es
De: Barry de Graaff <notifications@github.com>
Enviado el: jueves, 5 de noviembre de 2020 11:16
Para: Zimbra-Community/owncloud-zimlet <owncloud-zimlet@noreply.github.com>
CC: Camilo Sanz - 720tec <csanz@720tec.es>; Author <author@noreply.github.com>
Asunto: Re: [Zimbra-Community/owncloud-zimlet] Problem with search inside the zimlet (#255)

This is probably an issue in Nextcloud, the error message is misleading.

This error happens if your database collation is not correct.

Try:

  'mysql.utf8mb4' => false,

in config.php and try again.


Also you are running a very old version, upgrade is recommended.

**Comment by barrydegraaff** [comment]
This is most likely an issue in your nextcloud server, I have tested on Nextcloud 20 and it just works.
