### ISSUE TITLE
Placeholders appeared in zimlet window

### ISSUE THREAD

**Issue by xjobex** [Zimbra-Community/owncloud-zimlet#256]
Hi, recently I installed the latest patch on my Zimbra server, from 8.8.15 P6 to P 15. I also upgraded ownlcloud zimlet using the the installer without problems. The zimlet works normally, but I noticed that now in the zimlet window there are some placeholders (es. ???attachFrom???, ???attachFileFolder???) instead of normal labels. 
Here is a screenshot:
![image](https://user-images.githubusercontent.com/6407955/100897595-212e9c00-34c0-11eb-8a53-cd0017d70528.png)

I tried changing zimbra interface language but the problem persists. Is there a way to have normal labels back?

**Comment by barrydegraaff** [comment]
This should be fixed now,re-run the installer

**Comment by xjobex** [comment]
Thanks Barry, I updated the zimlet today and I confirm that the problem is solved.
