### ISSUE TITLE
There are no enabled repos.  Ubuntu 18.04 error

### ISSUE THREAD

**Issue by vahlerus** [Zimbra-Community/owncloud-zimlet#257]
While installation on Ubuntu 18.04 there is an error in the end both with 
/tmp/webdav-client-installer.sh 
and 
/tmp/webdav-client-installer.sh --auto

"There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>"

Any idea?

**Comment by barrydegraaff** [comment]
No clue, just ran the installer on ubunnut 18.04 and it went just fine.
