### ISSUE TITLE
Public link sharing stopped working in Zimbra 8.8.15 Patch 17 and OwnCloud 10.6.0

### ISSUE THREAD

**Issue by DiegoIRPI** [Zimbra-Community/owncloud-zimlet#258]
Hi!
First of all, thank you very much for your great work on this Zimlet.
We used it successfully until the last updates (see title) and, after applying them, we encountered the following issue.
While sharing a public link for a file correctly hosted inside our OwnCloud instance, the browser returns the error "Could not create share" and, using the Firefox web console (shift+ ctrl + k) it says (translated from our language):
"Error: request failed with status 404 resource URL: https://<OUR_MAIL_SYSTEM>/service/zimlet/_dev/tk_barrydegraaff_owncloud_zimlet/markdown/purify.js?v=201103051731&language=it&country=IT&debug=1 origin URL mapping: purify.js.map".
Moreover (but is less important), we noticed that after a previous Zimbra update (I do not remember exactly wich one), all labels that were translated in our language (italian) are now "placeholder names" preceded and followed by "???".
We already tried uninstalling and re-installing the Zimlet but nothing has changed.
Have you any idea about those issues?
Thanks in advance,
    Diego

**Comment by DiegoIRPI** [comment]
With further investigations, we discovered that the issue related to the "Could not create share" appered after the upgrade of OwnCloud from 10.5 to 10.6 and is not related to the Zimbra version (so with Zimbra 8.8.15 Patch 17 and OwnCloud 10.5 the publink link sharing works while with Zimbra 8.8.15 Patch 17 and OwnCloud 10.6 it doesn't).
Anyway, the problem of the translation still persist, with both versions of OwnCloud.
Any suggestion about a fix for both problems?

**Comment by barrydegraaff** [comment]
The OCS API has changed in Nextcloud and Owncloud and need to be updated here for it to work. Nothing you can do about it.

For the translations, please download a copy of this:
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/tk_barrydegraaff_owncloud_zimlet.properties

Translate all to Italian and upload it back here, so I can add it to the Zimlet, thanks!

**Comment by barrydegraaff** [comment]
for public link sharing to work you must enable `File sharing` app and disable password policy (if needed). Public links tested and work on Nextcloud 20 using this Zimlet.

**Comment by DiegoIRPI** [comment]
Thank you for your reply.
We will stick to the working 10.5 until a new Zimlet supporting the new API will be released: no problem for us since that instance of OwnCloud is dedicated exclusively to Zimbra sharing.
Concerning the translation you requested, you can find it here - https://github.com/Zimbra-Community/owncloud-zimlet/files/5878821/italian_translation.txt
Thanks again,
    Diego

**Comment by barrydegraaff** [comment]
Disregard the comment on the public link sharing not working.

I have verified this Zimlet works with Nextcloud 20. You must enable File sharing app and disable password policy (if needed) to use public link creation from Zimbra.

Also thanks for the translation, it has been added to the Zimlet. Re-run the installer to get the last version. Thanks!
