### ISSUE TITLE
default owncloud_zimlet_welcome_url is missing

### ISSUE THREAD

**Issue by stefan0xC** [Zimbra-Community/owncloud-zimlet#260]
I just noticed that https://barrydegraaff.github.io/owncloud/ (the default value of owncloud_zimlet_welcome_url) does not exist anymore.
Is there a way to display the version that is included in the zimlet? C.f. [zimlet/help/index.html](/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/zimlet/help/index.html)

**Comment by barrydegraaff** [comment]
Yes by setting owncloud_zimlet_welcome_url

via 
https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences

**Comment by barrydegraaff** [comment]
The documentation URL is moved to https://zetalliance.org/owncloud-zimlet/
