### ISSUE TITLE
3 minor problems: (1) Italian translation, (2) opening of help into a frame and (3) nextcloud error reporting

### ISSUE THREAD

**Issue by DiegoIRPI** [Zimbra-Community/owncloud-zimlet#261]
Hi,
as the title says, I have to report 3 minor problems.
 - (1) Italian translation
I saw you added to Github the Italian translation I sent to you some time ago (https://github.com/Zimbra-Community/owncloud-zimlet/commit/df8829a0dfce96da497695796560132c1c977a69) but, after re-installing the Zimlet, it seems to use another translation file, where different Italian strings are present and some text is still in English (i.e.: in "_Connection settings_" there is the text "_If checked, the password is stored in plain text in Zimbra LDAP. If not checked you have to provide password for each session_" instead of what you can see in line 28 "passwordStoredComment" of the previous file; moreover, the Owncloud/Nextcloud path is translated as "_Luogo ownCloud/Nextcloud_" instead of what you can see on line 43 - "_Percorso ownCloud/Nextcloud_"). It is possible that it is not using the right translation file?
 - (2) Opening of help into a frame
When opening the "Nextcloud" tab into the Zimbra webmail, the right-most panel shows an error (that happens with all browsers I've tested) saying that those contents (https://zetalliance.org/owncloud-zimlet/) cannot be shown into a frame due to author decision. I think this appeared after you moved to Zetalliance from Github, but I'm not sure about it. Is something you can fix in any way?
 - (3) Nextcloud error reporting
We noticed that, if you upload a file to Nextcloud from the Zimlet and you run out of space, the upload process stops but no error is shown to the user. It is possible to warn the user that the file has not been uploaded (as it happens with the Nextcloud/owncloud web interface, where it says that you cannot upload a file greater than your remaining free space)? Saying nothing, in that case, has confused some of our users...
Thanks in advance!

**Comment by barrydegraaff** [comment]
2. Fixed the server headers, should work now!

1. To use the correct translation you must deploy the zimlet via 
zmzimletctl deploy, so when you run the installer and this question 
comes up:
/There are two ways you can deploy the Zimlet"//
//You can have the installer do zmzimletctl deploy, this way you can 
enable/disable the Zimlet per user/cos."//
//Or you can have the installer install the Zimlet to 
/opt/zimbra/zimlets-deployed/_dev that way you will have"//
//less cache issues on updates of the Zimlet and it is also easier if 
you want to rebrand the Zimlet."//
//
//Do you want to deploy to /opt/zimbra/zimlets-deployed/_dev ? "//
//If you have trouble or are unsure, choose Y. Y/n:"/

Select N

3. There are currently no plans to implement it.
