### ISSUE TITLE
Permission denied for some users changing preferences

### ISSUE THREAD

**Issue by alepaes1975** [Zimbra-Community/owncloud-zimlet#270]
Hi !

![image](https://user-images.githubusercontent.com/67766108/123690227-8534fb00-d82a-11eb-9d87-0380060ed457.png)

For some users, when I try to edit prefrerences of Nextcloud Zimlet, Zimbra show a permission denied.

Best regards,

Alexandre

**Comment by barrydegraaff** [comment]
I would need to see the server logs to know what the issue can be, try and disable browser extensions.
