### ISSUE TITLE
Onlyoffice edit should be available by default

### ISSUE THREAD

**Issue by adriangibanelbtactic** [Zimbra-Community/owncloud-zimlet#271]
In our deployment we expect OnlyOffice document editing to be on by default.

So that means:
https://github.com/Zimbra-Community/owncloud-zimlet/blob/f524fba12cbd04bbc6df47431b9cd4ae15c9177f/webdav-client-installer.sh#L98-L107

where:
```
    YNONLYOFFICE="N"
```
is turned on to:
```
    YNONLYOFFICE="Y"
```
.

Do you think OnlyOffice document editing is mature enough to turn it on by default when installing in an automatic way?
I might send a pull request later if your answer is true. There is no problem about it.

**Comment by barrydegraaff** [comment]
There is many people that do not want OnlyOffice for performance or security reasons, some do not want to use it... but enabling it is fine by me!
