### ISSUE TITLE
How to use a proxy between zimbra and nextcloud

### ISSUE THREAD

**Issue by castejonc** [Zimbra-Community/owncloud-zimlet#273]
Hello,

We have to use a proxy to communicate from our mailstore server to the nextcloud server. Is it possible to configure owncloud-zimlet to force the use of a proxy?

Zimbra version: 9.0.0
Nextcloud: 20.012

Thanks

**Comment by barrydegraaff** [comment]
Yes you need to make sure that you set `allowdomains` and only allow your proxy:

https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences

You can set the proxy domain in `/etc/hosts` on the Zimbra server in case it is not in DNS, you may need to install Dnsmasq if Zimbra cannot resolve your proxy.
