### ISSUE TITLE
RFE: Remove intermediate mysql database

### ISSUE THREAD

**Issue by adriangibanelbtactic** [Zimbra-Community/owncloud-zimlet#277]
I believe we can remove the intermediate mysql which it's only needed for onlyoffice editing.

`Path`, `filekey` and `file` content can be delivered by the onlyoffice server which can receive them as parametres.

The rest of parametres (`owncloud_zimlet_server_path`, `owncloud_zimlet_username`, `owncloud_zimlet_server_name`, `owncloud_zimlet_server_port`, `owncloud_zimlet_password` and `owncloud_zimlet_oc_folder`) can be fetched from the zimbra account zimlet properties.

My question is: Was this extra database design an additional security measure (so that the filekey parametre already existed in the database)?

Thank you.

**Comment by barrydegraaff** [comment]
I added it as a way to make sure the server knows how to save the document even if the client disappears.
