### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by uhlhosting** [Zimbra-Community/owncloud-zimlet#278]
Will this work with Nextcloud 22 and newer? + Zimbra 9 OSE.

**Comment by vhostvn** [comment]
This is zimlet for webdav service, does not depend on nextcloud version. If you nextcloud can support webdav then it works perfectly.

Zimbra 9 and Nextcloud 23 is supported.

**Comment by barrydegraaff** [comment]
Yes this is maintained and works with latest Nextcloud and Zimbra OSE
