### ISSUE TITLE
License changed from GNU GPLv3 to GNU GPLv2 (less restricted) 

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/owncloud-zimlet#34]
@EmailConsortium
@manens 
@maxxer 
@nnachit 
@pbruna 
@zerlgi 
@ZeXtras

Recently I changed the license for owncloud Zimlet from GNU GPLv3, to GNU GPLv2, less restricted, but more importantly more compatible with upstream Zimbra.

You (may) have contributed a few lines of code under the old license, in case you object to this change, please update this issue, so we can remove your code.

Thanks, Barry

**Comment by tuanta** [comment]
It's fine for me. Thanks!

**Comment by maxxer** [comment]
no probl
