### ISSUE TITLE
404 on file zcs.php

### ISSUE THREAD

**Issue by largouwalid** [Zimbra-Community/owncloud-zimlet#35]
Hi,
I'm trying to integrate Owncloud with Zimbra, here is my configuration : 
- First VM with Zimbra (@ : 192.168.1.5) on Centos 7
- Second VM with Owncloud (@ : 192.168.1.7) on Centos 7

I installed the owncloud-zimlet and configured Owncloud to be accessed on the same ip as : 192.168.1.5/owncloud
On zimbra i can access owncloud from the owncloud tab. (it works fine)
I have a problem when i try to attach a file on a mail, on the front end i check the file i want to attach and i get a popup asking for user/pwd (which is not normal) and when i inspect the javascript i've found a call this link "/owncloud/ocs/zcs.php?proxy_location=/owncloud&zcsuser=admin&zcspass=owncloudpass00&path=getshares"
which results to 404 (because there is no file called zcs.php.

Thank you in advance, i'm very interested in your project and would like to contribute in the near future, you can contact me directly with : largouwalid@gmail.com

**Comment by tuanta** [comment]
Did you follow the whole installation process described in README?
You should consider steps in "Configure your ownCloud Server".

**Comment by barrydegraaff** [comment]
For fresh ownCloud installs I recommend to use the official repository. If you do a fresh install of ownCloud, please finalize the installation via the Zimbra proxied url, this will add your Zimbra domain to the list of trusted domains in ownCloud and will avoid unwanted http auth prompts to show up in Zimbra.

If you get an ERROR 404 or you don't see ownCloud see https://github.com/Zimbra-Community/owncloud-zimlet/wiki/Install-and-enable-Zimbra-Proxy

If you want to enable link sharing add a php file to you ownCloud installation:

[root@owncloud1 ~]# cd /var/www/html/owncloud/ocs/
[root@owncloud1 ~]# rm -Rf zcs.php
[root@owncloud1 ~]# wget https://raw.githubusercontent.com/Zimbra-Community/owncloud-zimlet/master/php/zcs.php

**Comment by largouwalid** [comment]
Thank you both for the answer, indeed this error was related with the link sharing. But it isn't the main problem. On the zimbra main page, when i see the console (on chrome) , i find this error (see file Method Not Allowed) : 

MKCOL https://192.168.1;105/owncloud/remote.php/webdav//Documents 405 (Method Not Allowed) 

When i open this link in another tab i get a prompt asking for user/pass for my owncloud account and when i enter it i see the documents (see file Access link.png). 

Is this problem related to CORS ? 

Thank you.

**Comment by barrydegraaff** [comment]
405 is a normal error, just means the Zimlet tries to create a folder that already exists.
It is also normal that you cannot open that webpage using your browser in a normalGET request. So visiting that url in a browser you use HTTP GET protocol, but the Zimlet uses HTTP MKCOL.... so that is not the issue.
Also, as you proxy owncloud now, there should be no cross-site javascript errors.

**Comment by barrydegraaff** [comment]
If you still get http password prompts, those are usually configuration issues in apache/httpd.
Did you install owncloud from the repo? What OS are you on? If all else fails, reinstall and:finalize the installation via the Zimbra proxied url, this will add your Zimbra domain to the list of trusted domains in ownCloud and will avoid unwanted http auth prompts to show up in Zimbra.
Also, for a small donation, I can set up your ownCloud server on CentOS 7.

Barry
