### ISSUE TITLE
E-mail and own cloud log-in issue

### ISSUE THREAD

**Issue by zkryakgul** [Zimbra-Community/owncloud-zimlet#38]
Hello, once you login to owncloud over zimbra then log-out from zibra without loging-out from owncloud, it brings the same owncloud account on your next log-in. This triggers a security issue.

For example: Once I log-in with 'asmith' user to zimbra and log-in to owncloud with 'asmith' account, then logout from 'asimith' zimbra without logging-out from owncloud. Next time when I log-in to zimbra with a different account like 'cbolder', the owncloud comes with previous log-in account already logged-in which is 'asimith' in this case. The user logs-in to zimbra with 'cbolder' account and owncloud comes already open with 'asmith' account.

I hope it was explained well.

Bests

**Comment by barrydegraaff** [comment]
To avoid this, please see the wiki page on single sign on.

https://github.com/Zimbra-Community/owncloud-zimlet/wiki/Zimbra-and-ownCloud-Single-Sign-On-SSO
