### ISSUE TITLE
Test Zimlet with ownCloud 9

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/owncloud-zimlet#47]
Test Zimlet with ownCloud 9

ownCloud is now also using DAV for the UI so, lets see if somethings got broken.

**Comment by barrydegraaff** [comment]
Seems like the webdav response of ownCloud 9 is not correctly parsed by the zimlet, so it needs some work.

**Comment by barrydegraaff** [comment]
The webdav response in ownCloud9 is the same, but someone decided to apply spaces and indenting. (not very usefull if you ask me)

Replacing this:
if(response.indexOf('<d:resourcetype><d:collection/>') > -1)
 with:
if(response.indexOf('<d:collection/>') > -1)

And 90% of the features will return, and I guess this also works for 8.0 so needs some dev time.

**Comment by MNL-dick** [comment]
HI Barry,
I upgraded my ownCloud to 9.0 and since then can not add a owncloud file to my mail. 
I do not see anything at all.

I downloaded and installed the latest version from GitHub, but still.

How can I check if the change you mention is pushed through?

Other things seem to work like before.

Kindest regards,
Dick Muller

**Comment by barrydegraaff** [comment]
Its probably a cache issue, reboot your Zimbra server and flush your browser cache.

**Comment by MNL-dick** [comment]
HI Barry,

Reboot the zimbra server and my browser. Even after using another type of browser it still doesn't work.
In the Attach from ownCloud window nothing is shown, it is completely empty.

Do you have other suggestion?

**Comment by barrydegraaff** [comment]
press f12 to open the browser console. Reload the screen and see what is in the console and network tab, use Google Chrome or Firefox to test.

**Comment by MNL-dick** [comment]
Hi Barry,

Did this and it shows two errors in the below screendump.

![image](https://cloud.githubusercontent.com/assets/15033822/14081874/27f34600-f50d-11e5-92b0-38853859c361.png)

**Comment by barrydegraaff** [comment]
try to append : ?dev=1 to the url of your zimbra:


https://myzimbra.com/?dev=1

**Comment by MNL-dick** [comment]
OK, did that. 
It restarted zimbra in the window. Again tried to add an attachment, but still no luck.

In the debug screen I see the same errors as before.

**Comment by barrydegraaff** [comment]
Ok now click on the url in the error, tk_barryde... and then click again, to see what line in the code has the error

**Comment by MNL-dick** [comment]
That gives the following result
![image](https://cloud.githubusercontent.com/assets/15033822/14082163/bc606b32-f50e-11e5-95da-a632176e5243.png)

**Comment by MNL-dick** [comment]
The uncought type error refer to the following lines in the script.
868
861
502

Is this usefull?

**Comment by barrydegraaff** [comment]
now click on the @tk_barryd... link, that should show you the code, I need to see that.

**Comment by MNL-dick** [comment]
This is for the first line:
![image](https://cloud.githubusercontent.com/assets/15033822/14082326/b1fb95da-f50f-11e5-8ccb-36514f1d15e3.png)

**Comment by MNL-dick** [comment]
This is for the third line:
![image](https://cloud.githubusercontent.com/assets/15033822/14082338/ce4d661e-f50f-11e5-9a16-997725be2558.png)

**Comment by barrydegraaff** [comment]
That is a cache issue 100% as line 868 you are showing is of version 0.3.3 and NOT 0.4.0

On your server do 
zmprov fc all
zmcontrol restart

And make 100% sure you have updated the zimlet files in /opt/zimbra/zimlets-deployed/_dev

If needed, remove the 
rm -Rf /opt/zimbra/zimlets-deployed/_dev/tk_barrydegraaff_owncloud_zimlet/

Also remove your git clone, and try again, you are now still using the older version that does not work with oc9

**Comment by MNL-dick** [comment]
Hi Barry,

I did it all. I removed the zimlet, and the git directory and installed it from scratch, like you explain in the readme.
Still I have the same problem. 
Is there a way to check  the version after I do a checkout of version 0.4.0

**Comment by MNL-dick** [comment]
I followed you code changes and in the zimlet directory I see a xml file that says I"m using version 0.4.0

I now rebooted the zimbra server to be sure, but I do not understand this.

**Comment by barrydegraaff** [comment]
Yes, but it may not be reliable, you can open the ownCloud tab... the version number is in the top there.

Zimbra cache issues are a pain... maybe try a different account. 

I that also does not work, wait for 24 hours, and try again

**Comment by MNL-dick** [comment]
Didn't think of that, but yes, it shows version 0.4.0 on the ownCloud tab.
But.... it still doesn't work.

So the best thing for now is to wait for 24 hours and try again.

OK, I will see if it works tomorrow and will let you know.

For know, thanks for your great help. And I really like this zimlet. thanks for that.

**Comment by barrydegraaff** [comment]
Also remove all your browser temporary files, before you try again

**Comment by MNL-dick** [comment]
Hi Barry,

Just did that and it now works.
Just restarting the browser was probably not enough.

Thanks for you help.

**Comment by barrydegraaff** [comment]
@MNL-dick and others, I get these kinds of issues reported a lot, also via email. So in case you ever want to support my projects, remember where you got free support.

You can make donations via the below ways, thank you for you consideration and thank you for using ownCloud Zimlet.

PayPal: info@barrydegraaff.tk
Bank transfer: IBAN NL55ABNA0623226413 ; BIC ABNANL2A
