### ISSUE TITLE
ownCloud root path

### ISSUE THREAD

**Issue by kubut3k** [Zimbra-Community/owncloud-zimlet#49]
hi
we have 2 servers:
mail.example.com with configured proxy_pass mail.example.com/owncloud to second server cloud.example.com
on owncloud instance we don't use subdirectory
when we're accessing to mail.example.com/owncloud
we get https://mail.example.com/owncloud/index.php/apps/files/
but no static files going to load
in source file we get for example:
<link rel="stylesheet" href="/core/css/styles.css?v=331c790dcf506edf887a1c5dcd7748d4" media="screen">
pointing to: https://mail.example.com/core/css/styles.css
instead https://mail.example.com/owncloud/core/css/style.css

**Comment by barrydegraaff** [comment]
On the root is not possible in this release:
https://github.com/Zimbra-Community/owncloud-zimlet/wiki/ownCloud-in-a-different-location
