### ISSUE TITLE
Visualization Issues

### ISSUE THREAD

**Issue by robbyd2** [Zimbra-Community/owncloud-zimlet#50]
Hi,
awesome plugin for Owncloud. 

I got visualisation issues when I go to owncloud tab, basically a blank blue box has been visualised. 

Another question, is possible to change Owncloud Name ? 
<img width="588" alt="screen shot 2016-04-29 at 10 25 45" src="https://cloud.githubusercontent.com/assets/18264994/14911300/dc00e4a4-0df4-11e6-8f59-3b75673542c3.png">

**Comment by barrydegraaff** [comment]
Please make sure you download and install the latest version, 0.4.1 and run zmprov fc all as user Zimbra on the server.

Remove your browser cache.

And then most likely your owncloud is configured on a different domain (open .htaccess or apache configuration and remove the x-frame or sameorigin header there)

For more info, press F12 in your browser while loading the tab... you should see an error there.

**Comment by robbyd2** [comment]
How can upgrade it?

**Comment by maxxer** [comment]
https://github.com/Zimbra-Community/owncloud-zimlet/wiki#install-the-owncloud-zimlet

**Comment by robbyd2** [comment]
ok thanks!

I cannot attach from Owncloud as link, I got following error:

*Not Found*

The requested URL /drive/ocs/zcs.php was not found on this server.

Is this issue caused by owncloud or zimbra ?

**Comment by maxxer** [comment]
Did you follow **all** the instructions? Specifically **[this](https://github.com/Zimbra-Community/owncloud-zimlet/wiki#configure-your-owncloud-server)** step which mentions your, guess what, *zcs.php*?

**Comment by robbyd2** [comment]
Hi,
sorry I've lost that piece of commands :)

Right now I have blink link attached in the email. Only "I uploaded some
files that you can access with the following links: " without link.
