### ISSUE TITLE
Use zimbra's credential to log in to owncloud

### ISSUE THREAD

**Issue by tigre-bleu** [Zimbra-Community/owncloud-zimlet#51]
My owncloud instance uses the LDAP from Zimbra to authenticate users. The credentials are then exactly the same in owncloud and zimbra.

It is therefore a little strange to have to configure the zimlet with the same credentials as the zimbra account which is already connected.

Is it possible to add an admin option to autoconfigure the zimlet in order to use the credential from zimbra?

**Comment by maxxer** [comment]
Isn't the [SSO guide](https://github.com/Zimbra-Community/owncloud-zimlet/wiki/Zimbra-and-ownCloud-Single-Sign-On-SSO) suitable for your setup?

**Comment by barrydegraaff** [comment]
The suggestion above, or wait for us to fix pre auth for ownCloud. Its on our todo
