### ISSUE TITLE
HTTP ERROR 502  Problem accessing ZCS upstream server

### ISSUE THREAD

**Issue by AmineSaidi** [Zimbra-Community/owncloud-zimlet#54]
Hello i have my owncloud running on 
192.168.1.17/owncloud and the zimbra is running on 192.168.1.111 i've followed this tutorial for installing the zimlet but i get this error when i try to open this URL ;
https://192.168.1.111/owncloud 
i get the following error 
Problem accessing ZCS upstream server. Cannot connect to the ZCS upstream server. Connection is refused.
Possible reasons:

upstream server is unreachable
upstream server is currently being upgraded
upstream server is down
Please contact your ZCS administrator to fix the problem.

Note i have zimbra proxy running and when i tape netstat -tulpn | grep :443 I get the following response 

(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:443             0.0.0.0:*              LISTEN      6703/nginx: worker
please help me . thank's 
![capture](https://cloud.githubusercontent.com/assets/19797986/15857160/1bdad52e-2cba-11e6-8c92-419f67b5c8aa.PNG)

**Comment by barrydegraaff** [comment]
Looks like you forgot some steps in the readme:
https://github.com/Zimbra-Community/owncloud-zimlet#configure-your-zimbra-server

Please read all of the readme, and then it should work.
