### ISSUE TITLE
ZCS.php

### ISSUE THREAD

**Issue by richardyeardley** [Zimbra-Community/owncloud-zimlet#55]
I am impressed by the video showing the zimlet working.
I installed the zimlet and can now attach files from owncloud
But attaching a link splatters html code into the new mail being created
Also when clicking on the owncloud link for the 1st time (at the top bar ) nothing
happens for about 10 seconds and then it requests an owncloud login ( with a sabre/dav message )
and when dragging an item over to the owncloud zimlet on the left-hand it doesnt update the owncloud
folder. I installed the /ocs/zcs.php and wonder if it needs any changes making and if so are there any
examples.
Nice work Barry

**Comment by barrydegraaff** [comment]
Maybe you can try and install the NEW Zimbra WebDAV Client http://zimbra.org/extend/items/view/zimbra-webdav-client
