### ISSUE TITLE
The problem with the Cyrillic alphabet

### ISSUE THREAD

**Issue by shlange** [Zimbra-Community/owncloud-zimlet#57]
Hello,

I really like your zimlet, but I can't use it fully. 
The zimlet does not attaches to and does not create links for files in the owncloud with Cyrillic characters.

```
zcs# locale
LANG=ru_RU.UTF-8
LANGUAGE=
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```

![attach](https://cloud.githubusercontent.com/assets/20700879/17237790/fb7acd6a-556e-11e6-9a62-11b22a6e0aad.jpg)
![ie](https://cloud.githubusercontent.com/assets/20700879/17237788/fb6256ae-556e-11e6-86c7-17eaf55cfbe8.jpg)
![mf](https://cloud.githubusercontent.com/assets/20700879/17237789/fb629862-556e-11e6-92f4-918eddb3f83e.jpg)

**Comment by barrydegraaff** [comment]
Hello,

While the Zimlet was tested with UTF-8 clients, it was not tested on a ZCS running on a server in a different language.

Maybe you can check:
http://zimbra.org/extend/items/view/zimbra-webdav-client
https://www.youtube.com/watch?v=8pVMoXkNt8c

In the mean time, it will take me a few weeks to look into this, thanks for reporting. Barry

**Comment by barrydegraaff** [comment]
As it looks now, I will not be updating the old ownCloud Zimlet, and focus all development on WebDAV Client. Please let me know if that works out for you.
