### ISSUE TITLE
Create folder ?

### ISSUE THREAD

**Issue by sematuszewski** [Zimbra-Community/owncloud-zimlet#66]
How to create a folder via zimlet?

**Comment by barrydegraaff** [comment]
Thanks for noticing, it seems we forgot to add that.

Right now you can create the default folder (using the settings dialog).

I will add a menu item and a button for creating folders later.

**Comment by sematuszewski** [comment]
Thanks ;)

**Comment by barrydegraaff** [comment]
Added menu option to create folders... works the same as for briefcase.
https://github.com/Zimbra-Community/owncloud-zimlet/commit/ba382eb630a19e9c3f547e294d1cc545b3317a57

However there is no top-level menu, so one cannot create folders in /, I probably add a toolbar button for that.

**Comment by barrydegraaff** [comment]
Just added the button, problems should be fixed.
