### ISSUE TITLE
cannot SHARE non-english filename AS LINK

### ISSUE THREAD

**Issue by leo-yip** [Zimbra-Community/owncloud-zimlet#69]
cannot attach non-english filename,

when attach as link, it show undefined: 
![image](https://cloud.githubusercontent.com/assets/19850742/18009087/5ec81d62-6bdd-11e6-9249-3c5f36f2079a.png)

when attach as file , it keep loading 
![image](https://cloud.githubusercontent.com/assets/19850742/18009141/9dd8d6b8-6bdd-11e6-926f-bb056c52b788.png)

**Comment by barrydegraaff** [comment]
I fixed a related issue, now, you can attach the file as attachment... but not links yet.

**Comment by barrydegraaff** [comment]
I took a few hours debugging, it seems like java does a good request to ownCloud, only the share api returns invalid url.

I checked against the old ownCloud Zimlet (that is php/curl based), and it does NOT work there either.

ownCloud 8  does NOT use the share API for their own UI... rather use some internal json interface that requires their own magic auth cookies. Anyways, there is no documentation on what encoding is supported. At least it seems urlencoding (with encodeURIComponent) is not supported, and that is the de-facto solution in these cases...

**Comment by barrydegraaff** [comment]
https://doc.owncloud.org/api/classes/OCP.Util.html
encodePath(string  $component) : string
Public function to encode url parameters

This function is used to encode path to file before output. Encoding is done according to RFC 3986 with one exception: Character '/' is preserved as is.

So maybe we encode slashes as well?

**Comment by barrydegraaff** [comment]
https://doc.owncloud.org/server/7.0/developer_manual/android_library/examples.html
Paths must not be on URL Encoding
Correct path: http://www.myowncloudserver.com/owncloud/remote.php/webdav/PopMusic
Wrong path: http://www.myowncloudserver.com/owncloud/remote.php/webdav/Pop%20Music/

**Comment by barrydegraaff** [comment]
Well attaching files works, the link stuff is gonna take a bit more effort. It may be worth it to make a new feature that caches the document, so we are not relying on ownCloud/nextcloud to provide the share api.

**Comment by leo-yip** [comment]
with the new version, attached file works now.
tks.
waiting for the attached link.

**Comment by leo-yip** [comment]
When I try to save the attachment with chinese file name to webDAV:
![upload1](https://cloud.githubusercontent.com/assets/19850742/18266938/7f9a0864-744f-11e6-8030-4d0e83f7829b.png)

It seems the chinese filename cannot convert properly: 
![upload2](https://cloud.githubusercontent.com/assets/19850742/18266942/8507f43c-744f-11e6-80d4-43b3f3cf6344.png)

**Comment by barrydegraaff** [comment]
@leo-yip I have moved above comment to https://github.com/Zimbra-Community/owncloud-zimlet/issues/73

**Comment by barrydegraaff** [comment]
To fix this issues, one should install the latest version of ownCloud/Nextcloud from git, then use http poster extension in firefox or curl to make the request to the share api of ownCloud/nextcloud.... if that works, its a bug in this extensions code... but if not, its a bug in oc/nc and should be filed there.

The lack of documentation is a bug imho and may be a separate bug report.

For now I am lacking the time to debug.

**Comment by barrydegraaff** [comment]
This bug is also in nextcloud 11, and debugging further it seems it is a bug in Zimbra WebDAV Client, not owncloud.

This works:

      curl -H "OCS-APIRequest: true" -k 'https://user:password@localhost//nextcloud/ocs/v1.php/apps/files_sharing/api/v1/shares' -X POST --data "path=Documents/汉语漢語.odt&shareType=3"

**Comment by barrydegraaff** [comment]
@leo-yip sorry it took so long, this issue is fixed in the 0.6.9 release
