### ISSUE TITLE
"Send link(s)" doesn't work.

### ISSUE THREAD

**Issue by sematuszewski** [Zimbra-Community/owncloud-zimlet#71]
"Send link(s)" doesn't work.

Zimbra 8.6
OC 9.1
Zimlet latest

**Comment by barrydegraaff** [comment]
What did you put in the Preferences dialog?

**Comment by barrydegraaff** [comment]
Did you try with a regular filename? ASCII only and NOT UTF-8?

**Comment by sematuszewski** [comment]
Send link(s) (regular filename ASCII):
![link](https://cloud.githubusercontent.com/assets/3145872/18080855/7bb0b44a-6e97-11e6-93b6-029f00e65c0e.png)

Preferences dialog:
![settings](https://cloud.githubusercontent.com/assets/3145872/18080856/7bcaf468-6e97-11e6-817d-45f80a38f7e6.png)

**Comment by sematuszewski** [comment]
Send link(s) does not work because username contains "@".
I removed "@" and everything is working properly.

**Comment by barrydegraaff** [comment]
Thanks, I added a warning message, so next time, the user is shown a message the password may not be supported.

https://github.com/Zimbra-Community/owncloud-zimlet/commit/8a5eb3d2ae7a287b862b298723d59b1f8b6f6ca9
