### ISSUE TITLE
What does parameter "Location ownCloud/Nextcloud" mean?

### ISSUE THREAD

**Issue by thangnguyennang** [Zimbra-Community/owncloud-zimlet#76]
Hi,
In WebDAV client's preferences, I do not understand the meaning of the parameter "Location ownCloud/Nextcloud".  My questions:
1. Can you explain this parameter in details?
2. Can I leave this parameter blank by default? (see my note below).

Note: My DAV server (ownCloud) is running on a separate node. Users access it via the domain name "file.mydomain.com" as my design (not via the domain name file.mydomain.com/owncloud as your suggestion).

**Comment by barrydegraaff** [comment]
The parameter should contain the location where owncloud is
so
/owncloud
or in your case blank is OK

**Comment by thangnguyennang** [comment]
@barrydegraaff Thanks for your reply. I have another question:
If I leave this parameter "blank" as my goal, why when I reload webclient, this parameter automatically reset to "/owncloud"?
Note: My goal is that this parameter is always "blank" by default due to my design.

**Comment by barrydegraaff** [comment]
You can set the default value in config_template.xml

**Comment by thangnguyennang** [comment]
@barrydegraaff thanks.

**Comment by barrydegraaff** [comment]
Please check the updated readme, it should better explain all the config options.
