### ISSUE TITLE
HTTP ERROR 500 while opening file(s) in WebDAV tab

### ISSUE THREAD

**Issue by thangnguyennang** [Zimbra-Community/owncloud-zimlet#77]
Hi,
When I click file(s) in WebDAV tab, the preview window shows the error below:
HTTP ERROR 500
Problem accessing /service/extension/dav_download/. Reason: 
Powered by Jetty://

My environment and configs:
* Zimbra: 8.6 (latest patch).
* ownCloud: 0.4.3.
* WebDAV preferences:
- CalDAV Server: https://mail.mydomain.com.
- Port: 443.
- DAV path: /owncloud/remote.php/webdav/.
- Location ownCloud/Nextcloud: /owncloud
- Default folder: blank (by default).
- Must specify destination folder: unchecked (by default).
* DAV Server (ownCloud) is running on a separate node, its domain name "file.mydomain.com"
(I do not design its domain name as "file.mydomain.com/owncloud").

**Comment by thangnguyennang** [comment]
My configs on Zimbra server (Proxy service running on it):
location /owncloud/remote.php/webdav {
        proxy_pass      http://file.mydomain.com/remote.php/webdav;
 }
Note: The configs files modified on Zimbra server:
/opt/zimbra/conf/nginx/templates/nginx.conf.web.https.template
/opt/zimbra/conf/nginx/templates/nginx.conf.web.https.default.template

**Comment by barrydegraaff** [comment]
You can check the log in ownCloud and the log on the ZImbra server to see what gave the 500 error. Sometimes its an auth issue...

**Comment by barrydegraaff** [comment]
Probably need to clear `Location ownCloud/Nextcloud `

**Comment by thangnguyennang** [comment]
@barrydegraaff

**Comment by thangnguyennang** [comment]
@barrydegraaff The Zimbra Nginx log says that:
2016/09/27 14:38:35 [info] 26352#0: *466 client A.B.C.D closed keepalive connection.

**Comment by barrydegraaff** [comment]
On ownCloud check:
 /var/www/html/owncloud/data/owncloud.log
That location may vary, you can also find it in the ownCloud Admin area.

And on the Zimbra check:
/opt/zimbra/log/mailbox.log

**Comment by thangnguyennang** [comment]
@barrydegraaff **owncloud.log**:
{"reqId":"V@rxrLfgv0HGLoVTqDoSzgAAAAU","remoteAddr":"119.17.215.101","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 **Empty filename is not allowed**\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\InvalidPath\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1118): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChild(NULL)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(588): Sabre\\\\DAV\\\\Server->createCollection('', Object(Sabre\\\\DAV\\\\MkCol))\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":198,\"User\":\"demo\"}","level":4,"time":"2016-09-27T22:24:44+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/","user":"demo"}
**mailbox.log:**
2016-09-28 05:28:10,104 INFO  [qtp509886383-178:http://1.2.3.4:8080/service/soap/davSoapConnector] [name=demo@mydomain.com;mid=2815;ip=1.2.3.4;ua=ZimbraWebClient - FF48 (Linux)/8.6.0_GA_1200;] soap - davSoapConnector elapsed=6

**Note**:
* If I config parameter "CalDAV Server" to point to my ownCloud server's domain name directly, the feature works fine.
* But if I config parameter "CalDAV Server" to my Zimbra server's domain name (to use reverse proxy), the feature does not work.

**Comment by barrydegraaff** [comment]
I see you have configured your Zimbra proxy wrong. Anyway, using the proxy is not recommended anymore. So if it works without, its good.
