### ISSUE TITLE
Does each user have to fill their password in WebDAV preferences?

### ISSUE THREAD

**Issue by thangnguyennang** [Zimbra-Community/owncloud-zimlet#78]
Hi,
I see that in clients' WebDAV preferences, the parameter "**Password**" automatically filled by default whenever clients click the WebDAV preferences at the first time. So, I do not understand How this parameter automatically filled correctly, by default?
And, Do I have to talk to each client to fill their ownCloud password again whenever they click the WebDAV preferences at the first time?
**Note:** Via my test result, each client does not have to do that at the first time.

**Comment by thangnguyennang** [comment]
Additional infos: I config my ownCloud server to authenticate users by Zimbra LDAP by default (users not need to be created at ownCloud server).

**Comment by barrydegraaff** [comment]
Yah, ownCloud does not provide a pre-auth solution and the SAML looks un-maintained, what I do, in hosted environments is pre-populate the ldap using zmprov.

The good way would be either add SAML support to WebDAV client or pre-auth to owncloud.

But I do not have time or funding for that. So unless you have, you need to have the password.
