### ISSUE TITLE
Cannot share with password protected 

### ISSUE THREAD

**Issue by mkaliyannan** [Zimbra-Community/owncloud-zimlet#79]
I don't see any option to share the link with password protected like owncloud client.

**Comment by thangnguyennang** [comment]
You can use the option "Password setup" after clicking the menu "Attach from WebDAV" in your WebClient.

**Comment by barrydegraaff** [comment]
http://barrydegraaff.github.io/owncloud/#share-as-link
http://barrydegraaff.github.io/owncloud/share-as-link-dialog.png

**Comment by barrydegraaff** [comment]
Re-open as we need to add this to the menu in the DAV browser.

**Comment by barrydegraaff** [comment]
Just added, when one click `Send links` from the DAV browser, the user is asked to set password (optional).
