### ISSUE TITLE
Server error (unknown command sent to server) / OpenZAL installer bug on ZCS8.6

### ISSUE THREAD

**Issue by thangnguyennang** [Zimbra-Community/owncloud-zimlet#82]
Hi,
I've tested the latest version of the Zimlet with ZCS 8.6. After users logged in via webmail, Zimbra shows the following error:
Server error (unknown command sent to server).
method:	[unknown]
msg:	unknown document: davSoapConnector
code:	service.UNKNOWN_DOCUMENT
detail:	soap:Sender
trace:	qtp509886383-831:http://1.2.3.4:8080/service/soap/davSoapConnector:1475822270452:d793b31ba6446564
request:	

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><context xmlns="urn:zimbra"><userAgent xmlns="" name="ZimbraWebClient - FF48 (Linux)" version="8.6.0_GA_1191"/><session xmlns="" id="1668"/><account xmlns="" by="name">username@domain.com</account><format xmlns="" type="js"/><csrfToken xmlns="">0_fd410842e3a016b68c6c0e2e3b1fb33bcdd556ed</csrfToken></context></soap:Header><soap:Body><davSoapConnector xmlns="urn:zimbraAccount"><path xmlns="">/</path><dav_user_password xmlns="">HTTDTCVCB$2016</dav_user_password><action xmlns="">MKCOL</action></davSoapConnector></soap:Body></soap:Envelope>

**note:** 
* 1.2.3.4: IP address of my Zimbra server.
* username@domain.com: the logged in test account.
* ZCS version: Release 8.6.0_GA_1153.RHEL7_64_20141215151110 RHEL7_64 FOSS edition, Patch 8.6.0_P5.
* Zimlet version: 0.4.9.

**Comment by barrydegraaff** [comment]
I think its a bug in the installer, 

Check if you see 2 versions of zal:
 ls /opt/zimbra/lib/ext/ownCloud/

If yes, remove the 8.7 one:
rm -f /opt/zimbra/lib/ext/ownCloud/zal-1.10.6-8.7.0.jar

Then zmmailboxdctl restart

**Comment by thangnguyennang** [comment]
@barrydegraaff You're right, I see 2 versions of ZAL due to a bug in the installer. 
I'll try your suggestion and feedback you soon.

**Comment by thangnguyennang** [comment]
@barrydegraaff The issue has been resolved. My WebDAV client (ver 0.4.9) works fine now.
Solution: as your suggestion.
Note: It may be a bug in the installer script, so anyone can open a new issue related to this bug (bug of 2 version of ZAL), or can make pull request to solve it.

**Comment by barrydegraaff** [comment]
@bud-mo Hello Michele, can you take a look at the installer script and fix this bug?

The bug is that if one installs WebDAV Client on ZCS 8.6, it downloads 2 copies of zal jar into lib/ext.And then the WebDAV Client does not work.

For now the work-around is as in above comments. Thanks.

**Comment by bud-mo** [comment]
Hello @thangnguyennang and @barrydegraaff 
The issue is caused because in the `extension/lib` folder inside the repository is present a version of the zal jar.
Any version is good for the compile process of the extension, but when the installer download another version, both are copied into the extension path.
I suggest to remove the zal jar from the repository and download it before the compilation.

**Comment by barrydegraaff** [comment]
@thangnguyennang can you verify the patch, thanks!
