### ISSUE TITLE
Falla autoinstaller

### ISSUE THREAD

**Issue by Necropoly** [Zimbra-Community/owncloud-zimlet#83]
Hola, 

A continuación relaciono un error menor que se me presento en una instalación limpia:

/bin/sh: zip: no se encontró la orden
make[1]: *** [zimlet] Error 127
make[1]: se sale del directorio `/tmp/webdav-client-installer.fV42dsmh/owncloud-zimlet/zimlet'
make: *** [zimlet] Error 2

se soluciona: yum install zip

**Comment by barrydegraaff** [comment]
I added this to the installer, thanks!
