### ISSUE TITLE
Performance issue after upgrading WebDAV client to the latest version

### ISSUE THREAD

**Issue by thangnguyennang** [Zimbra-Community/owncloud-zimlet#86]
Hi,
I found that after upgrading WebDAV client to the latest version, it seemed to work very slow to load data from WebDAV server. My test flow was as below:
1. User login Webmail normally.
2. Email data loaded normally, but after that, the WebDAV client (Zimlet) loaded very slow (it took about 1 minute to load data).

After debugging, I found that it had an error in the WebDAV server. As this reason, the WebDAV client loaded very slow:
Exception: {"Message":"**HTTP\/1.1 400 Empty filename is not allowed**","Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\InvalidPath","Code":0,"Trace":"#0 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1118): OCA\\DAV\\Connector\\Sabre\\Directory->getChild(NULL)\n#1 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(588): Sabre\\DAV\\Server->createCollection('', Object(Sabre\\DAV\\MkCol))\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#5 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/html\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php(60): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/html\/nextcloud\/remote.php(165): require_once('\/var\/www\/html\/n...')\n
#8 {main}","File":"\/var\/www\/html\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","Line":199,"User":"myusername"}
**Note:** I did not change any configurations in the WebDAV server before upgrading the WebDAV client to the latest version.

**My environment:**
* WebDAV client: 0.5.3.
* WebDAV server: NextCloud 10.
* ZCS: 8.6 64-bit.
* OS: CentOS 7 64-bit.

**Comment by barrydegraaff** [comment]
Thanks for reporting, I patched the latest version, not to create folder on init time. I guess that is what caused the issue. Please check and let me know if this helps.

**Comment by thangnguyennang** [comment]
@barrydegraaff I'd like to udpate information even the issue closed:
After re-deploying my WebDAV server (NextCloud 10), this performance issue temporarily resolved.
I'll deploy the patched the latest version to know that this issue resolved completely or not.
Many thanks.

**Comment by barrydegraaff** [comment]
Yeah, I suspect is was a temporary issue. If you check history in the log, you will see the error 400/405 has been around for a while.

WebDAV Client has been doing the create-folder on init for a very long time. At least for half a year. Even ownCloud zimlet did this as well.

That said, I think in large installations, it is better not to do DAV requests on init time. So the newer version is better with that in mind.
