### ISSUE TITLE
FF49 Issues?

### ISSUE THREAD

**Issue by ThongSong7** [Zimbra-Community/owncloud-zimlet#97]
upon dev=1 :
##
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
<soap:Header>
<context xmlns="urn:zimbra">
<userAgent xmlns="" name="ZimbraWebClient - FF49 (Win)" version="8.7.0_GA_1659"/>
<session xmlns="" id="132"/>
-- Nothing was displayed in the Zimlet even though it says it got its SOAP envelope later down the log --
##
I changed my user agent in Firefox to that of:
"Mozilla/5.0 (Windows NT 10.0; rv:44.0) Gecko/20100101 Firefox/44.0"
and it worked flawlessly.

Strangely enough after clearing the browser cache and a "zmprov fc all"+"zmmailboxdctl restart"
and changing the agent back to:
"Mozilla/5.0 (Windows NT 10.0; rv:49.0) Gecko/20100101 Firefox/49.0"
it is working and showing as it should.

- I guest this is not really an issue, probably something local, just thought I would throw that out there since I saw nothing noted in here.

**Comment by barrydegraaff** [comment]
Did you only upgrade firefox? Or the WebDAV Client as well? Or Zimbra?

**Comment by ThongSong7** [comment]
I had only updated the WebDAV client from another version - sorry but I cannot remember which one - from about a month back? I deleted the allowed proxies (per instruction) and created the conf file per instruction.  It works still since changing the agent string, just seemed odd.

**Comment by barrydegraaff** [comment]
Owh, internally I changed the names of variables in SOAP requests, to be consistent.

As a result, if you use a cached version of the javascript files, the back-end no longer works with that. That is what you have seen. Flushing the cache, in the browser also, solved it. And is what is expected.

Also the changing of the SOAP solves https://github.com/Zimbra-Community/owncloud-zimlet/issues/96 

So all is well under control, thanks for reporting anyways.

**Comment by barrydegraaff** [comment]
changing the agent string flushed the cache in the browser, webdav client does NOT do ANY browser agent snooping

**Comment by barrydegraaff** [comment]
Do you like the new version?
