### ISSUE TITLE
Unchecking Zimlet in Preferences does not remove zimlet

### ISSUE THREAD

**Issue by mnichols62** [Zimbra-Community/owncloud-zimlet#98]
Installed webdav zimlet on Zimbra 8.7.1. When going to user preferences and unchecking the Webdav Zimlet, clicking save, the Zimlet is not removed for the user.

**Comment by barrydegraaff** [comment]
Hello Mark,

Yes, the only reason I not use zmzimletctl deploy, is to avoid cache issues, as people just don't get it.


If you zip all the files from that _dev/tk_barry.../ folder and put it in a zip file, the code will just work.

Thanks, Barry

**Comment by barrydegraaff** [comment]
See also:
https://github.com/Zimbra-Community/owncloud-zimlet/issues/67

**Comment by barrydegraaff** [comment]
Re-open: add to installer, ask user to deploy in _dev or with zmzimletctl deploy.

**Comment by barrydegraaff** [comment]
https://github.com/Zimbra-Community/owncloud-zimlet/blob/soapServiceBarry/webdav-client-installer.sh#L115

**Comment by barrydegraaff** [comment]
The installer has been updated, it will ask a question, asking the user if they want to manual deploy and do COS and Zimlet configuration.

Do you want to automatically install Zimlet and force enable it in all COS'es?
If you choose n you have to run zmzimletctl, configuration COS and set config_template.xml manually.
If you have trouble or are unsure, choose Y. Y/n:

If the user goes for manual install, all steps the user must to are showed to him after install:
To install Zimlet run as user Zimbra:"

    zmzimletctl deploy $TMPFOLDER/owncloud-zimlet/zimlet/tk_barrydegraaff_owncloud_zimlet.zip
    java -jar $TMPFOLDER/upgrade/prop2xml.jar tk_barrydegraaff_owncloud_zimlet     
    /opt/zimbra/lib/ext/ownCloud/config.properties /opt/zimbra/zimlets-deployed/tk_barrydegraaff_owncloud_zimlet/config_template.xml
    zmzimletctl configure /opt/zimbra/zimlets-deployed/tk_barrydegraaff_owncloud_zimlet/config_template.xml
    zmprov fc all
rm -Rf $TMPFOLDER"
Then go to the Admin Web Interface and enable Zimlet in the COS'es you want.

Should do
