### ISSUE TITLE
Select target folder each time

### ISSUE THREAD

**Issue by sempiterna** [Zimbra-Community/owncloud-zimlet#99]
Zimbra 8.7.1
Owncloud 9.0.2
Zimlet WebDav 0.6.5

Possible bugs:
- When I set a "Default folder" and enable "Must specify destination folder ", dragging e-mails to the zimlet does not present me with a dialog to select a folder. It copies it to the default folder.

- When I set a "Default folder" and enable "Must specify destination folder ", clicking on the "WebDav" link behind an attachment, presents me with a dialog, but only shows the default folder (e.g. "Zimbra/" ) and not my other folders which reside on the same tree level. Removing the default folder from the settings does result in showing all folders.

- Adminpanel: The zimlet is not visible at all in the adminpanel (Home-Configure-Zimlets), nor in Home-Configure-Class of Service - {cos name}. How does one disable or not enable by default for existing users?

**Comment by barrydegraaff** [comment]
Point 3, re-run the installer, when prompted:
 "Do you want to automatically install Zimlet and force enable it in all COS'es?"

choose the N no option. Then you can enable/disable the zimlet per user.

**Comment by barrydegraaff** [comment]
Must specify destination folder, at the moment is only implemented to show the folders **inside** the default folder, and only for the links at attachments. It is not yet implemented any further, as you found out.

**Comment by barrydegraaff** [comment]
see also:
https://github.com/Zimbra-Community/owncloud-zimlet/issues/36

**Comment by barrydegraaff** [comment]
@sempiterna also I looked into this, the `select folder each time` should not be enabled by default. But due to a bug it sorta was. For new users, it is now correctly disabled.

**Comment by barrydegraaff** [comment]
`Must specify destination folder ` the feature will not be extended for now. If you really want me to pick that up, consider a donation, thank you.
